### ISSUE TITLE
Issue in Download_media9)=

### ISSUE THREAD

**Issue by SakthiLK-dev** [pyrogram/pyrogram#1015]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I tried to download a file using bot client and I got this. 

 I do know that bot limit for downloading is somewhere around 20mb.

 I want to download files above that limit

### Steps to reproduce

Issue in app.download_media()

### Code example

```python
path = await client.download_media(message.reply_to_message,progress=progress,progress_args=(message.chat.id,current.message_id))
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Clara\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyrogram\client.py", line 499, in handle_download
    temp_file_path = await self.get_file(
  File "C:\Users\Clara\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyrogram\client.py", line 846, in get_file
    raise AuthBytesInvalid
pyrogram.errors.exceptions.bad_request_400.AuthBytesInvalid: [400 AUTH_BYTES_INVALID]: The authorization bytes are invalid
```

**Comment by odysseusmax** [comment]
Adding to the issue. 

In the latest Pyrogram, the same error is getting raised. In my case, I've set `max_concurrent_transmissions=5`. When there are multiple downloads (let's say 3 or 4) running concurrently and if the files are in different DCs `[400 AUTH_BYTES_INVALID]` is getting raised.

**Comment by covein** [comment]
I have the same problem, is this fixed yet?

**Comment by bitjerry** [comment]
My God, I have the same problem. I want to be able to download multiple files at the same time, queuing downloads is a waste of time.

**Comment by gjp1120** [comment]
same problem, download multiple files with `max_concurrent_transmissions=5` always cause this error

**Comment by kyoukisu** [comment]
any updates?
