### ISSUE TITLE
sqlite error

### ISSUE THREAD

**Issue by m1ch4elx** [pyrogram/pyrogram#1026]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Trying to run forwarder of messages and nothing working

### Steps to reproduce

1. Tried different versions of pyrogram, nothing worked

### Code example

```python
with app:
    sudo_users = get_formatted_chats(sudo_users, app)
    LOG.info(f"Sudo users - {sudo_users}")
    if len(to_chats) == 0 or len(from_chats) == 0:
      LOG.error("Set either ADVANCE_CONFIG or FROM_CHATS and TO_CHATS")
      sys.exit(1)
    else:
      from_chats = get_formatted_chats(from_chats, app)
      to_chats = get_formatted_chats(to_chats, app)
      LOG.info(f"From chats - {from_chats}")
      LOG.info(f"To chats - {to_chats}")
      time_str = datetime.now()
      time = time_str.strftime("%H:%M, %d/%m")
      app.send_message(chat_id=951893115, text=f"Forwarder запущен {time}")
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "E:\moi soft\telegram-message-forwarder-bot-main\bot\__init__.py", line 63, in <module>
    with app:
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 282, in __enter__
    return self.start()
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 565, in load_session
    await self.storage.open()
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\storage\file_storage.py", line 58, in open
    self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
sqlite3.OperationalError: unable to open database file
```

**Comment by LovanDog** [comment]
same error. up

**Comment by Kymymaru** [comment]
In my case, in the session name I indicated the name of a folder that did not exist. Something like this: Client(name='sessions/app')

After I created the sessions folder, the error disappeared.
