### ISSUE TITLE
Unable to Run the app with Flask

### ISSUE THREAD

**Issue by TelegramUsername** [pyrogram/pyrogram#1032]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When I try to run the Flask app in threading I am getting no current event loop error of asyncio

### Steps to reproduce

https://github.com/pyrogram/pyrogram/issues/480#issuecomment-684839155

### Code example

```python
https://github.com/pyrogram/pyrogram/issues/480#issuecomment-684839155
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request   
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\User\Coding\string sesison website\main.py", line 28, in hello_world
    with Client("account") as pyro:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 255, in __init__      
    self.dispatcher = Dispatcher(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 58, in __init__   
    self.loop = asyncio.get_event_loop()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-10 (process_request_thread)'.
```
```

**Comment by TelegramUsername** [comment]
@delivrance @ColinShark are requested to review

**Comment by NimaQu** [comment]
same issue after upgrade to pyrogram 2.0 

```
INFO:root:Starting webapi ....
Exception in thread WebThread:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\NimaQ\Desktop\dev\python\Telegram-CAPTCHA-bot-pyrogram\main.py", line 49, in start_web
    import web
  File "C:\Users\NimaQ\Desktop\dev\python\Telegram-CAPTCHA-bot-pyrogram\web.py", line 11, in <module>
    client = Client('web')
  File "C:\Users\NimaQ\Desktop\dev\python\Telegram-CAPTCHA-bot-pyrogram\venv\lib\site-packages\pyrogram\client.py", line 254, in __init__
    self.dispatcher = Dispatcher(self)
  File "C:\Users\NimaQ\Desktop\dev\python\Telegram-CAPTCHA-bot-pyrogram\venv\lib\site-packages\pyrogram\dispatcher.py", line 58, in __init__
    self.loop = asyncio.get_event_loop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'WebThread'.
```

**Comment by Hu-Wentao** [comment]
try run below code brfore import pyrogram
```python
import asyncio


def get_or_create_eventloop():
    try:
        return asyncio.get_event_loop()
    except RuntimeError as ex:
        if "There is no current event loop in thread" in str(ex):
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            return asyncio.get_event_loop()


__FIX_NO_CURRENT_EVENT_LOOP_RUNTIME_ERROR__ = get_or_create_eventloop()

```
