### ISSUE TITLE
Pyrogram not able to process tasks

### ISSUE THREAD

**Issue by EDM115** [pyrogram/pyrogram#1039]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When using some commands, or forwarding files to my bot, I get this :  
`Telegram says: [400 Bad Request] - [400 ENTITY_BOUNDS_INVALID] (caused by "messages.SendMessage")`  
  
I searched everywhere but this error message doesn't exist on the docs

### Steps to reproduce

idk if it's reproducible, as it's probably a bug from Telegram  
Moreover, it appeared without any code change from my side

### Logs

```shell
Telegram says: [400 Bad Request] - [400 ENTITY_BOUNDS_INVALID] (caused by "messages.SendMessage")
```

**Comment by EDM115** [comment]
@delivrance I can provide you sample code (that I use) and errors that came out  
  
```python
from pyrogram import Client, filters

@Client.on_message(filters.command("user"))
async def info_user(_, message: Message):
    info_user_msg = await message.reply(f"`Processing… ⏳`")
    try:
        user_id = message.text.split(None, 1)[1]
    except:
        return await info_user_msg.edit("Give an user id 🙂")
    up_count = get_uploaded(user_id)
    await info_user_msg.edit(f"**User ID :** `{user_id}`\n`{up_count}` files uploaded\n…\n\nWIP")
```
  
`get_uploaded()` is a working function that gets a value from DB, don't need to mind this  
here's the logs :  
  
```
2022-07-14 20:01:17,404 - INFO - __main__ - MainThread - Checking Log channel…
2022-07-14 20:01:17,541 - INFO - __main__ - MainThread - Starting bot…
2022-07-14 20:01:17,541 - INFO - __main__ - MainThread - Bot is running now ! Join @EDM115bots
2022-07-14 21:56:45,417 - ERROR - unzipper - MainThread - Telegram says: [400 Bad Request] - [400 ENTITY_BOUNDS_INVALID] (caused by "messages.SendMessage")
2022-07-14 22:36:36,349 - ERROR - pyrogram.dispatcher - MainThread - Telegram says: [400 Bad Request] - [400 ENTITY_BOUNDS_INVALID] (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/lib/python3.10/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/app/unzipper/modules/commands.py", line 237, in info_user
    await info_user_msg.edit(f"**User ID :** `{user_id}`\n`{up_count}` files uploaded\n…\n\nWIP")
  File "/usr/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2742, in edit_text
    return await self._client.edit_message_text(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/edit_message_text.py", line 83, in edit_message_text
    r = await self.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 80, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BadRequest: Telegram says: [400 Bad Request] - [400 ENTITY_BOUNDS_INVALID] (caused by "messages.EditMessage")
```

**Comment by EDM115** [comment]
this happens also when my bot need to process a file  
notice that this appeared 8-12 hours ago  
I didn't made any changes to my code, neither updating things  
  
So my bot doesn't process most of what it needs to  
most frustrating is that this error doesn't exist on the Documentation, maybe because no one faced it before ?

**Comment by EDM115** [comment]
The code lives here : https://github.com/EDM115/unzip-bot/tree/beta  
  
see the error in action : https://t.me/unzip_edm115bot  
send to him any archive  
ask him to extract  
**error** 🙂

**Comment by EDM115** [comment]
@delivrance This error seems to happen when we try to edit a message with one of the formatting tags (either html or markdown) empty  
  
Like "<b>Test</b> empty next <b></b>"  
Or "something ``"  
  
Hope this can help when for a better explanation on the docs 😉
