### ISSUE TITLE
socket.send() raised exception. Task exception was never retrieved.

### ISSUE THREAD

**Issue by boxxello** [pyrogram/pyrogram#1045]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello!
I'm experiencing this issue with the current release of pyrogram:

I read the [FAQ](https://docs.pyrogram.org/faq/socket-send-raised-exception-oserror-timeouterror) and that's probably due to inconsistencies in my connection, but is there anything that I can do instead of wrapping a while True around the app.run() in a try except, excepting for the OSError that it raises?

I made sure there's no blocking code in my code and I use the library as it's intended.
I tried seeking for help inside the Telegram channel to check if anyone had the same issue me but didn't actually get that much of help.

Thank you in advance.
This not either a bug report (at least as far as from what I see from the stacktrace) or either a feature request.

### Steps to reproduce

As far as from what I can see from the stacktrace it is due to a TCP issue (?), so there's no step do than just waiting for a tcp error while the bot is in idle.

### Code example

```python
app.run()
```

### Logs

```shell
[5] Retrying "updates.GetChannelDifference" due to Connection lost
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-139' coro=<Client.handle_updates() done, defined at C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\client.py:487> exception=OSError(ConnectionResetError('Connection lost'))>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\client.py", line 514, in handle_updates
    diff = await self.invoke(
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 381, in invoke
    return await self.invoke(query, retries - 1, timeout)
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 381, in invoke
    return await self.invoke(query, retries - 1, timeout)
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 381, in invoke
    return await self.invoke(query, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 374, in invoke
    raise e from None
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 315, in send
    raise e
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\session\session.py", line 312, in send
    await self.connection.send(payload)
  File "C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\site-packages\pyrogram\connection\connection.py", line 83, in send
    raise OSError(e)
```

**Comment by delivrance** [comment]
These are network issues. You should try with a stable connection.

**Comment by RobertAzovski** [comment]
@delivrance Hello. So how did you fix it ?
