### ISSUE TITLE
Forgot replace document_id to custom_emoji_id in 1 file

### ISSUE THREAD

**Issue by hittiks** [pyrogram/pyrogram#1063]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

In file pyrogram > raw > types > message_entity_custom_emoji.py in class MessageEntityCustomEmoji in ```__init__``` method (1) take argument document_id but in pyrogram > types > messages_and_media > message_entity.py in class MessageEntity in ```write``` method on line 123 have code ```return entity(**args)``` where args have custom_emoji_id, NOT document_id.

So I propose to replace document_id to custom_emoji_id in (1) method and change code from this:
```
    __slots__: List[str] = ["offset", "length", "document_id"]

    ID = 0xc8cf05f8
    QUALNAME = "types.MessageEntityCustomEmoji"

    def __init__(self, *, offset: int, length: int, document_id: int) -> None:
        self.offset = offset  # int
        self.length = length  # int
        self.document_id = document_id  # long

    @staticmethod
    def read(b: BytesIO, *args: Any) -> "MessageEntityCustomEmoji":
        # No flags
        
        offset = Int.read(b)
        
        length = Int.read(b)
        
        document_id = Long.read(b)
        
        return MessageEntityCustomEmoji(offset=offset, length=length, document_id=document_id)
```
to this:
```
    __slots__: List[str] = ["offset", "length", "custom_emoji_id"]

    ID = 0xc8cf05f8
    QUALNAME = "types.MessageEntityCustomEmoji"

    def __init__(self, *, offset: int, length: int, custom_emoji_id: int) -> None:
        self.offset = offset  # int
        self.length = length  # int
        self.document_id = custom_emoji_id # long

    @staticmethod
    def read(b: BytesIO, *args: Any) -> "MessageEntityCustomEmoji":
        # No flags
        
        offset = Int.read(b)
        
        length = Int.read(b)
        
        document_id = Long.read(b)
        
        return MessageEntityCustomEmoji(offset=offset, length=length, custom_emoji_id=document_id)
```

### Steps to reproduce

Just try to send message with custom emoji entity.

### Code example

```python
await cl.send_message(msg.chat.id, "😄😍🙃", entities=[MessageEntity(client=cl, type=MessageEntityType.CUSTOM_EMOJI, offset=0, length=2, custom_emoji_id=5366316836101038579)])
```

### Logs

```shell
__init__() got an unexpected keyword argument 'custom_emoji_id'
Traceback (most recent call last):
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "c:/Users/Skyline/Desktop/tg-userbot/main.py", line 1306, in test_func
    await cl.send_message(msg.chat.id, "😄😍🙃", entities=[MessageEntity(client=cl, type=MessageEntityType.CUSTOM_EMOJI, offset=0, length=2, custom_emoji_id=5366316836101038579)])   
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\messages\send_message.py", line 122, in send_message
    message, entities = (await utils.parse_text_entities(self, text, parse_mode, entities)).values()
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\utils.py", line 352, in parse_text_entities
    text, entities = text, [await entity.write() for entity in entities]
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\utils.py", line 352, in <listcomp>
    text, entities = text, [await entity.write() for entity in entities]
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\types\messages_and_media\message_entity.py", line 123, in write
    return entity(**args)
TypeError: __init__() got an unexpected keyword argument 'custom_emoji_id'
```

**Comment by delivrance** [comment]
Those are generated files and therefore not meant to be manually edited.
The issue has been addressed nonetheless.
