### ISSUE TITLE
EntityBoundsInvalid on ParseMode.DISABLED in explanation parameter of send_poll

### ISSUE THREAD

**Issue by annihilatorrrr** [pyrogram/pyrogram#1076]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

pyrogram.errors.exceptions.bad_request_400.EntityBoundsInvalid: Telegram says: [400 ENTITY_BOUNDS_INVALID] - The message entity bounds are invalid (caused by "messages.SendMedia")

Ig this error should not arrise if i specify ParseMode.DISABLED but this comes even after specifying.
Also there is nothing in the explanation text from my side that can create entity error.

### Steps to reproduce

try to send a poll with a explanation.

### Code example

```python
rm = await c.send_message(
            m.from_user.id,
            f"Hey, In oder to join {m.chat.title} you must answer correctly the below quiz under 10 mins!")
mid = await rm.reply_poll(
            'U ok ?',
            ['No', 'Yes', 'Hmm', 'Umm'],
            False,
            type=PollType.QUIZ,
            correct_option_id=0,
            explanation="Bruh!",
    )
```

### Logs

```shell
Traceback (most recent call last):
2022-08-28T14:08:42.780255+00:00 app[web.1]:   File "/app/sagiri/modules/greet.py", line 668, in senthepoll
2022-08-28T14:08:42.780256+00:00 app[web.1]:     mid = await rm.reply_poll(
2022-08-28T14:08:42.780257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2113, in reply_poll
2022-08-28T14:08:42.780257+00:00 app[web.1]:     return await self._client.send_poll(
2022-08-28T14:08:42.780272+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/messages/send_poll.py", line 143, in send_poll
2022-08-28T14:08:42.780272+00:00 app[web.1]:     r = await self.invoke(
2022-08-28T14:08:42.780273+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
2022-08-28T14:08:42.780273+00:00 app[web.1]:     r = await self.session.invoke(
2022-08-28T14:08:42.780274+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 361, in invoke
2022-08-28T14:08:42.780275+00:00 app[web.1]:     return await self.send(query, timeout=timeout)
2022-08-28T14:08:42.780275+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 331, in send
2022-08-28T14:08:42.780275+00:00 app[web.1]:     RPCError.raise_it(result, type(data))
2022-08-28T14:08:42.780276+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-08-28T14:08:42.780276+00:00 app[web.1]:     raise getattr(
2022-08-28T14:08:42.780277+00:00 app[web.1]: pyrogram.errors.exceptions.bad_request_400.EntityBoundsInvalid: Telegram says: [400 ENTITY_BOUNDS_INVALID] - The message entity bounds are invalid (caused by "messages.SendMedia")
```

**Comment by delivrance** [comment]
Fixed

**Comment by annihilatorrrr** [comment]
> Fixed

This commit created this bug: https://www.nekobin.com/xubusenoli

**Comment by delivrance** [comment]
Thanks. The newly introduced issue should now be fixed as well.
You can open a new issue in case you encounter any other problem.
