### ISSUE TITLE
message.react() raises AttributeError

### ISSUE THREAD

**Issue by roflanmen** [pyrogram/pyrogram#1086]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

whenever i try to use message.react(), with any arguments, it raises AttributeError

### Steps to reproduce

pip install pyrogram

then run code below:

### Code example

```python
from pyrogram import Client
from pyrogram import enums
import asyncio

api_id = 
api_hash = 

cid = (any chat id)

async def main():
    app = Client("my_account", api_id=api_id, api_hash=api_hash)
    async with app:
        await app.send_message("me", "Hi!")
        async for message in app.search_messages(cid, limit=1, from_user=(any user name)):
            await message.react(emoji="🔥")

asyncio.run(main())
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\tempCodeRunnerFile.python", line 18, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Temp\tempCodeRunnerFile.python", line 15, in main
    await message.react(emoji="🔥")
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\types\messages_and_media\message.py", line 3341, in react
    return await self._client.send_reaction(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\methods\messages\send_reaction.py", line 62, in send_reaction
    await self.invoke(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\session\session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\session\session.py", line 290, in send
    message = self.msg_factory(data)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\raw\functions\messages\send_reaction.py", line 93, in write
    b.write(Vector(self.reaction))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'str' object has no attribute 'write'
```

**Comment by delivrance** [comment]
Fixed.
