### ISSUE TITLE
I got stuck in the first step

### ISSUE THREAD

**Issue by mehranj73** [pyrogram/pyrogram#109]
I get the following error, and I checked everything multiple times.
Traceback (most recent call last):
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\client\client.py", line 927, in load_session
    with open(os.path.join(self.workdir, "{}.session".format(self.session_name)), encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\My_session.session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Mehran/PycharmProjects/new/apikey.py", line 9, in <module>
    app.run()
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\client\client.py", line 331, in run
    self.start()
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\client\client.py", line 208, in start
    self.load_session()
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\client\client.py", line 932, in load_session
    self.auth_key = Auth(self.dc_id, self.test_mode, self._proxy).create()
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\session\auth.py", line 266, in create
    raise e
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\session\auth.py", line 92, in create
    self.connection.connect()
  File "C:\Users\Mehran\PycharmProjects\python3.6\new\lib\site-packages\pyrogram\connection\connection.py", line 59, in connect
    raise TimeoutError
TimeoutError

Process finished with exit code 1

**Comment by delivrance** [comment]
Hi, looks like Telegram is blocked in your country and Pyrogram can't connect.
Can you try with a [proxy](https://docs.pyrogram.ml/resources/SOCKS5Proxy)?

**Comment by mehranj73** [comment]
yeah, I fixed it with a VPN.
