### ISSUE TITLE
Cannot invite contacts to private group chat

### ISSUE THREAD

**Issue by qianmianyao** [pyrogram/pyrogram#1093]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Cannot invite contacts to private group chat

### Steps to reproduce

1. Get your own contact id
2. Invite your contacts to join your private group chat

### Code example

```python
logger.debug(await app.get_chat("https://t.me/+m9qJxEjDN0NmOTZl"))

        uid = await get_contacts(app)
        logger.debug(len(uid))

        for i in uid:
            result = await app.get_users(i)
            logger.debug({"id": result.id, "first_name": result.first_name})
            await app.add_chat_members("https://t.me/+m9qJxEjDN0NmOTZl", result.id)
```

### Logs

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 148, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: https://t.me/+m9qJxEjDN0NmOTZl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 69, in resolve_peer
    int(peer_id)
ValueError: invalid literal for int() with base 10: 'https://t.me/m9qjxejdn0nmotzl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 72, in resolve_peer
    return await self.storage.get_peer_by_username(peer_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 159, in get_peer_by_username
    raise KeyError(f"Username not found: {username}")
KeyError: 'Username not found: https://t.me/m9qjxejdn0nmotzl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhoupeng/Downloads/L2480/server/tests/test.py", line 150, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/zhoupeng/Downloads/L2480/server/tests/test.py", line 98, in main
    await app.add_chat_members("https://t.me/+m9qJxEjDN0NmOTZl", result.id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/chats/add_chat_members.py", line 63, in add_chat_members
    peer = await self.resolve_peer(chat_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 74, in resolve_peer
    await self.invoke(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UsernameInvalid: Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")
```

**Comment by delivrance** [comment]
> Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")

**Comment by qianmianyao** [comment]
> > Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")

Thank you for your reply, is there any way to invite contacts to join the group chat using the invitation link above?

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
