### ISSUE TITLE
Why does the method `promote_chat_member` not work in groups?

### ISSUE THREAD

**Issue by qianmianyao** [pyrogram/pyrogram#1099]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Why the method `promote_chat_member` can't be used in group, but only in supergroup, is there an alternative to this method in group?

### Steps to reproduce

Why the method `promote_chat_member` can't be used in group, but only in supergroup, is there an alternative to this method in group?

### Code example

```python
# Promote chat member to admin
await app.promote_chat_member(chat_id, user_id)
```

### Logs

```shell
[2022-09-12 15:25:51,645: ERROR/MainProcess] Task invitation[3e5ee59b-f7ad-4b08-bfe4-9644ecb360fe] raised unexpected: ChannelInvalid('Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.EditAdmin")')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/celery_pool_asyncio/tracer.py", line 197, in trace_task
    R = retval = coro_task.result()
  File "/Users/zhoupeng/Downloads/L2480/server/api/task.py", line 522, in invitation_task
    return await invitation(tg_user_id, group_link)
  File "/Users/zhoupeng/Downloads/L2480/server/api/task.py", line 481, in invitation
    admin = await app.promote_chat_member(results.id, admin_user.id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/sync.py", line 74, in coro_wrapper
    return await asyncio.wrap_future(asyncio.run_coroutine_threadsafe(coroutine, main_loop))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/chats/promote_chat_member.py", line 78, in promote_chat_member
    await self.invoke(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/sync.py", line 74, in coro_wrapper
    return await asyncio.wrap_future(asyncio.run_coroutine_threadsafe(coroutine, main_loop))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.EditAdmin")
```

**Comment by clot27** [comment]
This method only works in channel and supergroup, not basic groups. See create_supergroup (https://docs.pyrogram.org/api/methods/create_supergroup)
