### ISSUE TITLE
run error - update handler

### ISSUE THREAD

**Issue by Roy5000** [pyrogram/pyrogram#110]
I used Pyrogram to receive message updates and the script worked perfect until today.  Now even a simple example like below does not work anymore.  (after re-install of pyrogram package I still have same issue.)

The error message does not give enough guidelines to identify the root cause,  anyone a suggestion what could be wrong?

test example:

```
from pyrogram import Client

app = Client("my_account",
             api_id= xxxxxx,
             api_hash='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
             )


@app.on_message()
def my_handler(client, message):
    print(message)


app.run()
```

run results in error:
```
Traceback (most recent call last):
  File "C:/Users/RA/PycharmProjects/Pyrogram/app6.py", line 15, in <module>
    app.run()
  File "C:\Users\RA\PycharmProjects\Pyrogram\venv\lib\site-packages\pyrogram\client\client.py", line 331, in run
    self.start()
  File "C:\Users\RA\PycharmProjects\Pyrogram\venv\lib\site-packages\pyrogram\client\client.py", line 208, in start
    self.load_session()
  File "C:\Users\RA\PycharmProjects\Pyrogram\venv\lib\site-packages\pyrogram\client\client.py", line 928, in load_session
    s = json.load(f)
  File "C:\Users\RA\AppData\Local\Programs\Python\Python36\Lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\RA\AppData\Local\Programs\Python\Python36\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\RA\AppData\Local\Programs\Python\Python36\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\RA\AppData\Local\Programs\Python\Python36\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

'''

**Comment by delivrance** [comment]
Hi, there's nothing wrong in your code. The problem is in your session file (`my_account.session`) which somehow got scrambled and is not a valid JSON anymore, that's why Pyrogram can't read it.

The main cause of this is that you likely used the **same** session with more than one Client at the same time, which is something not supported by Pyrogram (not even by the server). If you want to use more clients at the same time you have to use separate sessions for each one.

Personally I've never encountered this problem, but if you believe you did nothing wrong we can try to investigate further.

**Comment by Roy5000** [comment]
Thank you delivrance,  creation of new session file solved the issue.
