### ISSUE TITLE
while try to send document , i got error AttributeError: 'NoneType' object has no attribute 'is_premium'

### ISSUE THREAD

**Issue by jakbin** [pyrogram/pyrogram#1106]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

while try to send document , i got error.
```
file_size_limit_mib = 4000 if self.me.is_premium else 2000
AttributeError: 'NoneType' object has no attribute 'is_premium'
```

### Steps to reproduce

1. i just create a pyrogram client and try to upload file.

### Code example

```python
client = Client(f"sessions/{phone}", api_id, api_hash)

client.connect()


def progress(current, total):
    print(f"{current * 100 / total:.1f}%")

client.send_document(channel, file_name, caption=caption, progress=progress)
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/dj/Desktop/pyro/file-uploader/main.py", line 49, in <module>
    client.send_document(channel, file_name, caption=caption, progress=progress)
  File "/home/dj/.local/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/dj/.local/lib/python3.10/site-packages/pyrogram/methods/messages/send_document.py", line 161, in send_document
    file = await self.save_file(document, progress=progress, progress_args=progress_args)
  File "/home/dj/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 128, in save_file
    file_size_limit_mib = 4000 if self.me.is_premium else 2000
AttributeError: 'NoneType' object has no attribute 'is_premium'
```

**Comment by delivrance** [comment]
This is not an issue with the library, but rather an issue with your usage.
You are not properly starting the client. See https://docs.pyrogram.org/start/invoking.

**Comment by jakbin** [comment]
Thanks , it works.
