### ISSUE TITLE
got "FileNotFoundError" when downloading file from telegram

### ISSUE THREAD

**Issue by wulan17** [pyrogram/pyrogram#1111]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Im use message.download(filename) in my bot to do an ocr task, but i got FileNotFoundError exceptions
the Exception is gone when im downgrade my pyrogram to v2.0.52

### Steps to reproduce

1. Upgrade pyrogram to v2.0.53 and above
2. Download file from telegram using pyrogram

### Code example

```python
# download file to file_name
target = await message.download(file_name)
```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wulan17/Mayuri_mk2/mayuri/images/bl/CAACAgUAAx0CSGY3xQABDKgDYzWEAi6Q4TJwkVt_JZu_qEQOa7UAAgkCAAIwwDlWh3E9AnoaxUAeBA.webp.temp' -> '/home/wulan17/Mayuri_mk2/mayuri/images/bl/CAACAgUAAx0CSGY3xQABDKgDYzWEAi6Q4TJwkVt_JZu_qEQOa7UAAgkCAAIwwDlWh3E9AnoaxUAeBA.webp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wulan17/Mayuri_mk2/mayuri/plugins/gblacklist.py", line 340, in gbl_task
    target = await m.download(target)
  File "/home/wulan17/Mayuri_mk2/venv/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 3446, in download
    return await self._client.download_media(
  File "/home/wulan17/Mayuri_mk2/venv/lib/python3.10/site-packages/pyrogram/methods/messages/download_media.py", line 183, in download_media
    return await downloader
  File "/home/wulan17/Mayuri_mk2/venv/lib/python3.10/site-packages/pyrogram/client.py", line 752, in handle_download
    shutil.move(temp_file_path, file_path)
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wulan17/Mayuri_mk2/mayuri/images/bl/CAACAgUAAx0CSGY3xQABDKgDYzWEAi6Q4TJwkVt_JZu_qEQOa7UAAgkCAAIwwDlWh3E9AnoaxUAeBA.webp.temp'
```

**Comment by delivrance** [comment]
Couldn't reproduce the issue with the information given. Files download fine even with custom directories and name using the bound method `message.download(...)`.
