### ISSUE TITLE
functions.channels.GetFullChannel not working

### ISSUE THREAD

**Issue by SPIDER-L33T** [pyrogram/pyrogram#1119]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

GetFullChannel not working.

### Steps to reproduce

For example i wrote simple echo-bot, but GetFullChannel is not working.

### Code example

```python
from pyrogram import Client, filters, enums
from pyrogram.raw import functions, types

app = Client(username, api_id, api_hash)

@app.on_message(filters.text)
async def echo(client, message):
    if message.text == "test":
        r = await app.invoke(functions.channels.GetFullChannel(channel=-100********21))
        print(r)
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/******/.local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "**************.py", line 84, in echo
    ret = await app.invoke(functions.channels.GetFullChannel(channel=-100********21))
  File "/home/*****/.local/lib/python3.9/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/home/*****/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/******/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 290, in send
    message = self.msg_factory(data)
  File "/home/*****/.local/lib/python3.9/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/home/*****/.local/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 79, in __len__
    return len(self.write())
  File "/home/******/.local/lib/python3.9/site-packages/pyrogram/raw/functions/channels/get_full_channel.py", line 69, in write
    b.write(self.channel.write())
AttributeError: 'int' object has no attribute 'write'
```

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
Also, see https://docs.pyrogram.org/topics/advanced-usage.
