### ISSUE TITLE
Why does the method DeleteChatUser not work in groups?

### ISSUE THREAD

**Issue by natmars** [pyrogram/pyrogram#1140]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Why the method DeleteChatUser can't be used in group, but only in supergroup, is there an alternative to this method in group?

### Steps to reproduce

Why the method DeleteChatUser can't be used in group, but only in supergroup, is there an alternative to this method in group?

### Code example

```python
app = Client(PYROGRAM_SESSION_NAME)
with app:
    # удаляем в telegram
    input_user = app.resolve_peer(u.telegram_id)
    app.invoke(DeleteChatUser(chat_id=int(chat.telegram_id), user_id=input_user))
```

### Logs

```shell
Traceback (most recent call last):
  File "/code/manage.py", line 22, in <module>
    main()
  File "/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/icb/management/commands/block_user.py", line 16, in handle
    block_user(worker_id)
  File "/code/services/manage_chat.py", line 92, in block_user
    app.invoke(DeleteChatUser(chat_id=chat.telegram_id, user_id=input_user))
  File "/usr/local/lib/python3.11/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChatIdInvalid: Telegram says: [400 CHAT_ID_INVALID] - The chat id being used is invalid or not known yet. Make sure you see the chat before interacting with it (caused by "messages.DeleteChatUser")
```

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
