### ISSUE TITLE
import pyrogram raises RuntimeError: There is no current event loop in MainThread

### ISSUE THREAD

**Issue by YutaRedux** [pyrogram/pyrogram#1150]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When you import Pyrogram or any object in the library, it raises `RuntimeError: There is no current event loop in thread 'MainThread'.`  

### Steps to reproduce

1. Import Pyrogram
2. ...
3. done

### Code example

```python
from pyrogram.client import Client  # will raise
from pyrogram import __version__  # will raise too!
import pyrogram  # raises too
```

### Logs

```shell
Traceback (most recent call last):
 File "C:\Проекты\TelePower\safe_main.py", line 4, in <module>
    from services.account import AccountService
  File "C:\Проекты\TelePower\services\account\__init__.py", line 2, in <module>
    from .model import Account
  File "C:\Проекты\TelePower\services\account\model.py", line 4, in <module>
    from pyrogram import __version__
  File "C:\Users\yutar\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\__init__.py", line 40, in <module>
    from .sync import idle, compose
  File "C:\Users\yutar\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\sync.py", line 99, in <module>
    wrap(Methods)
  File "C:\Users\yutar\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\sync.py", line 95, in wrap
    async_to_sync(source, name)
  File "C:\Users\yutar\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\sync.py", line 31, in async_to_sync
    main_loop = asyncio.get_event_loop()
  File "C:\Users\yutar\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by delivrance** [comment]
This is unrelated. If simply importing had generated such error I would have noticed.
