### ISSUE TITLE
Empty messages cannot be copied.  Add except

### ISSUE THREAD

**Issue by davidleboblai** [pyrogram/pyrogram#1158]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

https://github.com/pyrogram/pyrogram/blob/ad773455a74ef6db7c1752734b6fe9b6647870c6/pyrogram/types/messages_and_media/message.py#L3054

You should add except for copy empty message
To try catching the error

### Steps to reproduce

https://github.com/pyrogram/pyrogram/blob/ad773455a74ef6db7c1752734b6fe9b6647870c6/pyrogram/types/messages_and_media/message.py#L3054

### Code example

```python
https://github.com/pyrogram/pyrogram/blob/ad773455a74ef6db7c1752734b6fe9b6647870c6/pyrogram/types/messages_and_media/message.py#L3054
```

### Logs

```shell
https://github.com/pyrogram/pyrogram/blob/ad773455a74ef6db7c1752734b6fe9b6647870c6/pyrogram/types/messages_and_media/message.py#L3054
```

**Comment by JackHerer1337** [comment]
channel -1001215974918 💎GREEN DIAMOND vip💎
Can't copy this message
Traceback (most recent call last):
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\dispatcher.py", line 219, in handler_worker
    await self.loop.run_in_executor(
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mac\bot.py", line 38, in g_msgs
    app.copy_message(gnm.de[message.chat.id],from_chat_id=message.chat.id , message_id=message.message_id)
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\sync.py", line 50, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\messages\copy_message.py", line 107, in copy_message
    return await message.copy(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\types\messages_and_media\message.py", line 3023, in copy
    raise ValueError("Can't copy this message")
ValueError: Can't copy this message

**Comment by JackHerer1337** [comment]
'Message' object has no attribute 'message_id'
Traceback (most recent call last):
File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\dispatcher.py", line 242, in handler_worker
await [self.loop.run](http://self.loop.run/)_in_executor(
File "C:\Users\mac\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\mac\Desktop\bot.py", line 38, in g_msgs
app.copy_message([gnm.de](http://gnm.de/)[[message.chat.id](http://message.chat.id/)],from_chat_id=message.chat.id , message_id=message.message_id)
^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'message_id'
