### ISSUE TITLE
'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by KODYAcoder** [pyrogram/pyrogram#1165]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hi, i'm requesting the code for auth using function send_code but your lib says this: "'int' object has no attribute 'encode'"
Input number format is str
![image](https://user-images.githubusercontent.com/97844699/207926957-e6c7d7d7-5ce7-4f80-9877-941fd858677a.png)
![image](https://user-images.githubusercontent.com/97844699/207926979-c50eb7d9-b4df-4952-97a7-bfef6a516ed9.png)

### Steps to reproduce

1

### Code example

```python
try:
   sent = await app.send_code(result[1])
except Exception as e:
   logger.error(e)
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\KODYA\Desktop\sas\main.py", line 174, in <module>
    asyncio.run(main())
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\KODYA\Desktop\sas\main.py", line 60, in main
    await asyncio.wait_for(logic(result), timeout=300)
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\KODYA\Desktop\sas\main.py", line 82, in logic
    sent = await app.send_code(result[1])
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\auth\send_code.py", line 54, in send_code
    r = await self.invoke(
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 290, in send
    message = self.msg_factory(data)
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\raw\functions\auth\send_code.py", line 92, in write
    b.write(String(self.api_hash))
  File "C:\Users\KODYA\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\string.py", line 31, in __new__
    return super().__new__(cls, value.encode())
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by KODYAcoder** [comment]
Solved by sending API_ID as string (Lol)
