### ISSUE TITLE
Video upload: descriptor 'to_bytes' requires a 'int' object but received a 'float'

### ISSUE THREAD

**Issue by zeroone2numeral2** [pyrogram/pyrogram#117]
Hello there,

I just ran in to an issue while uploading from disk an mp4 file using the `send_video` method.

This is the traceback:
```
[2018-09-10 14:59:58,063][utils.utils][INFO] >>> error while running handler callback: descriptor 'to_bytes' requires a 'int' object but received a 'float'
Traceback (most recent call last):
  File "/root/ytdl-bot/utils/utils.py", line 43, in wrapped
    return func(client, message, *args, **kwargs)
  File "main.py", line 167, in download_media
    duration=media.duration
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/methods/messages/media/send_video.py", line 182, in send_video
    **style.parse(caption)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 801, in send
    r = self.session.send(data)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 417, in send
    return self._send(data)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 383, in _send
    message = self.msg_factory(data)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/core/object.py", line 47, in __len__
    return len(self.write())
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/functions/messages/send_media.py", line 101, in write
    b.write(self.media.write())
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/types/input_media_uploaded_document.py", line 85, in write
    b.write(Vector(self.attributes))
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/core/primitives/vector.py", line 52, in __new__
    for i in value
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    for i in value
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/types/document_attribute_video.py", line 68, in write
    b.write(Int(self.duration))
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/core/primitives/int.py", line 32, in __new__
    return int.to_bytes(value, cls.SIZE, "little", signed=signed)
TypeError: descriptor 'to_bytes' requires a 'int' object but received a 'float'
```

This issue rarely happens but it's not random and I've been able to reproduce only with a specific video file, that I am able to play or upload using TDesktop or the bot API (so the file should be ok). Unfortunately I can not share the video itself because of private content, I'm sorry. Will share a video as soon as I am able to reproduce with another one. [These](https://i.imgur.com/k9sKLaY.jpg) are the video streams data.

**Comment by zeroone2numeral2** [comment]
Hold on, I just saw it might be a problem with the `duration` argument being a float

**Comment by zeroone2numeral2** [comment]
Yep nvm. Sorry

**Comment by delivrance** [comment]
Oops
