### ISSUE TITLE
ValueError: <class 'pyrogram.raw.types.auth.sent_code_type_email_code.SentCodeTypeEmailCode'>  is not a valid SentCodeType

### ISSUE THREAD

**Issue by maximyurevich** [pyrogram/pyrogram#1183]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

ValueError: <class 'pyrogram.raw.types.auth.sent_code_type_email_code.SentCodeTypeEmailCode'>
 is not a valid SentCodeType

### Steps to reproduce

1. Run python telegram_service.py
2. Input phone number
3. Enter y
4. I get an error and a telegram code in the mail

### Code example

```python
from pyrogram import Client

api_id = **
api_hash = "***"

app = Client("my_account", api_id=api_id, api_hash=api_hash)

app.run()
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/maxim/Desktop/**/backend/app/services/telegram_service.py", line 10, in <m
odule>
    app.run()
  File "/home/maxim/.cache/pypoetry/virtualenvs/**-QvaYT4s1-py3.10/lib/python3.1
0/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/home/maxim/.cache/pypoetry/virtualenvs/**-QvaYT4s1-py3.10/lib/python3.1
0/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/maxim/.cache/pypoetry/virtualenvs/**-QvaYT4s1-py3.10/lib/python3.1
0/site-packages/pyrogram/methods/utilities/start.py", line 62, in start
    await self.authorize()
  File "/home/maxim/.cache/pypoetry/virtualenvs/**-QvaYT4s1-py3.10/lib/python3.1
0/site-packages/pyrogram/client.py", line 347, in authorize
    sent_code = await self.send_code(self.phone_number)
  File "/home/maxim/.cache/pypoetry/virtualenvs/**-QvaYT4s1-py3.10/lib/python3.1
0/site-packages/pyrogram/methods/auth/send_code.py", line 79, in send_code
    return types.SentCode._parse(r)
  File "/home/maxim/.cache/pypoetry/virtualenvs/**-QvaYT4s1-py3.10/lib/python3.1
0/site-packages/pyrogram/types/authorization/sent_code.py", line 58, in _parse
    type=enums.SentCodeType(type(sent_code.type)),
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: <class 'pyrogram.raw.types.auth.sent_code_type_email_code.SentCodeTypeEmailCode'>
 is not a valid SentCodeType
```

**Comment by BlackBird09** [comment]
Anyone can answer it, i get same isue

**Comment by BlackBird09** [comment]
![Uploading Screenshot_20221229-210926_Termux.png…]()

**Comment by maximyurevich** [comment]
> Pyrogram not Use Auth With Email Address Yet , you must wait for future updates.

Telethon too, but confirmation codes come in telegram
