### ISSUE TITLE
AttributeError: 'MessageMediaWebPage' object has no attribute 'spoiler'

### ISSUE THREAD

**Issue by DataReset** [pyrogram/pyrogram#1184]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I try to get all dialogs with app.get_dialogs() but it throws exception AttributeError: 'MessageMediaWebPage' object has no attribute 'spoiler'

### Steps to reproduce

I don't know how to reproduce

### Code example

```python
from pyrogram.client import Client
app = Client("session")
async def main():
    async with app:
      async for dialog in app.get_dialogs():
                    print(dialog.chat.first_name or dialog.chat.title)
app.run(main())
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/danya/parsetg/main.py", line 18, in <module>
    app.run(main())
  File "/home/danya/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 77, in run
    run(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/danya/parsetg/main.py", line 16, in main
    async for dialog in app.get_dialogs():
  File "/home/danya/venv/lib/python3.10/site-packages/pyrogram/methods/chats/get_dialogs.py", line 79, in get_dialogs
    messages[chat_id] = await types.Message._parse(self, message, users, chats)
  File "/home/danya/venv/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 785, in _parse
    has_media_spoiler=media and media.spoiler,
AttributeError: 'MessageMediaWebPage' object has no attribute 'spoiler'
```

**Comment by DataReset** [comment]
thx, fixed!
