### ISSUE TITLE
Getting TypeError due to changes in Pyrogram after v2.0.70

### ISSUE THREAD

**Issue by Mahesh0253** [pyrogram/pyrogram#1185]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Sometime I'm getting below errors in logs while uploading files. After Pyrogram v2.0.70 many changes were made for handling connection and security checks which causing this issue. Currently I'm using Pyrogram v2.0.92 and I have tested this on two different servers so it is not connectivity issue from server side.

```TypeError: Value after * must be an iterable, not NoneType```

### Steps to reproduce

You can try to run below code. As these errors are not consistent so I'm not sure below code will reproduce same errors or not.

### Code example

```python
import asyncio
from pyrogram import Client


file_path = './1GB.bin'

async def main():
    async with Client("my_account") as app:
        await app.send_document("me", document=file_path)


asyncio.run(main())
```

### Logs

```shell
[31/12/2022 03:08:39 PM:pyrogram.methods.advanced.save_file:108:ERROR] Value after * must be an iterable, not NoneType
Traceback (most recent call last):
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/methods/advanced/save_file.py", line 108, in worker
    await session.invoke(data)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 378, in invoke
    return await self.send(query, timeout=timeout)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 326, in send
    await self.connection.send(payload)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/connection/connection.py", line 69, in send
    await self.protocol.send(data)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/connection/transport/tcp/tcp_abridged_o.py", line 61, in send
    payload = await self.loop.run_in_executor(pyrogram.crypto_executor, aes.ctr256_encrypt, data, *self.encrypt)
TypeError: Value after * must be an iterable, not NoneType
[31/12/2022 04:00:32 PM:pyrogram.methods.advanced.save_file:108:ERROR] Value after * must be an iterable, not NoneType
Traceback (most recent call last):
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/methods/advanced/save_file.py", line 108, in worker
    await session.invoke(data)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 378, in invoke
    return await self.send(query, timeout=timeout)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 326, in send
    await self.connection.send(payload)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/connection/connection.py", line 69, in send
    await self.protocol.send(data)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/connection/transport/tcp/tcp_abridged_o.py", line 61, in send
    payload = await self.loop.run_in_executor(pyrogram.crypto_executor, aes.ctr256_encrypt, data, *self.encrypt)
TypeError: Value after * must be an iterable, not NoneType
[31/12/2022 04:59:21 PM:pyrogram.methods.advanced.save_file:108:ERROR] Value after * must be an iterable, not NoneType
Traceback (most recent call last):
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/methods/advanced/save_file.py", line 108, in worker
    await session.invoke(data)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 378, in invoke
    return await self.send(query, timeout=timeout)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 326, in send
    await self.connection.send(payload)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/connection/connection.py", line 69, in send
    await self.protocol.send(data)
  File "/root/uploader2/venv/lib/python3.9/site-packages/pyrogram/connection/transport/tcp/tcp_abridged_o.py", line 61, in send
    payload = await self.loop.run_in_executor(pyrogram.crypto_executor, aes.ctr256_encrypt, data, *self.encrypt)
TypeError: Value after * must be an iterable, not NoneType
```

**Comment by md5hash16** [comment]
Yes I got that message also

**Comment by Cosangeles55** [comment]
AttributeError: 'NoneType' object has no attribute 'is_premium':

message_obj = await  self.app.send_photo(chat_id=chat_id, photo=file_path)

Error:

backend  | Traceback (most recent call last):
backend  |   File "/backend/./telegram/api/messages.py", line 53, in post
backend  |     message_obj = await  self.app.send_photo(chat_id=chat_id, photo=file_path)
backend  |   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/messages/send_photo.py", line 153, in send_photo
backend  |     file = await self.save_file(photo, progress=progress, progress_args=progress_args)
backend  |   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/save_file.py", line 130, in save_file
backend  |     file_size_limit_mib = 4000 if self.me.is_premium else 2000
backend  | AttributeError: 'NoneType' object has no attribute 'is_premium'

**Comment by Mahesh0253** [comment]
> AttributeError: 'NoneType' object has no attribute 'is_premium':
> 
> message_obj = await  self.app.send_photo(chat_id=chat_id, photo=file_path)
> 
> Error:
> 
> backend  | Traceback (most recent call last):
> backend  |   File "/backend/./telegram/api/messages.py", line 53, in post
> backend  |     message_obj = await  self.app.send_photo(chat_id=chat_id, photo=file_path)
> backend  |   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/messages/send_photo.py", line 153, in send_photo
> backend  |     file = await self.save_file(photo, progress=progress, progress_args=progress_args)
> backend  |   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/save_file.py", line 130, in save_file
> backend  |     file_size_limit_mib = 4000 if self.me.is_premium else 2000
> backend  | AttributeError: 'NoneType' object has no attribute 'is_premium'
> 
> 
> 
> 

This is different TypeError and it is not related to this issue.

**Comment by delivrance** [comment]
This has been addressed in the latest version by limiting concurrent transfers.
