### ISSUE TITLE
Telegram Primium Account Cant Login 

### ISSUE THREAD

**Issue by PouryaDe** [pyrogram/pyrogram#1186]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

it works well in Normal Telegram Accounts 
but i cant login Primium Account with pyogram!

i get this error:

### Steps to reproduce

i cant login Primium Account with pyogram

### Logs

```shell
Welcome to Pyrogram (version 2.0.88)
Pyrogram is free software and comes with ABSOLUTELY NO WARRANTY. Licensed
under the terms of the GNU Lesser General Public License v3.0 (LGPL-3.0).

Enter phone number or bot token: *************
Is "*************" correct? (y/N): y
Traceback (most recent call last):
  File "c:\Users\Zard\Desktop\pyogram\pyogram.py", line 56, in <module>
    app.run()
  File "C:\Users\Zard\Desktop\pyogram\env\lib\site-packages\pyrogram\methods\utilities\run.py", line 84, in run
    self.start()
  File "C:\Users\Zard\Desktop\pyogram\env\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap  
    return loop.run_until_complete(coroutine)
  File "C:\Users\Zard\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Zard\Desktop\pyogram\env\lib\site-packages\pyrogram\methods\utilities\start.py", line 62, in start    await self.authorize()
  File "C:\Users\Zard\Desktop\pyogram\env\lib\site-packages\pyrogram\client.py", line 347, in authorize
    sent_code = await self.send_code(self.phone_number)
  File "C:\Users\Zard\Desktop\pyogram\env\lib\site-packages\pyrogram\methods\auth\send_code.py", line 79, in send_c    return types.SentCode._parse(r)
  File "C:\Users\Zard\Desktop\pyogram\env\lib\site-packages\pyrogram\types\authorization\sent_code.py", line 58, in _parse
    type=enums.SentCodeType(type(sent_code.type)),
  File "C:\Users\Zard\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Zard\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: <class 'pyrogram.raw.types.auth.sent_code_type_set_up_email_required.SentCodeTypeSetUpEmailRequired'> i
```

**Comment by Mahesh0253** [comment]
Update Pyrogram version then try again

**Comment by PouryaDe** [comment]
> Update Pyrogram version then try again

I did this, but it gives the same error
