### ISSUE TITLE
download_media not raised FloodWait error (duplicate)

### ISSUE THREAD

**Issue by keklick1337** [pyrogram/pyrogram#1192]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I created program to download all files from channel.
And some people who use my program may have this error before running my software. And I need to catch this error at download media.

### Steps to reproduce

1. try to parallel download 1000 files by any telegram client's (or any software)
2. got this error
3. try to download file by download_media
4. can't catch this exception

### Code example

```python
try:
    file = await app.download_media(msgobj, file_name=_filename, in_memory=False, progress=downloadCallback, progress_args=(_filename,))
except Exception as E:
    print(f'Exception raised {E}')
```

### Logs

```shell
Telegram says: [420 FLOOD_WAIT_X] - A wait of 1076 seconds is required (caused by "auth.ExportAuthorization")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/client.py", line 861, in get_file
    exported_auth = await self.invoke(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 1076 seconds is required (caused by "auth.ExportAuthorization")
```

**Comment by keklick1337** [comment]
duplicate issue https://github.com/pyrogram/pyrogram/issues/1191
but, nobody explain to me, how to catch this exception, because the account may have such an error even before my program is launched.
