### ISSUE TITLE
Loads tooo long. Why?

### ISSUE THREAD

**Issue by vega0** [pyrogram/pyrogram#1237]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

stucks on client.connect() / client.start()

### Steps to reproduce

1. Create the client
2. Run the client.connect()
3. Run the client.start()

### Code example

```python
import pyrogram
client = pyrogram.Client("my application", api_id=, api_hash="")
client.connect()
```

### Logs

```shell
>>> client.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1881, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 812, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
>>> client.get_contacts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\contacts\get_contacts.py", line 46, in get_contacts
    contacts = await self.invoke(raw.functions.contacts.GetContacts(hash=0))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 71, in invoke
    raise ConnectionError("Client has not been started yet")
ConnectionError: Client has not been started yet
>>> client.connect()
```

**Comment by delivrance** [comment]
The issue section on GitHub is for issues with the library. This is not an issue with the library, but rather an issue with your usage. If you want to ask Pyrogram related questions you can do so on [StackOverflow](https://stackoverflow.com/questions/ask?tags=pyrogram).
