### ISSUE TITLE
Unknow Error:406 SEND_CODE_UNAVAILABLE

### ISSUE THREAD

**Issue by PooyaRezaee** [pyrogram/pyrogram#1256]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I get error 406 SEND_CODE_UNAVAILABLE in resend code

### Steps to reproduce

I try method resend_code in pyrogram.Client object and get this error :

pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: Telegram says: [406 Not Acceptable] - [406 SEND_CODE_UNAVAILABLE] (caused by "auth.ResendCode")

and created log file with name unkown_errors.txt with this text in it:
2023-04-17 01:12:21.782343	[406 SEND_CODE_UNAVAILABLE]	auth.ResendCode

### Code example

```python
from pyrogram import Client

API_ID = 1234567
API_HASH = 'XXXXXXXXXXXXXXXXXXXXXX'
PHONE_NUMBER = '+98123456789'

client = Client('account',API_ID,API_HASH)
client.connect()
sent_code = client.send_code(PHONE_NUMBER)
HASH_CODE = sent_code.phone_code_hash

code = input('\nEnterCode\n  -Enter "resend" for send again Code\n >> ')

if code == 'resend':
    code_sent = client.resend_code(phone_number=PHONE_NUMBER,phone_code_hash=HASH_CODE)

    code = input('Enter Code : ')

# Operation SignIn
...

client.disconnect()
```

### Logs

```shell
Traceback (most recent call last):
  File "/.../main.py", line 16, in <module>
    code_sent = client.resend_code(phone_number=PHONE_NUMBER,phone_code_hash=HASH_CODE)
  File "/.../venv/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/.../venv/lib/python3.10/site-packages/pyrogram/methods/auth/resend_code.py", line 57, in resend_code
    r = await self.invoke(
  File "/.../venv/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/.../venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/.../venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/.../venv/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 80, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: Telegram says: [406 Not Acceptable] - [406 SEND_CODE_UNAVAILABLE] (caused by "auth.ResendCode")
```

**Comment by delivrance** [comment]
The error is self-explanatory: the server decided that the method invoked is not acceptable, with a reference to the unavailability of the functionality. This is not a client-side issue and there's nothing a client can do about such server decisions.
