### ISSUE TITLE
Error 400 - USER_IS_BOT

### ISSUE THREAD

**Issue by Gokujo** [pyrogram/pyrogram#1260]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I just followed this instruction https://docs.pyrogram.org/start/invoking and got an error 404

### Steps to reproduce

1. follow instructions on https://docs.pyrogram.org/start/invoking
2. start app

### Code example

```python
from pyrogram import Client, filters
from pyrogram.handlers import MessageHandler
from pyrogram.types import ReplyKeyboardMarkup, ReplyKeyboardRemove

from assets.variables import SETTINGS_FILE
from classes.Settings import Settings

config = Settings(SETTINGS_FILE)

app = Client("MyBot", api_id=config.api, api_hash=config.hash, bot_token=config.bot_token)


async def main():
    async with app:
        await app.send_message("me", "Hi!")


app.run(main())
```

### Logs

```shell
Connected to pydev debugger (build 231.8109.197)
/env/botPosterEnv310/bin/python /JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.8109.197/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 43531 --file /Python/projects/tgbot/main.py 
Traceback (most recent call last):
  File "/Python/projects/tgbot/main.py", line 22, in main
    await app.send_message("me", "Hi!")
  File "/env/botPosterEnv310/lib/python3.10/site-packages/pyrogram/methods/messages/send_message.py", line 126, in send_message
    r = await self.invoke(
  File "/env/botPosterEnv310/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/env/botPosterEnv310/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/env/botPosterEnv310/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/env/botPosterEnv310/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UserIsBot: Telegram says: [400 USER_IS_BOT] - A bot cannot send messages to other bots or to itself (caused by "messages.SendMessage")
python-BaseException

Process finished with exit code 1
```

**Comment by delivrance** [comment]
The special chat `"me"` refers to the running account, which is assumed to be a user-kind by the example, as opposed to a bot-kind. Simply change `"me"` to your username so that the bot can send a message to you instead of to itself (hence the error, which is self-explanatory).

**Comment by Gokujo** [comment]
Oh, thx. But that info is missing in the docs
