### ISSUE TITLE
request_callback_answer can't get the callback query

### ISSUE THREAD

**Issue by fivepe** [pyrogram/pyrogram#1270]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

```
botname = 'xxx'
app_user_id = "@yyyy"
base_cha = "@zzzz"

apps = [
    Client(botname),
    Client('hh')
]
app = apps[0]
app_user = apps[1]

@app.on_callback_query()
async def callback_query(client, callback_query):
    #print(callback_query)
    #msg = await app_user.get_messages(base_cha, int(callback_query.data.split('|')[0]), replies=0)
    print(callback_query.data)

    callback1 = await app_user.request_callback_answer(
        chat_id = base_cha,
        message_id = 420,
        callback_data = 'hot_adwords',
        timeout = 50
    )
    print(callback1)

compose(apps)
asyncio.run()
```

Simulate the user clicking the button, and the response information can be seen in the desktop client, but the request_ callback_ Answer did not obtain an answer, indicating that the time has expired

```
Request timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "souqun_bot.py", line 54, in callback_query
    await app_user.request_callback_answer(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/bots/request_callback_answer.py", line 69, in request_callback_answer
    return await self.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 402, in invoke
    raise e from None
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 351, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out
```

### Steps to reproduce

then i use  functions.messages.GetBotCallbackAnswer
```
@app.on_callback_query()
async def callback_query(client, callback_query):
    aaa = await app_user.invoke(
        functions.messages.GetBotCallbackAnswer(
            peer = await app_user.resolve_peer(-1001963371264),
            msg_id= int(callback_query.data.split('|')[0]),
            data = bytes("hot_adwords", "utf-8")
        )
    )
    print(aaa)
```

The desktop client can receive a response normally，but the demo run error，error information

```
Telegram says: [400 DATA_INVALID] - The encrypted data is invalid (caused by "messages.GetBotCallbackAnswer")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "souqun_bot.py", line 54, in callback_query
    aaa = await app_user.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.DataInvalid: Telegram says: [400 DATA_INVALID] - The encrypted data is invalid (caused by "messages.GetBotCallbackAnswer")
```

**Comment by delivrance** [comment]
This is not an issue and is also documented. See docs for `Client.request_callback_answer`.
