### ISSUE TITLE
FloodWait error by auth.ExportAuthorization 

### ISSUE THREAD

**Issue by fivepe** [pyrogram/pyrogram#1287]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I try to download more than 1000 files, and every time I download about 100 files, Waiting for 2856 seconds before continuing (required by "auth.ExportAuthorization") will appear. How to avoid this problem and how to deal with it.

### Steps to reproduce

Login into telegram account
try to download parallel more than 1000 files
There is Waiting for 2856 seconds before continuing (required by "auth.ExportAuthorization") prompt, how to avoid this problem

### Code example

```python
try:
    file = await app.download_media(msgobj, file_name=_filename))
except Exception as E:
    print(f'Exception raised {E}')
```

### Logs

```shell
Telegram says: [420 FLOOD_WAIT_X] - A wait of 1076 seconds is required (caused by "auth.ExportAuthorization")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/client.py", line 861, in get_file
    exported_auth = await self.invoke(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 1076 seconds is required (caused by "auth.ExportAuthorization")
```

**Comment by gr0esch** [comment]
I just run in the same problem…

`Telegram says: [420 FLOOD_WAIT_X] - A wait of 142 seconds is required (caused by "auth.ExportAuthorization")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 880, in get_file
    dc_id=dc_id
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/advanced/invoke.py", line 83, in invoke
    else self.sleep_threshold)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/errors/rpc_error.py", line 97, in raise_it
    is_signed=is_signed)
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 142 seconds is required (caused by "auth.ExportAuthorization")`

**Comment by delivrance** [comment]
This is not a library issue, it's the server telling you to slow down and there's nothing that needs to be fixed.

**Comment by gr0esch** [comment]
> 

Interestingly for me when I get these messages and let the for loop continue, some downloads are still successful. I would say 2/3 are okay and with 1/3 I get the error.

How would you suggest to wait in term of rate limits? Is there a way to let pyrogram automatically wait for the rate limit?

**Comment by delivrance** [comment]
There's no general suggestion on rate limits because, as the link in the FAQ tells too, they are unknown and can change anytime at the server discretion. The FAQ also shows you how to handle such exceptions and that's what you can resort to, besides slowing down things in the first place.

**Comment by gr0esch** [comment]
Thanks @delivrance for the info. I've been trying to implement this for days now but I keep failing. It seems to me that the FloodWait Error is not being caught?

I keep getting errors like these
`Telegram says: [420 FLOOD_WAIT_X] - A wait of 1219 seconds is required (caused by "auth.ExportAuthorization")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 880, in get_file
    dc_id=dc_id
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/advanced/invoke.py", line 83, in invoke
    else self.sleep_threshold)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/errors/rpc_error.py", line 97, in raise_it
    is_signed=is_signed)
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 1219 seconds is required (caused by "auth.ExportAuthorization")`

… although I am actually catching these and trying to wait, as it is shown in the link mentioned in my earlier comment…

`try:
                            downloaded_file = await app.download_media(new_message.photo, file_name=new_file_path, progress=progress)
                        except FloodWait as e:
                            print("Now waiting seconds", e.value)
                            await asyncio.sleep(e.value)  # Wait "value" seconds before continuing`

This is really odd to me?

**Comment by ChuckNorrison** [comment]
I would suggest to reopen this issue, its happening on my code too, even i did the try except Floodwait catch. It was not possible for me to catch the exception and wait the amount of seconds from error message.

**Comment by gr0esch** [comment]
It seems that we have a fix for this awaiting to be accepted into the main branch with #1348 :)
