### ISSUE TITLE
get_chat_member problem when user_id is Unique identifier (int)

### ISSUE THREAD

**Issue by milaad10** [pyrogram/pyrogram#1296]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

get_chat_member(chat_id, user_id) works fine when user_id is username (str) But
when user_id is Unique identifier (int), it doesn't work :(
Please check logs

### Steps to reproduce

1. 

### Code example

```python
async def checkMember(user):
  member = await bot.get_chat_member(channel_chat_id, user)
  if member.status == ChatMemberStatus.MEMBER:
    return True
  else:
    return False

await checkMember(user_id) # doesn't work
await checkMember(username) # works fine
```

### Logs

```shell
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:pyrogram.dispatcher:Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 45....325'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 123, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 45....325'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "<ipython-input-2-21c8b3752acd>", line 33, in start
    if await checkMember(user_id):
  File "<ipython-input-2-21c8b3752acd>", line 23, in checkMember
    member = await bot.get_chat_member(channel_chat_id, user)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/chats/get_chat_member.py", line 56, in get_chat_member
    user = await self.resolve_peer(user_id)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 125, in resolve_peer
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
```

**Comment by tangyoha** [comment]
add -100 at first

**Comment by tangyoha** [comment]
Now go to the chat/channel and you will see the URL as something like

https://web.telegram.org/?legacy=1#/im?p=u853521067_2449618633394 here 853521067 is the chat id.
https://web.telegram.org/?legacy=1#/im?p=@somename here somename is the chat id.
https://web.telegram.org/?legacy=1#/im?p=s1301254321_6925449697188775560 here take 1301254321 and add -100 to the start of the id => -1001301254321.
https://web.telegram.org/?legacy=1#/im?p=c1301254321_6925449697188775560 here take 1301254321 and add -100 to the start of the id => -1001301254321

**Comment by milaad10** [comment]
> add -100 at first

> Now go to the chat/channel and you will see the URL as something like
> 
> https://web.telegram.org/?legacy=1#/im?p=u853521067_2449618633394 here 853521067 is the chat id. https://web.telegram.org/?legacy=1#/im?p=@somename here somename is the chat id. https://web.telegram.org/?legacy=1#/im?p=s1301254321_6925449697188775560 here take 1301254321 and add -100 to the start of the id => -1001301254321. https://web.telegram.org/?legacy=1#/im?p=c1301254321_6925449697188775560 here take 1301254321 and add -100 to the start of the id => -1001301254321

Thank you. I know that about channel id (starts with -100)
In logs  'ID not found: 45....325'  is User id I changed it to post here
when i change just user id to username it works fine.

As long as no communication or message is exchanged between the user and the bot, it is not possible to check with the User Id. After starting the bot with the user, the problem was solved. But the interesting thing is that this is not true when checking with Username
