### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by SAMIRKL** [pyrogram/pyrogram#1309]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Every Where i want use (Phone_Number) it give me a error

### Steps to reproduce

KeyError: 'Phone number not found: 9******'

### Code example

```python
await app.add_contact("+******", "1")
```

### Logs

```shell
KeyError: 'Phone number not found: 9******'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AraLap\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "c:\Users\AraLap\Desktop\PARVAZ BOLOURIN\Adder bot\telegram.py", line 24, in s
    await APP.add_contact("+989123048400", "1")
  File "C:\Users\AraLap\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\contacts\add_contact.py", line 70, in add_contact
    id=await self.resolve_peer(user_id),
  File "C:\Users\AraLap\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 87, in resolve_peer       
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
```

**Comment by Antipire** [comment]
Make sure you are using this method not for bot. This method usable only by users and not by bots . For detail information visit and reread docs: https://docs.pyrogram.org/api/methods/add_contact
