### ISSUE TITLE
PEER_ID_INVALID when send_message to a private group with admin rights

### ISSUE THREAD

**Issue by SyberiaK** [pyrogram/pyrogram#1314]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When my bot gets message, callback data or inline query, it tries to log it into specific private group.
```python
async def log(client: Client, message: Message):
    """The bot sends log to log channel"""

    text = (
        f"✍️ User: <a href=\"tg://user?id={message.from_user.id}\">{message.from_user.first_name}</a>\n"
        f"ID: {message.from_user.id}\n"
        f"Language: {message.from_user.language_code}\n"
        f"Private message: {message.text}"
    )
    await client.send_message(config.LOGCHANNEL, text, disable_notification=True)

@app.on_message()
async def sync_user_data(client: Client, message: Message):
    await log(client, message)
```

Before this date, it did that properly without any error.
However, once I tried to run the bot from another script (to send messages on function call), stopped it and ran this one, the bot started to throw `PeerIdInvalid`:

```python
13:41:50 — 26/07/2023 | pyrogram.dispatcher: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it 
Traceback (most recent call last):
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 142, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -914613674'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 85, in resolve_peer
    return await self.storage.get_peer_by_phone_number(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 168, in get_peer_by_phone_number
    raise KeyError(f"Phone number not found: {phone_number}")
KeyError: 'Phone number not found: -914613674'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyropatch\listen\callback.py", line 155, in resolve_listener
    await self.user_callback(client, update, *args)
  File "C:\Users\guard\Desktop\vscode projects\botty\main.py", line 95, in sync_user_data_callback
    await log_callback(client, callback_query)
  File "C:\Users\guard\Desktop\vscode projects\botty\functions\logs.py", line 31, in log_callback
    await client.send_message(config.LOGCHANNEL, text, disable_notification=True)
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\methods\messages\send_message.py", line 128, in send_message
    peer=await self.resolve_peer(chat_id),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyropatch\flood_handler\flood_handler.py", line 20, in resolve_peer
    return await self.old_resolve_peer(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guard\Desktop\vscode projects\botty\.venv\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 87, in resolve_peer
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
```
When i comment `await log(client, message)`, the bot works properly.
Even if I use any bot commands in this group (and bot responds to them) or mention the bot or use inline queries or kick and add bot back to the group or promote bot to admin, it still throws `PeerIdInvalid`.
Deleting .session file doesn't help either.
I checked through `https://api.telegram.org/bot[token]/getUpdates` and it seems like bot does get my messages and group id is  valid but it still can't find the peer.

### Steps to reproduce

Sadly, I have no idea where that came from but the main suspect is another script that maybe broke something while I tried to run the bot in it.

**Comment by SyberiaK** [comment]
Interesting thing: if I use `client.get_chat([chat_id])` - it shows me proper group info, but if bot tries to send message by `client.get_chat([chat_id]).id` - it still throws `PeerIdInvalid`:
```python
{
    "_": "Chat",
    "id": -914613674,
    "type": "ChatType.GROUP",
    "is_creator": false,
    "title": "[REDACTED] logs",
    "has_protected_content": false,
    "members_count": 0,
    "available_reactions": {
        "_": "ChatReactions",
        "all_are_enabled": true,
        "allow_custom_emoji": true
    }
}
14:49:11 — 26/07/2023 | pyrogram.dispatcher: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it (caused by "messages.SendMessage")

```

**Comment by SyberiaK** [comment]
And for some reason when I use `client.get_chat(message.chat.id)`, it shows me different chat id and type for the same group:
```python
{
    "_": "Chat",
    "id": -1001923718915,
    "type": "ChatType.SUPERGROUP",
    "is_verified": false,
    "is_restricted": false,
    "is_creator": false,
    "is_scam": false,
    "is_fake": false,
    "title": "[REDACTED] logs",
    "has_protected_content": false,
    "can_set_sticker_set": false,
    "members_count": 2,
    "permissions": {
        "_": "ChatPermissions",
        "can_send_messages": true,
        "can_send_media_messages": true,
        "can_send_other_messages": true,
        "can_send_polls": true,
        "can_add_web_page_previews": true,
        "can_change_info": true,
        "can_invite_users": true,
        "can_pin_messages": true
    },
    "available_reactions": {
        "_": "ChatReactions",
        "all_are_enabled": true,
        "allow_custom_emoji": true
    }
}
```
When I replaced old ID with this one - it works like a charm.
Any ideas what's going on?

**Comment by CSR-SOFTWARES** [comment]
its actually a bug over Tg , it happens at formation of new group but also within some minutes its gives us actual group id starting with "-100"

**Comment by devenu85** [comment]
same issue with newly created channel..

I fixed it by just sending a message in the channel.

**Comment by yashafromrussia** [comment]
Was having the same issue... I ended up just using super group instead:

```python
group = await app.create_supergroup(title)
await app.add_chat_members(group.id, user_ids=users)
```

instead of
```python
group = await app.create_group(title, users=users)
```

**Comment by AndrewFucher** [comment]
I think issue described by @SyberiaK lies within method 
```
MIN_CHANNEL_ID = -1002147483647
MAX_CHANNEL_ID = -1000000000000
MIN_CHAT_ID = -2147483647
MAX_USER_ID_OLD = 2147483647
MAX_USER_ID = 999999999999
# some other code
def get_peer_type(peer_id: int) -> str:
    if peer_id < 0:
        if MIN_CHAT_ID <= peer_id:
            return "chat"

        if MIN_CHANNEL_ID <= peer_id < MAX_CHANNEL_ID:
            return "channel"
    elif 0 < peer_id <= MAX_USER_ID:
        return "user"

    raise ValueError(f"Peer id invalid: {peer_id}")
```

As u can see we will get peer type "chat" only when it's id is greater than MIN_CHAT_ID which does not really correspond to logic stated in [documentation](https://docs.pyrogram.org/topics/advanced-usage#chat-ids). I believe it is supposed to be calculated a bit different. Also, according to [telegram API](https://core.telegram.org/bots/api#chat) id's can have up to 52 significant bits, so those constant values are actually really wrong.

For now I believe monkey patch can be used e.g.:
```
def get_peer_type(peer_id: int) -> str:
    peer_id_str = str(peer_id)
    if not peer_id_str.startswith("-"):
        return "user"
    elif peer_id_str.startswith("-100"):
        return "channel"
    else:
        return "chat"
```

**Comment by efinskiy** [comment]
> I think issue described by @SyberiaK lies within method
> 
> ```python
> MIN_CHANNEL_ID = -1002147483647
> MAX_CHANNEL_ID = -1000000000000
> MIN_CHAT_ID = -2147483647
> MAX_USER_ID_OLD = 2147483647
> MAX_USER_ID = 999999999999
> # some other code
> def get_peer_type(peer_id: int) -> str:
>     if peer_id < 0:
>         if MIN_CHAT_ID <= peer_id:
>             return "chat"
> 
>         if MIN_CHANNEL_ID <= peer_id < MAX_CHANNEL_ID:
>             return "channel"
>     elif 0 < peer_id <= MAX_USER_ID:
>         return "user"
> 
>     raise ValueError(f"Peer id invalid: {peer_id}")
> ```
> 
> As u can see we will get peer type "chat" only when it's id is greater than MIN_CHAT_ID which does not really correspond to logic stated in [documentation](https://docs.pyrogram.org/topics/advanced-usage#chat-ids). I believe it is supposed to be calculated a bit different. Also, according to [telegram API](https://core.telegram.org/bots/api#chat) id's can have up to 52 significant bits, so those constant values are actually really wrong.
> 
> For now I believe monkey patch can be used e.g.:
> 
> ```python
> def get_peer_type(peer_id: int) -> str:
>     peer_id_str = str(peer_id)
>     if not peer_id_str.startswith("-"):
>         return "user"
>     elif peer_id_str.startswith("-100"):
>         return "channel"
>     else:
>         return "chat"
> ```

Thank you very much! The Monkey patching pyrogram really helped.

**Comment by eddyli1989** [comment]
for those don't want to change system function ,use this in your code

```
from pyrogram import utils

def get_peer_type_new(peer_id: int) -> str:
    peer_id_str = str(peer_id)
    if not peer_id_str.startswith("-"):
        return "user"
    elif peer_id_str.startswith("-100"):
        return "channel"
    else:
        return "chat"

utils.get_peer_type = get_peer_type_new

// your other code
```

this will fix this error

**Comment by AndryMaster** [comment]
> for those don't want to change system file,use this in your code
> 
> ```
> from pyrogram import utils
> ...
> utils.get_peer_type = get_peer_type_new
> ```
> 
> // your other code
> this will fix this error

Thank you very much it works!

**Comment by mithun-ctrl** [comment]
Guys use pyrofork instead of Pyrogram, it helped me
