### ISSUE TITLE
download_media does not raise an exception

### ISSUE THREAD

**Issue by Pabloader** [pyrogram/pyrogram#132]
```
try:
    path = app.download_media(file_id, tempdir + '/')
except FloodWait as e:
    time.sleep(e.x)
```
If download_media receives an error (FloodWait in my case) - no exception raised. 
Execution continues as normal, but path is None and FloodWait message prints in stdout

**Comment by delivrance** [comment]
@Pabloader Hi, do you have any full traceback of the error I can view?

**Comment by Pabloader** [comment]
```
[420 FLOOD_WAIT_X]: A wait of 377 seconds is required
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 1211, in get_file
    limit=limit
  File "/home/user/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 420, in send
    return self._send(data, timeout=timeout)
  File "/home/user/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 407, in _send
    Error.raise_it(result, type(data))
  File "/home/user/.local/lib/python3.5/site-packages/pyrogram/api/errors/error.py", line 71, in raise_it
    )(x=x)
pyrogram.api.errors.exceptions.flood_420.FloodWait: [420 FLOOD_WAIT_X]: A wait of 377 seconds is required
```

**Comment by delivrance** [comment]
@Pabloader As I thought. It is really really hard to hit flood waits while downloading files, but this very FloodWait error is of a weird kind because it happens for unavailable files only. They are easy to spot because you get random timeouts of some hundreds seconds.

There's pretty much nothing we can do client side, is server's fault and your only option is to ignore for now (we can at most show a nicer error).

If you forward that message to yourself you'll see that official clients (e.g.: tdesktop) will display an error too.

**Comment by Pabloader** [comment]
@delivrance This is not issue I speak about. 
I expect FloodWait, it's ok, but I cannot catch it. 
Function `download_media` just prints stacktrace and returns None. 
I'll check if I can download next file from same chat without FloodWait, thank you.

**Comment by delivrance** [comment]
@Pabloader I get what you mean, but ([as docs also state](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.download_media)) the only way to tell if something went wrong after the download has started is to check what the method returns, which is None in case of an error.

Not very pythonic probably, but in the current implementation the message is enqueued and the actual download is made by another worker thread.

Anyway, you are surely able to download the next (non-broken) files from the same chat. As I said, you encountered a "fake" flood wait; the server is not telling you to slow down, rather that there's a problem getting that specific file, telegram-wide (nobody will be able to download it).

**Comment by schw4rzlicht** [comment]
Stuck with the same issue here. What's the difference to `ValueError` then? In my understanding `ValueError` is raised when no media exists for download.

**Comment by morethancoder** [comment]
Clearly the `download_media()` function has issues, i was stuck with this problem for 3 days and i have messed up my code adding delays and sleeping between requests to not get flood error, turns out its a bug from telegram servers, it tells you flood error but in reality its just the download_media function doesnt work properly, i solved the problem by replacing the `download_media()` function with manually requesting the file from telegram servers by using file_id and bot_token and the telegrm.org url.

``` photo_message = client.get_messages(chat_id, int(requested_photo_message_id))
    if photo_message.photo:
        url = f"https://api.telegram.org/bot{client.bot_token}/getFile?file_id={photo_message.photo.file_id}"
    elif photo_message.document:
        url = f"https://api.telegram.org/bot{client.bot_token}/getFile?file_id={photo_message.document.file_id}"
    sleep(1)
    response = requests.get(url).json()
    file_path = response['result']['file_path']

    # Build the download URL
    download_url = f'https://api.telegram.org/file/bot{client.bot_token}/{file_path}'
    sleep(1)
    image_binary = requests.get(download_url).content
```

### I hope you find my comment useful :) 

#### follow me for more on telegram bots as i work with telegram bot api a lot :100:

**Comment by porridgexj** [comment]
I think it is a bug from pyrogram, so I find another way to solve this, when show a FloodWait error, the file downloaded size usually is 0KB, so we can test whether the file size is 0KB.

```python
def is_file_empty(file_path):
    if os.path.exists(file_path):
        return os.path.getsize(file_path) == 0
    else:
        return True

flag = true
while flag:
    path = app.download_media(file_id)
    if file_path and not is_file_empty(file_path):  
        flag = false
        # solve success situation
    else:
        time.sleep(10)
        # sleep for 10 seconds and retry
```
