### ISSUE TITLE
get_dialogs errors if there is one channel/supergroup that is not accessible

### ISSUE THREAD

**Issue by hugonzb** [pyrogram/pyrogram#1332]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I have tested this extensively and can confirm that the issue is coming from get_dialogs() and not my code. It looks like if a user is banned from a group, it picks that up as a dialog still and then it fails when trying to get messages?

Can something be added (such as an exception), so that if this happens, it won't completely break get_dialogs() and all other dialogs are returned successfully?

### Steps to reproduce

User is banned in a group, or the group itself has been deleted. The returned message is "Channel/supergroup is not accessible" which is ambiguous/.

### Code example

```python
async for dialog in client.get_dialogs(200):
     print("Works")


# Tried iterating through get_dialogs() without doing anything with the dialog object, and it still fails. Sometimes it works (if I reduce the dialogs returned to a smaller number and it doesn't get the problem dialog by chance).
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\X\X\X\X\X.py", line 249, in <module>
    asyncio.run(func)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\X\Documents\X\X\X.py", line 171, in main
    async for dialog in client.get_dialogs(200):
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\chats\get_dialogs.py", line 79, in get_dialogs
    messages[chat_id] = await types.Message._parse(self, message, users, chats)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\types\messages_and_media\message.py", line 836, in _parse
    reply_to_message = await client.get_messages(
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\messages\get_messages.py", line 115, in get_messages
    r = await self.invoke(rpc, sleep_threshold=-1)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.ChannelPrivate: Telegram says: [406 CHANNEL_PRIVATE] - The channel/supergroup is not accessible (caused by "channels.GetMessages")
```

**Comment by hugonzb** [comment]
I tested this even further - it is really weird.

It seems to return exactly 101 dialogs completely fine e.g.
async for dialog in client.get_dialogs(101):

but it fails as soon as I change it to:
async for dialog in client.get_dialogs(102):

This points to not being a specific group/channel, but something else. Is Telegram potentially limiting the particular user by only allowing it to fetch 101 dialogs?! The 102nd being non-accessible..

**Comment by hugonzb** [comment]
Also tested with other users and they have no limit. It is just this user (recently). Some weird Telegram shadow ban?
