### ISSUE TITLE
BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by PalashMudi** [pyrogram/pyrogram#1347]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

2023-10-02T05:17:28.266812+00:00 heroku[worker.1]: State changed from crashed to starting
2023-10-02T05:17:31.769839+00:00 heroku[worker.1]: Starting process with command `python3 bot.py`
2023-10-02T05:17:32.339762+00:00 heroku[worker.1]: State changed from starting to up
2023-10-02T05:17:33.896266+00:00 app[worker.1]: Traceback (most recent call last):
2023-10-02T05:17:33.896295+00:00 app[worker.1]:   File "/app/bot.py", line 33, in <module>
2023-10-02T05:17:33.896351+00:00 app[worker.1]:     app.start()
2023-10-02T05:17:33.896360+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
2023-10-02T05:17:33.896405+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2023-10-02T05:17:33.896406+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-10-02T05:17:33.896506+00:00 app[worker.1]:     return future.result()
2023-10-02T05:17:33.896507+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
2023-10-02T05:17:33.896544+00:00 app[worker.1]:     is_authorized = await self.connect()
2023-10-02T05:17:33.896545+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect
2023-10-02T05:17:33.896579+00:00 app[worker.1]:     await self.session.start()
2023-10-02T05:17:33.896580+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 142, in start
2023-10-02T05:17:33.896633+00:00 app[worker.1]:     raise e
2023-10-02T05:17:33.896633+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 109, in start
2023-10-02T05:17:33.896671+00:00 app[worker.1]:     await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
2023-10-02T05:17:33.896672+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 333, in send
2023-10-02T05:17:33.896730+00:00 app[worker.1]:     raise BadMsgNotification(result.error_code)
2023-10-02T05:17:33.896746+00:00 app[worker.1]: pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.
2023-10-02T05:17:34.592533+00:00 heroku[worker.1]: Process exited with status 1
2023-10-02T05:17:34.614877+00:00 heroku[worker.1]: State changed from up to crashed

### Steps to reproduce

repo : https://github.com/PalashMudi/Premium-Rename-Bot.

### Logs

```shell
2023-10-02T05:17:28.266812+00:00 heroku[worker.1]: State changed from crashed to starting
2023-10-02T05:17:31.769839+00:00 heroku[worker.1]: Starting process with command `python3 bot.py`
2023-10-02T05:17:32.339762+00:00 heroku[worker.1]: State changed from starting to up
2023-10-02T05:17:33.896266+00:00 app[worker.1]: Traceback (most recent call last):
2023-10-02T05:17:33.896295+00:00 app[worker.1]:   File "/app/bot.py", line 33, in <module>
2023-10-02T05:17:33.896351+00:00 app[worker.1]:     app.start()
2023-10-02T05:17:33.896360+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
2023-10-02T05:17:33.896405+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2023-10-02T05:17:33.896406+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-10-02T05:17:33.896506+00:00 app[worker.1]:     return future.result()
2023-10-02T05:17:33.896507+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
2023-10-02T05:17:33.896544+00:00 app[worker.1]:     is_authorized = await self.connect()
2023-10-02T05:17:33.896545+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect
2023-10-02T05:17:33.896579+00:00 app[worker.1]:     await self.session.start()
2023-10-02T05:17:33.896580+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 142, in start
2023-10-02T05:17:33.896633+00:00 app[worker.1]:     raise e
2023-10-02T05:17:33.896633+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 109, in start
2023-10-02T05:17:33.896671+00:00 app[worker.1]:     await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
2023-10-02T05:17:33.896672+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 333, in send
2023-10-02T05:17:33.896730+00:00 app[worker.1]:     raise BadMsgNotification(result.error_code)
2023-10-02T05:17:33.896746+00:00 app[worker.1]: pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.
2023-10-02T05:17:34.592533+00:00 heroku[worker.1]: Process exited with status 1
2023-10-02T05:17:34.614877+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by KurimuzonAkuma** [comment]
Why you opened this issue? Sync your time 🤨🤨🤨

**Comment by PalashMudi** [comment]
> Why you opened this issue? Sync your time 🤨🤨🤨

after sync time not resolved.

**Comment by KurimuzonAkuma** [comment]
> > Why you opened this issue? Sync your time 🤨🤨🤨
> 
> after sync time not resolved.

How you sync time?

**Comment by PalashMudi** [comment]
> > > > Why you opened this issue? Sync your time 🤨🤨🤨
> > > 
> > > 
> > > after sync time not resolved.
> > 
> > 
> > How you sync time?

through win+R... >
timedate.cpl >
Internet time >
time.windows.com >
synchronize

**Comment by Danstiv** [comment]
> time.windows.com >
> synchronize

Are you sure the synchronization is working?
Try checking here: https://www.ntp-servers.net/
Sorry, it seems this resource is only in Russian, but I did not find a similar service in English.

**Comment by Danstiv** [comment]
and...
As I see from the logs, you are running your bot on the Heroku platform, in which case you should make sure that the time is set correctly on that server.
Unfortunately, I can’t quickly come up with a way to check the correctness of the time, because, as far as I know, you cannot connect there via ssh or gain full access in any other way.
Alternatively, you can write a small web server to which you can send a timestamp from a machine on which the time is set correctly, log the timestamp in your endpoint, and then compare them; a difference of 2-3 seconds should not be critical.

**Comment by PalashMudi** [comment]
> and... As I see from the logs, you are running your bot on the Heroku platform, in which case you should make sure that the time is set correctly on that server. Unfortunately, I can’t quickly come up with a way to check the correctness of the time, because, as far as I know, you cannot connect there via ssh or gain full access in any other way. Alternatively, you can write a small web server to which you can send a timestamp from a machine on which the time is set correctly, log the timestamp in your endpoint, and then compare them; a difference of 2-3 seconds should not be critical.

solved by updating python and required library. but now came another errror...

pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: Telegram says: [406 AUTH_KEY_DUPLICATED] - The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")

**Comment by KurimuzonAkuma** [comment]
> > and... As I see from the logs, you are running your bot on the Heroku platform, in which case you should make sure that the time is set correctly on that server. Unfortunately, I can’t quickly come up with a way to check the correctness of the time, because, as far as I know, you cannot connect there via ssh or gain full access in any other way. Alternatively, you can write a small web server to which you can send a timestamp from a machine on which the time is set correctly, log the timestamp in your endpoint, and then compare them; a difference of 2-3 seconds should not be critical.
> 
> solved by updating python and required library. but now came another errror...
> 
> pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: Telegram says: [406 AUTH_KEY_DUPLICATED] - The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")

Everything is written in the error. Read more than the first two words

**Comment by i701** [comment]
Upgrade to Pyrogram [latest](https://pypi.org/project/Pyrogram/) version. It should fix the issue. Install version 2.0.106

The releases page in github is not updated.

**Comment by purnima200** [comment]
Just run this in your terminal to know exact time and date $ date ; date +"%FORMAT" ; var=$(date) ; var=`date` ; echo "$var";

**Comment by aaron0713** [comment]
Upgrade to 2.0.106

**Comment by DeArchX** [comment]
![image](https://github.com/pyrogram/pyrogram/assets/145952424/64e4b910-1329-4797-ae40-928a76bbd215)
same error, and my time is synchronized too

**Comment by mdmeds123** [comment]
after changed the pyrogram 1.xxx version to 2.xxx in requirements.txt, I have no more issues. thx a lot guys😁

**Comment by HiddenLights** [comment]
Is there a way of still using the pyrogram version 1.4.16 and fix this "error [16]"?

**Comment by ZhymabekRoman** [comment]
> Is there a way of still using the pyrogram version 1.4.16 and fix this "error [16]"?

Upgrade your Pyrogram

**Comment by Helias** [comment]
as I wrote [here](https://stackoverflow.com/questions/77726848/pyrogram-telegram-server-synchronization-error/78022812#78022812) I've solved upgrading pyrogram. I got this issue after 25 December 2023

**Comment by CodeOfDestruction** [comment]
Is there a way of still using the pyrogram version 1.4.16 and fix this "error [16]"?

**Comment by okineadev** [comment]
I don't know how, but synchronizing the time with NTP helped me.

Here is the command that synchronizes the time:

```bash
sudo ntpdate -u <ntp_server>
```

Instead of `<ntp_server>` insert the address of your NTP server.

Personally I used `0.ua.pool.ntp.org` (See https://www.ntppool.org/uk/zone/ua)

**Comment by LuchKan-Git-Hub** [comment]
probaly time is not correct try solve it in settings
