### ISSUE TITLE
When kick new joined user, error 400 PEER_ID_INVALID

### ISSUE THREAD

**Issue by E8N2D24H** [pyrogram/pyrogram#135]
A supergroup
user-bot

Not every joined user will produce this error, but some of them will, i just don't know why

Code:

```
for n in message.new_chat_members:
    user_id = n.id
    try:
        client.kick_chat_member(message.chat.id, user_id)
    except Exception as e:
        logging.warning('Kick user error: %s', e)
```

error I got:

`Kick user error: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid`

I want to figure out why this happened, and how can i handle it

**Comment by delivrance** [comment]
@E8N2D24H Hi, I need the **full** traceback error, otherwise I can't know what's going on.

Meanwhile, if you find it easy to replicate the issue you could try invoking `kick_chat_member` once again after, say, 5 seconds of sleep when PEER_ID_INVALID arises and report back what happens.

**Comment by E8N2D24H** [comment]
Thank you for your reply!
Today, I used two accounts to join my group, one was successfully banned, the other was not, and the full log shows error:

```
2018-10-13 10:22:26,180 - __main__ - ERROR - Kick user error: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1053, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: 574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1056, in resolve_peer
    return self.peers_by_id[-peer_id]
KeyError: -574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1059, in resolve_peer
    return self.peers_by_id[int("-100" + str(peer_id))]
KeyError: -100574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot/FakeBot/fakebot.py", line 1000, in new_nick
    client.kick_chat_member(gid, uid)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/methods/chats/kick_chat_member.py", line 58, in kick_chat_member
    user_peer = self.resolve_peer(user_id)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1061, in resolve_peer
    raise PeerIdInvalid
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
```

**after 5 seconds the user bot tried kicking again:**

```
2018-10-13 10:22:31,185 - __main__ - ERROR - Kick user error: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1053, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: 574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1056, in resolve_peer
    return self.peers_by_id[-peer_id]
KeyError: -574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1059, in resolve_peer
    return self.peers_by_id[int("-100" + str(peer_id))]
KeyError: -100574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot/FakeBot/fakebot.py", line 1673, in kick_again
    client.kick_chat_member(gid, uid)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/methods/chats/kick_chat_member.py", line 58, in kick_chat_member
    user_peer = self.resolve_peer(user_id)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1061, in resolve_peer
    raise PeerIdInvalid
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
```

**after 10 seconds the user bot tried kicking again:**

```
2018-10-13 10:22:41,185 - __main__ - ERROR - Kick user error: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1053, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: 574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1056, in resolve_peer
    return self.peers_by_id[-peer_id]
KeyError: -574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1059, in resolve_peer
    return self.peers_by_id[int("-100" + str(peer_id))]
KeyError: -100574035934

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot/FakeBot/fakebot.py", line 1673, in kick_again
    client.kick_chat_member(gid, uid)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/methods/chats/kick_chat_member.py", line 58, in kick_chat_member
    user_peer = self.resolve_peer(user_id)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 1061, in resolve_peer
    raise PeerIdInvalid
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid
```

**Comment by delivrance** [comment]
@E8N2D24H Any info on how to test this *exactly*? I'm trying in a test group with a clean session, but I'm unable to reproduce the issue. I tried inviting one as well as multiple users (bots) at once (up to 4). Everything works as intended and the new members are instantly banned.

```python
CHAT_ID = -100123456789


@app.on_message(Filters.chat(CHAT_ID) & Filters.new_chat_members)
def _(c, m):
    for i in m.new_chat_members:
        c.kick_chat_member(CHAT_ID, i.id)
```

What you can do now is sending me a full debug logging file, which will be generated automatically once you add these lines at the top of your main script:

```python
import logging

LOG_FORMAT = "[%(asctime)s.%(msecs)03d] %(filename)s:%(lineno)s %(levelname)s: %(message)s"

logging.basicConfig(
    filename="issue135.txt",
    level=logging.DEBUG,
    format=LOG_FORMAT
)
```

The logging file will be named `issue135.txt` and could be huge in size, so it would be better to try replicate the issue within a short run.

**Some things to note:**

- The logging file won't truncate automatically, so, if you restart your client multiple times, the same file will contain debug lines from the previous runs. You might delete the file completely if you didn't manage to replicate the issue within a short period of time to prevent it growing too much.

- The `debug` level will log **everything**, and this includes your personal information such as phone number, dialogs and contacts.

Regarding the last point, it's unfeasible to try hiding personal info in a huge logging file, but that's the only way left for me to find what's the issue (since I'm not able to reproduce the issue myself). If you prefer, you can send the file to me [privately](//t.me/haskell) once you have it, but if you are not comfortable with all of this your only option would be to ignore the error as I have no clue what is going on.

To ignore the error you can simply do:

```python
from pyrogram.api import errors

try:
    ...
except errors.PeerIdInvalid:
    pass
```

**Comment by E8N2D24H** [comment]
OK, I got the log, and I tested, reproduced the same error, I will send it to you privately, thanks for you help!
