### ISSUE TITLE
Cannot decode photo file_id

### ISSUE THREAD

**Issue by DataReset** [pyrogram/pyrogram#1363]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I'm receiving photo file_id with bot api(aiogram) and trying to send it with pyrogram, but i get an error

### Steps to reproduce

1. Receive a file id with bot api
2. Pass to send_photo pyrogram method
3. Get an error

### Logs

```shell
[2023-11-11 11:31:26,165] [WARNING] Traceback (most recent call last):
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\file_id.py", line 253, in decode
    thumbnail_source = ThumbnailSource(thumbnail_source)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 109 is not a valid ThumbnailSource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\utils.py", line 49, in get_input_media_from_file_id
    decoded = FileId.decode(file_id)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\file_id.py", line 255, in decode
    raise ValueError(f"Unknown thumbnail_source {thumbnail_source} of file_id {file_id}")
ValueError: Unknown thumbnail_source 109 of file_id AgACAgIAAxkBAAIFl2VPOPk8nUNWtN47f4z2zswf0NI5AAJS0TEb4EB5Sn6G2--e8rXWAQADAgADbQADMwQ

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\backup\spam2.0\main.py", line 186, in spam
    await client.send_photo(chat['id'], photo=message['photo'], caption=message['text'] if 'text' in message else None, caption_entities=message['entities'] if 'entities' in message else None, reply_markup=message['reply_markup'] if 'reply_markup' in message else None)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\messages\send_photo.py", line 166, in send_photo
    media = utils.get_input_media_from_file_id(photo, FileType.PHOTO, ttl_seconds=ttl_seconds)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\utils.py", line 51, in get_input_media_from_file_id
    raise ValueError(
ValueError: Failed to decode "AgACAgIAAxkBAAIFl2VPOPk8nUNWtN47f4z2zswf0NI5AAJS0TEb4EB5Sn6G2--e8rXWAQADAgADbQADMwQ". The value does not represent an existing local file, HTTP URL, or valid file id.
```

**Comment by sb0y** [comment]
I have similar issue

```
warp_beacon  | 2024-08-06 21:57:15,363 - root - ERROR - Failed to decode "AgACAgIAAxkDAAJL_2aiM6Qr5p_MuoCRtXRJQu3-WOH2AALF3jEbJbgRSeo7xOa1QPekAQADAgADeQADNQQ". The value does not represent an existing local file, HTTP URL, or valid file id.
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/file_id.py", line 253, in decode
warp_beacon  |     thumbnail_source = ThumbnailSource(thumbnail_source)
warp_beacon  |   File "/usr/lib/python3.10/enum.py", line 385, in __call__
warp_beacon  |     return cls.__new__(cls, value)
warp_beacon  |   File "/usr/lib/python3.10/enum.py", line 710, in __new__
warp_beacon  |     raise ve_exc
warp_beacon  | ValueError: 121 is not a valid ThumbnailSource
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/utils.py", line 49, in get_input_media_from_file_id
warp_beacon  |     decoded = FileId.decode(file_id)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/file_id.py", line 255, in decode
warp_beacon  |     raise ValueError(f"Unknown thumbnail_source {thumbnail_source} of file_id {file_id}")
warp_beacon  | ValueError: Unknown thumbnail_source 121 of file_id AgACAgIAAxkDAAJL_2aiM6Qr5p_MuoCRtXRJQu3-WOH2AALF3jEbJbgRSeo7xOa1QPekAQADAgADeQADNQQ
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/telegram/bot.py", line 302, in upload_job
warp_beacon  |     messages = await self.client.send_media_group(
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/send_media_group.py", line 137, in send_media_group
warp_beacon  |     media = utils.get_input_media_from_file_id(i.media, FileType.PHOTO)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/utils.py", line 51, in get_input_media_from_file_id
warp_beacon  |     raise ValueError(
warp_beacon  | ValueError: Failed to decode "AgACAgIAAxkDAAJL_2aiM6Qr5p_MuoCRtXRJQu3-WOH2AALF3jEbJbgRSeo7xOa1QPekAQADAgADeQADNQQ". The value does not represent an existing local file, HTTP URL, or valid file id.
```
