### ISSUE TITLE
Does not return an error when downloading

### ISSUE THREAD

**Issue by FreeM1ne** [pyrogram/pyrogram#1378]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am using pyrogram via 
with Client("user", api_id, api_hash) as app

Problem when using the function to download files
full_path = app.download_media(message.document.file_id, file_name=file_name)

The point is that if in the process of downloading a file upload.GetFile error or other error comes out, it does not interrupt the code, that is, I can not catch the error through try except

In the console it writes an error and the function returns the full path and the code goes on

### Steps to reproduce

I think from the description of the problem it's pretty clear what I'm talking about

### Code example

```python
from pyrogram import Client
with Client("user", api_id, api_hash) as app:
    full_path = app.download_media(message.document.file_id, file_name=file_name)
```

### Logs

```shell
Telegram says: [420 FLOOD_WAIT_X] - A wait of 942 seconds is required (caused by "auth.ExportAuthorization")
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py", line 878, in get_file
    exported_auth = await self.invoke(
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 942 seconds is required (caused by "auth.ExportAuthorization")
# error
C:\Users\Administrator\Desktop\dir\downloads\name.zip # print full path
```

**Comment by FreeM1ne** [comment]
P.S. I have not found any normal solutions that would handle all errors, not just a certain one. Anyway, this is obviously a bug because the file was not successfully downloaded, but the function returns the full path of the file, which means that the code worked correctly

**Comment by FreeM1ne** [comment]
I am currently using this solution
`                    if not os.path.exists(full_path):
                        # return undownload

                    if os.path.getsize(full_path) < message.document.file_size - 200:
                         # return undownload
`
