### ISSUE TITLE
error 400 from poll 

### ISSUE THREAD

**Issue by Alias4D** [pyrogram/pyrogram#1379]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

get error 400 , pyrogram.errors.exceptions.bad_request_400.MediaInvalid: Telegram says: [400 MEDIA_INVALID] - The media is invalid (caused by "messages.SendMedia")

`import asyncio
from pyrogram import Client
from pyrogram.types import Poll,PollOption
app = Client("session", api_id=api_id, api_hash=api_hash)

async def main():
    await app.start()
    await app.send_message("me", "Hi!")
    await app.send_poll("me","test poll ? ",["yes","no"])
    await app.stop()
app.run(main())`

### Steps to reproduce

run code 
python pooly.py

pc windows 10

### Code example

```python
import asyncio
from pyrogram import Client
from pyrogram.types import Poll,PollOption
app = Client("session", api_id=api_id, api_hash=api_hash)

async def main():
    await app.start()
    await app.send_message("me", "Hi!")
    await app.send_poll("me","test poll ? ",["yes","no"])
    await app.stop()
app.run(main())
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Ali\Desktop\telegram-group-info\pooly.py", line 16, in <module>
    app.run(main())
  File "C:\Users\Ali\anaconda3\Lib\site-packages\pyrogram\methods\utilities\run.py", line 77, in run
    run(coroutine)
  File "C:\Users\Ali\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Ali\Desktop\telegram-group-info\pooly.py", line 14, in main
    await app.send_poll("me","test poll ? ",["yes","no"])
  File "C:\Users\Ali\anaconda3\Lib\site-packages\pyrogram\methods\messages\send_poll.py", line 140, in send_poll
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\anaconda3\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\anaconda3\Lib\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\anaconda3\Lib\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Ali\anaconda3\Lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MediaInvalid: Telegram says: [400 MEDIA_INVALID] - The media is invalid (caused by "messages.SendMedia")
```

**Comment by KurimuzonAkuma** [comment]
You cant sent polls in private chats, only forwarding

**Comment by Alias4D** [comment]
Thanks for reply 🙏
What is solution? please.
I need make poll in group and collect results from it 🌹

**Comment by KurimuzonAkuma** [comment]
> What is solution? please.

Dont send polls in private, only in chats or channels

**Comment by Alias4D** [comment]
Thanks very much ❤️
