### ISSUE TITLE
Can't send media due to 401(AuthKeyUnregistered) error

### ISSUE THREAD

**Issue by DevNordWind** [pyrogram/pyrogram#1427]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am connecting to Telegram using this code:
```
client: Client = get_client_str(user_id='123', session_str=settings.admin_session)
await client.load_session()
client.session = Session(
    client=client, dc_id=settings.dc_id, auth_key=bytes.fromhex(settings.auth_key), test_mode=False
)
await client.session.start()
client.is_connected = True
```

When I try to call Client methods like send_message(), get_chat(), get_chat_history(), get_me() and the like, I get the standard result.

But when sending media using:
`client.send_photo('me', photo=path + photo, caption='123')
`

I'm getting an error:
`pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "upload.SaveFilePart")`

### Steps to reproduce

**1. I am connecting to Telegram using this code:ode:**
```
client: Client = get_client_str(user_id='123', session_str=settings.admin_session)
await client.load_session()
client.session = Session(
    client=client, dc_id=settings.dc_id, auth_key=bytes.fromhex(settings.auth_key), test_mode=False
)
await client.session.start()
client.is_connected = True
```

**1.1 get_client_str function code:**

```
def get_client_str(user_id, session_str, proxy=None) -> Client:
    return Client(
        name=str(user_id),
        api_id=int(conf.pyro.api_id),
        api_hash=conf.pyro.api_hash,
        proxy=proxy,
        session_string=session_str,
        in_memory=True,
        device_model="Safari 16.4",
        system_version="1.9.6",
        app_version='1.9.6 (418)',
        lang_code='en',
        no_updates=True,

    )
```

**2.  When I try to call Client methods like send_message(), get_chat(), get_chat_history(), get_me() and the like, I get the standard result.**

**3. But when sending media using:**

`client.send_photo('me', photo=path + photo, caption='123')
`

I'm getting an error:
`pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "upload.SaveFilePart")`

### Logs

```shell
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/sweet_candy-YUIkJlsa-py3.10/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 108, in worker
    await session.invoke(data)
  File "/home/user/.cache/pypoetry/virtualenvs/sweet_candy-YUIkJlsa-py3.10/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/user/.cache/pypoetry/virtualenvs/sweet_candy-YUIkJlsa-py3.10/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/user/.cache/pypoetry/virtualenvs/sweet_candy-YUIkJlsa-py3.10/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "upload.SaveFilePart")
```

**Comment by DevNordWind** [comment]
Apparently, the Pyrogram storage was not written auth_key for some reason. I solved the problem by:

`await client.storage.auth_key(bytes.fromhex(settings.auth_key))`

**Comment by DevNordWind** [comment]
Apparently, the Pyrogram storage was not written auth_key for some reason. I solved the problem by:

`await client.storage.auth_key(bytes.fromhex(settings.auth_key))`
