### ISSUE TITLE
key error 0

### ISSUE THREAD

**Issue by AnujkumarGithub** [pyrogram/pyrogram#1429]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

when I run a program- 
terminal out-put of Replit IDE shows- key error 0

### Steps to reproduce

1. I am using "Replit IDE"
2. I try to install pyrogram using - pip3 install -U pyrogram but replit is unble to install this
3. I try - pip install pyrogram, its working.
4. Then I run the program 

### Code example

```python
from pyrogram import Client, filters

# Replace the following variables with your own values
API_ID = '19341831'
API_HASH = 'd5dd7d867fc35ae9fa59c54e54d218ad'
BOT_TOKEN = '7167823797:AAHnrBgaWCWnSQ7F838QRAQO2auiboiJby0'

# Initialize the bot
app = Client("my_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

# Define the start command handler
@app.on_message(filters.command("start"))
async def start(client, message):
    await message.reply_text("Hi, you're welcome!")

# Run the bot
if __name__ == "__main__":
    print("Bot is running...")
    app.run()
```

### Logs

```shell
Bot is running...
Traceback (most recent call last):
  File "/home/runner/1st-project/main.py", line 19, in <module>
    app.run()
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/nix/store/blyk7br3pqd873y5kbinxlngc1xb8sf9-python3-3.10.14/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/client.py", line 637, in load_session
    await Auth(
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 274, in create
    raise e
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 89, in create
    res_pq = await self.invoke(raw.functions.ReqPqMulti(nonce=nonce))
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 67, in invoke
    return self.unpack(response)
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/session/auth.py", line 60, in unpack
    return TLObject.read(b)
  File "/home/runner/1st-project/.pythonlibs/lib/python3.10/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 0
```

**Comment by AnujkumarGithub** [comment]
I was completely frustrated.
Thanku so much for you precious suggestion.

**Comment by EDM115** [comment]
@AnujkumarGithub I highly recommend you to revoke your bot token through BotFather  
this and the API hash and id are sensitive and personal information, never share them online
