### ISSUE TITLE
Cannot edit message edit_message_text in channel with real bot

### ISSUE THREAD

**Issue by AyraHikari** [pyrogram/pyrogram#1454]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

It seems real bot cannot edit text message in the channel.
But sending a message in channel is working fine

And yes, bot admin permission to manage messages is already checked

### Steps to reproduce

1. await app.edit_message_text("MyChannel", 12345, "Edited", disable_web_page_preview=True)
2. Raise an error

### Code example

```python
from pyrogram import Client, filters

app = Client("bot", api_id=api_id, api_hash=api_hash)

async def job():
    # this code work fine
    send = await app.send_message("MyChannel", "Hello world")
    # this code raise error
    await app.edit_message_text("MyChannel", send.id, "Hello world two", disable_web_page_preview=True)

scheduler = AsyncIOScheduler()
scheduler.add_job(job, "interval", seconds=60)

app.start()
scheduler.start()
```

### Logs

```shell
ERROR:apscheduler.executors.default:Job "job (trigger: interval[0:01:00], next run at: 2024-10-16 19:31:59 WIB)" raised an exception
Traceback (most recent call last):
  File "/home/ayra/.local/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayra/website/botv2/premium/modules/giveaway.py", line 312, in job
    raise e
  File "/home/ayra/website/botv2/premium/modules/giveaway.py", line 307, in job
    await app.edit_message_text(channel, message_id, text, disable_web_page_preview=True)
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 318, in send
    message = self.msg_factory(data)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/raw/core/tl_object.py", line 79, in __len__
    return len(self.write())
               ^^^^^^^^^^^^
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/raw/functions/messages/edit_message.py", line 119, in write
    b.write(Int(self.id))
            ^^^^^^^^^^^^
  File "/home/ayra/.local/lib/python3.11/site-packages/pyrogram/raw/core/primitives/int.py", line 33, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_bytes'
```

**Comment by AyraHikari** [comment]
My fault, the message_id is not an int in my actual code
This working fine now

`await app.edit_message_text(chat_id=channel, message_id=int(message_id), text=text, disable_web_page_preview=True)`

**Comment by Danstiv** [comment]
Hello @AyraHikari
Yes, pyrogram throws a slightly confusing error if a parameter of the wrong type is passed to a method.
It tries to serialize a value and treats it as if it were the right type, for example it tries to convert an int to a sequence of bytes, and since no type checking happens, you can pass str instead of int, and the error will only occur at the very end, on a completely different one level of abstractions.
