### ISSUE TITLE
When i use InviteToChannel function , why  did  rasie RpcError 'CHANNEL_ADD_INVALID'

### ISSUE THREAD

**Issue by van0303** [pyrogram/pyrogram#158]

**Comment by delivrance** [comment]
@van0303 Hi. Without the full error traceback and possibly your code I can't help you.

**Comment by van0303** [comment]
Traceback (most recent call last):                                                                                                              │    Error.raise_it(result, type(data))
  File "<console>", line 1, in <module>                                                                                                            File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/api/errors/error.py", line 63, in raise_it
  File "/Users/zj/workspace/python-src/tutorial/invitation/chat/simple.py", line 105, in handle                                                 │    raise UnknownError(x=rpc_error, query_type=query_type)
    users=self.user_ids_peer))                                                                                                                  │pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/client/client.py", line 908, in send                                 │    "_": "telegram:RpcError",
    r = self.session.send(data, retries, timeout)                                                                                               │    "error_code": 500,
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/session/session.py", line 420, in send                                    "error_message": "CHANNEL_ADD_INVALID"
    return self._send(data, timeout=timeout)                                                                                                    │}
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/session/session.py", line 407, in _send                               ^CException ignored in: <module 'threading' from '/Users/zj/anaconda3/envs/py36/lib/python3.6/threading.py'>
    Error.raise_it(result, type(data))                                                                                                          │Traceback (most recent call last):
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/api/errors/error.py", line 63, in raise_it                           │  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/threading.py", line 1294, in _shutdown
    raise UnknownError(x=rpc_error, query_type=query_type)                                                                                      │    t.join()
pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {                                                                                  │  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/threading.py", line 1056, in join
    "_": "telegram:RpcError",                                                                                                                        self._wait_for_tstate_lock()
    "error_code": 500,                                                                                                                             File "/Users/zj/anaconda3/envs/py36/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    "error_message": "CHANNEL_ADD_INVALID"                                                                                                      │    elif lock.acquire(block, timeout):
}

**Comment by van0303** [comment]
@delivrance Thank you

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/zj/workspace/python-src/tutorial/invitation/chat/simple.py", line 105, in handle
    users=self.user_ids_peer))
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/client/client.py", line 908, in send
    r = self.session.send(data, retries, timeout)
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/session/session.py", line 420, in send
    return self._send(data, timeout=timeout)
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/session/session.py", line 407, in _send
    Error.raise_it(result, type(data))
  File "/Users/zj/anaconda3/envs/py36/lib/python3.6/site-packages/pyrogram/api/errors/error.py", line 63, in raise_it
    raise UnknownError(x=rpc_error, query_type=query_type)
pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {
    "_": "telegram:RpcError",
    "error_code": 500,
    "error_message": "CHANNEL_ADD_INVALID"
}
>>>

**Comment by delivrance** [comment]
I need to see your simple.py code around line 105. The entire method call should be enough if you also tell me what `self.user_ids_peer` is exactly.

**Comment by van0303** [comment]
```
self.chat_members = self.app.get_chat_members(chat_id=self.chat_source, offset=self.offset,
                                                      limit=self.limit)
 self.user_ids = list()
 for i in range(0, len(self.user_ids), self.step):
            
            self.user_ids_peer = list()
            # wait for 3 seconds
            time.sleep(3)
            for j in range(self.step):

                if i + j >= len(self.user_ids):
                    break
                
                self.user_ids_peer.append(self.app.resolve_peer(self.user_ids[i + j]))

```

**Comment by delivrance** [comment]
I just noticed that's a 500-class error. I.e., a server error that doesn't depend on a wrong method usage on your side or in general the client (pyrogram) itself.

**Comment by hzexe** [comment]
This error from Telegram server.
No way to solve this issue unless the telegram changes policy again.
Unless the telegram changes policy again.
But telegram at mobile vision  can  work still.

**Comment by hzexe** [comment]
Or try other layer vision?

**Comment by delivrance** [comment]
> No way to solve this issue unless the telegram changes policy again.

It's unlikely to be a policy-related issue-- unless Telegram messed up error codes.
500-class errors are internal server errors, probably caused by some bug or hiccup on Telegram servers.

> Or try other layer vision?

Old Pyrogram versions that use older schemas are available, both on PyPI and GitHub (from tags), and can be used to test and see if the error persists.
