### ISSUE TITLE
app.start() fails 

### ISSUE THREAD

**Issue by Qunal** [pyrogram/pyrogram#167]
I have pyrogram working on a win 10 desktop with python 3.6 . using getparticpants sample. It was working fine for few weeks now it does not.
on app.start() we get the following error

`app.start()

Traceback (most recent call last):

  File "<ipython-input-7-8dd2436b0600>", line 1, in <module>
    app.start()

  File "I:\Users\Arvind\Annaconda\lib\site-packages\pyrogram\client\client.py", line 217, in start
    self.load_session()

  File "I:\Users\Arvind\Annaconda\lib\site-packages\pyrogram\client\client.py", line 937, in load_session
    s = json.load(f)

  File "I:\Users\Arvind\Annaconda\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

  File "I:\Users\Arvind\Annaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)

  File "I:\Users\Arvind\Annaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "I:\Users\Arvind\Annaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

`
Any hint what went wrong?

**Comment by delivrance** [comment]
@Qunal Hi. Your session file was messed up somehow, probably because you tried to run more than one client using the same session at the same time? Don't do that.

Fastest fix: delete the session file and log-in again, or manually open the session file and look what's wrong (it must be valid json). Keep in mind that running multiple clients with the same auth key (session file) is not supported neither by the server and pyrogram.
