### ISSUE TITLE
messages are not sent to user every time

### ISSUE THREAD

**Issue by kondyurin** [pyrogram/pyrogram#174]
hi, 
the error below occurred this week, it was not previously. Messages are sent through time, I can not understand the pattern.

```
Traceback (most recent call last):
  File "/home/runner/.site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/runner/.site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "main.py", line 83, in send
    send_message(text_message, username)
  File "main.py", line 36, in send_message
    functions.messages.SendMessage(user_id, message=message, random_id=random_id)
  File "/home/runner/.site-packages/pyrogram/client/client.py", line 908, in send
    r = self.session.send(data, retries, timeout)
  File "/home/runner/.site-packages/pyrogram/session/session.py", line 420, in send
    return self._send(data, timeout=timeout)
  File "/home/runner/.site-packages/pyrogram/session/session.py", line 407, in _send
    Error.raise_it(result, type(data))
  File "/home/runner/.site-packages/pyrogram/api/errors/error.py", line 63, in raise_it
    raise UnknownError(x=rpc_error, query_type=query_type)
pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {
    "_": "telegram:RpcError",
    "error_code": 400,
    "error_message": "RANDOM_ID_EMPTY"
}
```

code:
```
def send_message(message, username):
    
    random_id = randint(0, 10^12)
    app = Client(session_name='new_session', api_id=API_ID, api_hash=API_HASH)
    with app:
        user_id = app.resolve_peer(username)
        app.send(
            functions.messages.SendMessage(user_id, message=message, random_id=random_id)
        )
```

**Comment by delivrance** [comment]
What are you even doing that requires `messages.SendMessage`? Just use `app.send_message`, it takes care of the random_id automatically.

**Comment by kondyurin** [comment]
@delivrance because I want to send a message to the user, regardless of whether he is in a group or not

**Comment by delivrance** [comment]
@kondyurin There's no limitation like that with send_message. ``chat_id`` refers to either a user (private chat) or group/channel id
