### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by arminblack** [pyrogram/pyrogram#190]
hi i working on contact :
app.send(
			functions.contacts.block(id=message.chat.id)
		)
and get error :
'module' object is not callable
Traceback (most recent call last):
  File "/home/Mr.Black/.local/lib/python3.5/site-packages/pyrogram/client/dispatcher/dispatcher.py", line 148, in update_worker
    handler.callback(self.client, *args)
  File "main.py", line 22, in response
    functions.contacts.block(id=message.chat.id)
TypeError: 'module' object is not callable

**Comment by delivrance** [comment]
You must format your code and message. That's unreadable.
