### ISSUE TITLE
Bot can't login without session and raise exception 

### ISSUE THREAD

**Issue by AlanLiu4516** [pyrogram/pyrogram#219]

**Comment by AlanLiu4516** [comment]
self.load_session()
self.auth_key = Auth(self.dc_id, self.test_mode, self.ipv6, self._proxy).create() 

Exception:

Traceback (most recent call last):
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\client\client.py", line 1104, in load_session
    with open(os.path.join(self.workdir, "{}.session".format(self.session_name)), encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\747928105.session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/KNTT/telegram/code/tel-bot-reply/client/service/chat/test.py", line 11, in <module>
    app.run()  # Automatically start() and idle()
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\client\client.py", line 424, in run
    self.start()
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\client\client.py", line 270, in start
    self.load_session()
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\client\client.py", line 1109, in load_session
    self.auth_key = Auth(self.dc_id, self.test_mode, self.ipv6, self._proxy).create()
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\session\auth.py", line 255, in create
    raise e
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\session\auth.py", line 86, in create
    res_pq = self.send(functions.ReqPqMulti(nonce))
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\session\auth.py", line 64, in send
    return self.unpack(response)
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\session\auth.py", line 57, in unpack
    return Object.read(b)
  File "E:\KNTT\telegram\code\tel-bot-reply\pyrogram\api\core\object.py", line 32, in read
    return Object.all[int.from_bytes(b.read(4), "little")].read(b, *args)
KeyError: 0

**Comment by delivrance** [comment]
@AlanLiu4516 Pyrogram here is failing at the very first request. It's nothing specific to Bots. Seems like you have network issues or Telegram is blocked in your country. If you are behind a system proxy it is probably failing to forwards your requests.
