### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by GooDeeJaY** [pyrogram/pyrogram#228]
```Traceback (most recent call last):
  File "path", line 4, in <module>
    c.run()
  File "C:\Users\GooDeeJaY\AppData\Local\Programs\Python\Python37\lib\site-packages\pyrogram\client\client.py", line 424, in run
    self.start()
  File "C:\Users\GooDeeJaY\AppData\Local\Programs\Python\Python37\lib\site-packages\pyrogram\client\client.py", line 276, in start
    self.auth_key
  File "C:\Users\GooDeeJaY\AppData\Local\Programs\Python\Python37\lib\site-packages\pyrogram\session\session.py", line 79, in __init__
    print("Pyrogram v{}, {}".format(__version__, __copyright__))
  File "C:\Users\GooDeeJaY\AppData\Local\Programs\Python\Python37\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 47: character maps to <undefined>```

**Comment by delivrance** [comment]
@GooDeeJaY This looks like an issue of your terminal. Is that coming from MinGW's bash?

**Comment by GooDeeJaY** [comment]
No I'm using PyCharm terminal

**Comment by delivrance** [comment]
@GooDeeJaY You, somehow, need to tell your terminal to always output strings encoded using UTF-8.

**Comment by GooDeeJaY** [comment]
Fixed! Thanks! Sorry for disturbing)
