### ISSUE TITLE
Can't get invite link

### ISSUE THREAD

**Issue by KunoiSayami** [pyrogram/pyrogram#244]
**python version**: 3.7.2
**pyrogram version**: 0.12.0

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/main.py", line 273, in run
    self.do_revoke()
  File "/main.py", line 219, in do_revoke
    self.current_link = self.client.export_chat_invite_link(self.chat_id)
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/methods/chats/export_chat_invite_link.py", line 55, in export_chat_invite_link
    functions.channels.ExportInvite(
AttributeError: module 'pyrogram.api.functions.channels' has no attribute 'ExportInvite'
```

I rollback to version 0.11.0 it work normally

**Comment by delivrance** [comment]
Fixed, although the new method is currently disabled for bots server-side. We need to wait until Telegram releases a new Bot API update, apparently. More info: https://t.me/PyrogramLounge/53485.

**Comment by delivrance** [comment]
Ok, I've ported the old - but working - method from an older schema. [`export_chat_invite_link`](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.export_chat_invite_link) will now work at least for channels and supergroups, but not basic groups.
