### ISSUE TITLE
OverflowError: getsockaddrarg: port must be 0-65535.

### ISSUE THREAD

**Issue by LinArcX** [pyrogram/pyrogram#246]
I use lantern to bypass government censorship and talk to telegram api.
Lantern use localhost and port 432097 as default. this is the final result of confi.ini:
```
[pyrogram]
api_id = 748033
api_hash = b83a5c7c06571d109b431d1de6f988c4

[proxy]
enabled = True
hostname = 127.0.0.1
port = 432097
username = ""
password = ""
```
But it gives me this error when i run the bot:
```
╰ python server.py
Pyrogram v0.12.0, Copyright (C) 2017-2019 Dan Tès <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "server.py", line 31, in <module>
    APP.run()
  File "/usr/lib/python3.7/site-packages/pyrogram/client/client.py", line 440, in run
    self.start()
  File "/usr/lib/python3.7/site-packages/pyrogram/client/client.py", line 293, in start
    self.session.start()
  File "/usr/lib/python3.7/site-packages/pyrogram/session/session.py", line 178, in start
    raise e
  File "/usr/lib/python3.7/site-packages/pyrogram/session/session.py", line 119, in start
    self.connection.connect()
  File "/usr/lib/python3.7/site-packages/pyrogram/connection/connection.py", line 56, in connect
    self.connection.connect(self.address)
  File "/usr/lib/python3.7/site-packages/pyrogram/connection/transport/tcp/tcp_abridged_o.py", line 38, in connect
    super().connect(address)
  File "/usr/lib/python3.7/site-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
OverflowError: getsockaddrarg: port must be 0-65535.
```

**Comment by delivrance** [comment]
The error is clear enough
