### ISSUE TITLE
OSError when running code in windows 10

### ISSUE THREAD

**Issue by javad94** [pyrogram/pyrogram#252]
## Checklist
- [*] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [*] I have searched in the issue tracker for similar bug reports, including closed ones.
- [*] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
When I run the code below and someone send a message in the groups I had joined, Pyrogram gives me exception.
I test this code on windows and WSL and only gives error when running windows. 

system info:
```
Windows 10 x64 1903
Python 3.6.6 x64
Pyrogram 0.14.1
```

## Steps to Reproduce
1. run this code:
```
from pyrogram import Client

api_id = 123456
api_hash = '123456789'

app = Client(
    "my_account",
    api_id= api_id,
    api_hash= api_hash
)

@app.on_message()
def my_function(client, message):
    print(message)

app.run()
```
2. create a group and send one message to it.

## Traceback
```
[Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\Javad\cheat\grandedesafio-cheater\.venv\lib\site-packages\pyrogram\client\ext\dispatcher.py", line 157, in update_worker
    handler.callback(self.client, *args)
  File "D:\C\Documents\test.py", line 14, in my_function
    print(message)
  File "C:\Users\Javad\cheat\grandedesafio-cheater\.venv\lib\site-packages\pyrogram\client\types\object.py", line 59, in __str__
    return dumps(self, indent=4, default=Object.default, ensure_ascii=False)
  File "C:\Users\Javad\Anaconda3\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 438, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 438, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Users\Javad\Anaconda3\Lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\Users\Javad\cheat\grandedesafio-cheater\.venv\lib\site-packages\pyrogram\client\types\object.py", line 53, in default
    for attr in obj.__slots__
  File "C:\Users\Javad\cheat\grandedesafio-cheater\.venv\lib\site-packages\pyrogram\client\types\object.py", line 54, in <listcomp>
    if getattr(obj, attr) is not None
OSError: [Errno 22] Invalid argument
```

**Comment by delivrance** [comment]
Hi, I never used Anaconda, but you [claim](https://t.me/PyrogramChat/88853) is just CPython underneath and that the issue persists on CPython installations too, so I tested on Windows 10 with a clean installation of [Python 3.6.6](https://www.python.org/downloads/release/python-366/) using the default command prompt and I can't reproduce the issue. All works fine.

Moreover, the error is an unclear OSError which makes me think it has something to do with your specific setup rather than Pyrogram itself. I suggest you try install a different python environment and see if something changes.
