### ISSUE TITLE
Weird error returned when client time is out of sync

### ISSUE THREAD

**Issue by copfs0c13ty** [pyrogram/pyrogram#26]
I am getting this error while running the app for the first time. my code is the sample code which comes in the documents.

Traceback (most recent call last):
  File "D:/Telegram Solution/pythogeram/pythogeram.py", line 17, in <module>
    main()
  File "D:/Telegram Solution/pythogeram/pythogeram.py", line 12, in main
    client.start()
  File "D:\Hooman\python3venv\lib\site-packages\pyrogram\client\client.py", line 170, in start
    terms = self.session.start()
  File "D:\Hooman\python3venv\lib\site-packages\pyrogram\session\session.py", line 125, in start
    self.current_salt = self._send(functions.GetFutureSalts(1)).salts[0]
AttributeError: 'BadMsgNotification' object has no attribute 'salts'

**Comment by delivrance** [comment]
@copfs0c13ty  Hi. This error is due to wrong date on your side, sync your clock and try again. (yes, I should really make it more friendly).
