### ISSUE TITLE
The user has been deleted/deactivated (caused by "messages.GetPinnedDialogs")

### ISSUE THREAD

**Issue by kosmodromov** [pyrogram/pyrogram#270]
Hi,

`
# pip show pyrogram

Name: Pyrogram
Version: 0.15.1
Summary: Telegram MTProto API Client Library and Framework for Python
Home-page: https://github.com/pyrogram
Author: Dan
Author-email: dan@pyrogram.org
License: LGPLv3+
Location: /home/test/venv/lib/python3.6/site-packages
Requires: pyaes, pysocks
Required-by:
`

I did following steps:
1. I've completed registration on device
2. Tried to register on vps (ip from another country)
3. Get code in mobile app and put it in phone code field
4. Run pyrogram application and got this ban

`Old session file detected: "pyrogram_968.session.OLD". You can remove this file now
Pyrogram v0.15.1, Copyright (C) 2017-2019 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "watcher_telegram.py", line 104, in <module>
    client.start()
  File "/home/test/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 317, in start
    raise e
  File "/home/test/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 310, in start
    self.send(functions.messages.GetPinnedDialogs(folder_id=0))
  File "/home/test/venv/lib/python3.6/site-packages/pyrogram/client/client.py", line 984, in send
    r = self.session.send(data, retries, timeout)
  File "/home/test/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 437, in send
    return self._send(data, timeout=timeout)
  File "/home/test/venv/lib/python3.6/site-packages/pyrogram/session/session.py", line 424, in _send
    RPCError.raise_it(result, type(data))
  File "/home/test/venv/lib/python3.6/site-packages/pyrogram/errors/rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.unauthorized_401.UserDeactivatedBan: [401 USER_DEACTIVATED_BAN]: The user has been deleted/deactivated (caused by "messages.GetPinnedDialogs")
`

Registration:
`from pyrogram import Client

app = Client("pyrogram_968")
app.start()
app.stop()`

app:
`
from pyrogram import Client, MessageHandler, RawUpdateHandler

client = Client(session_name="pyrogram_968")
client.add_handler(MessageHandler(callback))
client.start()
`

**Comment by scrooge001** [comment]
i also got that error. but i have running my bot since 1 year. after i try to restart my bot i got this error. is there any solution??
