### ISSUE TITLE
Client.get_messages is broken

### ISSUE THREAD

**Issue by itshaadi** [pyrogram/pyrogram#288]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version. **(*)**
## Description
I want to clear the conversations that I had with the bot. using [Client.delete_messages](https://docs.pyrogram.org/api/methods#pyrogram.Client.delete_messages) and in order to do that, it requires `message_ids`, which I can get using [Client.get_messages](https://docs.pyrogram.org/api/methods#pyrogram.Client.get_messages)

the problem is that `get_messages` [complains](https://github.com/pyrogram/pyrogram/blob/a21858a262910817bcd2d1584065a06d0e315f24/pyrogram/client/methods/messages/get_messages.py#L77) about `No argument supplied` when it's used in the following order (mentioned in steps to reproduce).

however, the same function will yield the desired result, using `client.get_history`, also tested with asyncio branch, same error.
## Steps to Reproduce
```python
@Client.on_message(Filters.command(['clear', 'Clear'], prefix=''))
def clear(client, message):
    messages = client.get_messages(chat_id=message.chat.id)
    msg_ids = []
    for msg in messages:
        msg_ids.append(msg.message_id)
    client.delete_messages(chat_id=message.chat.id, message_ids=msg_ids)
```
(it shouldn't complain right? because all the other arguments are optional)

## Traceback
```
pyrogram.client.ext.dispatcher - ERROR - No argument supplied
Traceback (most recent call last):
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 180, in update_worker
    handler.callback(self.client, *args)
  File "/home/odin/projects/crab/plugins/commands.py", line 173, in clear
    messages = client.get_messages(chat_id=message.chat.id)
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/methods/messages/get_messages.py", line 77, in get_messages
    raise ValueError("No argument supplied")
ValueError: No argument supplied
```

**(*)**
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import pyrogram
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/__init__.py", line 32, in <module>
    from .client import *
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/__init__.py", line 19, in <module>
    from .client import Client
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/client.py", line 40, in <module>
    from pyrogram.client.methods.password.utils import compute_check
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/methods/__init__.py", line 19, in <module>
    from .bots import Bots
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/methods/bots/__init__.py", line 20, in <module>
    from .answer_inline_query import AnswerInlineQuery
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/methods/bots/answer_inline_query.py", line 23, in <module>
    from ...types.inline_mode import InlineQueryResult
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/types/__init__.py", line 20, in <module>
    from .inline_mode import *
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/types/inline_mode/__init__.py", line 19, in <module>
    from .inline_query import InlineQuery
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/types/inline_mode/inline_query.py", line 24, in <module>
    from ..messages_and_media import Location
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/types/messages_and_media/__init__.py", line 25, in <module>
    from .message import Message
  File "/home/odin/projects/crab/env/lib/python3.7/site-packages/pyrogram/client/types/messages_and_media/message.py", line 2873
    def retract_vote(
                    ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by delivrance** [comment]
`get_messages` works as it should, your usage is wrong. However, I agree the description doesn't do a great job in explaining exactly what the method is used for.

The reason `message_ids` is optional is that you can pass either that or `reply_to_message_ids`. This confusion could be fixed by allowing one argument only and a flag to tell messages and replied messages apart. For now:

- https://github.com/pyrogram/pyrogram/commit/87bbd764b9751b8e9e231f0d3ba75efe39bf3cd0 added a better summary in order for people to understand `get_messages` it's useful only when you already have message ids available.
- https://github.com/pyrogram/pyrogram/commit/7b9a38a2bae77c33ea12ec6887d4789239b6ccf6 fixed the `IndentationError` which was due to a bad PR I merged.

About your question, you can use [message.DeleteHistory](https://docs.pyrogram.org/telegram/functions/messages/delete-history) to delete the private chat history with a single method call. You can pass `peer=app.resolve_peer("usernamebot")` and `max_id=0`. More info at https://docs.pyrogram.org/topics/advanced-usage.
