### ISSUE TITLE
python3.4 support broken by dict unpacking (PEP448)

### ISSUE THREAD

**Issue by alozovskoy** [pyrogram/pyrogram#302]
## Description
In Readme file claimed than supported python version is 3.4 or higher. But in many modules you use dict unpacking (**someDict), that available from python3.5 (by PEP 448). So, you should edit project readme or few modules.
Please report me - is "backward compatibility" patch is acceptable (and i can write and send necessary PR by myself, because who needed py3.4 in 2019 =) ), or upgrade is my only available way.

## Steps to Reproduce
Just try to import pyrogram at python3.4. Relevanced results in next section with traceback. I use 
0.16.0.dev -version of pyrogram, issue is comming on https://github.com/pyrogram/pyrogram/commit/2f07e7abc400144c47f1e17d09a45df24730f71d , but problem is not in this file, many of it in project.

## Traceback
```
$ python3
Python 3.4.5 (default, Dec 11 2017, 14:22:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrogram
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/tgcrypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pyrogram/__init__.py", line 32, in <module>
    from .client import *
  File "/usr/lib/python3.4/site-packages/pyrogram/client/__init__.py", line 19, in <module>
    from .client import Client
  File "/usr/lib/python3.4/site-packages/pyrogram/client/client.py", line 40, in <module>
    from pyrogram.client.methods.password.utils import compute_check
  File "/usr/lib/python3.4/site-packages/pyrogram/client/methods/__init__.py", line 19, in <module>
    from .bots import Bots
  File "/usr/lib/python3.4/site-packages/pyrogram/client/methods/bots/__init__.py", line 20, in <module>
    from .answer_inline_query import AnswerInlineQuery
  File "/usr/lib/python3.4/site-packages/pyrogram/client/methods/bots/answer_inline_query.py", line 23, in <module>
    from ...types.inline_mode import InlineQueryResult
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/__init__.py", line 19, in <module>
    from .bots_and_keyboards import *
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/bots_and_keyboards/__init__.py", line 20, in <module>
    from .callback_query import CallbackQuery
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/bots_and_keyboards/callback_query.py", line 27, in <module>
    from ..user_and_chats import User
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/user_and_chats/__init__.py", line 23, in <module>
    from .chat_preview import ChatPreview
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/user_and_chats/chat_preview.py", line 23, in <module>
    from ..messages_and_media import Photo
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/messages_and_media/__init__.py", line 25, in <module>
    from .message import Message
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/messages_and_media/message.py", line 28, in <module>
    from .message_entity import MessageEntity
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/messages_and_media/message_entity.py", line 23, in <module>
    from ..user_and_chats.user import User
  File "/usr/lib/python3.4/site-packages/pyrogram/client/types/user_and_chats/user.py", line 189
    **User._parse_status(user.status, user.bot),
                                               ^
SyntaxError: invalid syntax
>>> 
```

**Comment by delivrance** [comment]
@alozovskoy Thanks for bringing this out. I guess we can bump the requirements at this point because Python 3.4 is EOL since March 16, 2019.

I believe we should set Python 3.5.2 as minimum requirement because of issues with the `typing` module, so that we can also get rid of ugly hacks like this one: https://github.com/pyrogram/pyrogram/blob/b42c6581b8dc1216cf3455d3f525a01337687ed1/pyrogram/__init__.py#L21-L25
