### ISSUE TITLE
AttributeError: 'int' object has no attribute 'write'

### ISSUE THREAD

**Issue by matiniamirhossein** [pyrogram/pyrogram#31]
Hello,
Thanks for you library.
There is a problem with the library version 0.6.2.
I get the above error when getting messages:
```
channel = client.resolve_peer(username)
messages = client.send(GetMessages(channel, range(min_message, 1 + max_message)))
```
The version 0.6.1 is working fine.
Full stack trace:
```
Traceback (most recent call last):
  File "/home/amir/pydev/basic.py", line 54, in <module>
    fetch_channel_messages("@TEST")
  File "/home/amir/pydev/basic.py", line 28, in fetch_channel_messages
    messages = client.send(GetMessages(channel, range(min_message, 1 + max_message)))
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/client/client.py", line 549, in send
    r = self.session.send(data)
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/session/session.py", line 402, in send
    return self._send(data)
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/session/session.py", line 367, in _send
    message = self.msg_factory(data)
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/api/core/object.py", line 44, in __len__
    return len(self.write())
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/api/functions/channels/get_messages.py", line 63, in write
    b.write(Vector(self.id))
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in __new__
    for i in value
  File "/home/amir/.local/lib/python3.6/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    for i in value
AttributeError: 'int' object has no attribute 'write'
```

Some clues:
In version 0.6.1 api/functions/channels/get_messages.py class GetMessage function write:
```
b.write(Vector(self.id, Int))
```
In version 0.6.2:
```
b.write(Vector(self.id))
```

**Comment by delivrance** [comment]
@matiniamirhossein Hi. Assuming you are using channels.GetMessages: https://docs.pyrogram.ml/functions/channels/GetMessages/

The `id` parameter must be a list of `InputMessage*` objects, not `int`s.
A simple list comprehension using InputMessageID should do the job: ^^

``` python
[types.InputMessageID(i) for i in range(min_message, 1 + max_message)]
```

**Comment by matiniamirhossein** [comment]
@delivrance Thank you <3 But it was working in an older version. That's why I didn't even thought of this.

Have a good day.

**Comment by delivrance** [comment]
Yeah, you are right, the new Layer 75 patch brought this change 0b15cb98672a8d4f21ef04d0803cd5f46415d1e7

**Comment by kalomi** [comment]
سلام داداش ایدی تلگرام رو میدی ؟
