### ISSUE TITLE
400 MESSAGE_NOT_MODIFIED error

### ISSUE THREAD

**Issue by IamJithendra** [pyrogram/pyrogram#340]
2019-11-08T09:12:25.019449+00:00 app[worker.1]: r = await self.session.send(data, retries, timeout)
2019-11-08T09:12:25.019452+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 420, in send
2019-11-08T09:12:25.019453+00:00 app[worker.1]: return await self.send(data, retries - 1, timeout)
2019-11-08T09:12:25.019455+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 409, in send
2019-11-08T09:12:25.019457+00:00 app[worker.1]: return await self._send(data, timeout=timeout)
2019-11-08T09:12:25.019460+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 393, in _send
2019-11-08T09:12:25.019462+00:00 app[worker.1]: RPCError.raise_it(result, type(data))
2019-11-08T09:12:25.019464+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/errors/rpc_error.py", line 84, in raise_it
2019-11-08T09:12:25.019466+00:00 app[worker.1]: is_unknown=False)
2019-11-08T09:12:25.019468+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified (caused by "messages.EditMessage")
2019-11-08T09:14:04.159601+00:00 app[worker.1]: 2019-11-08 09:14:04,159 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): chatbase.com:443
2019-11-08T09:14:04.437577+00:00 app[worker.1]: 2019-11-08 09:14:04,437 - urllib3.connectionpool - DEBUG - https://chatbase.com:443 "POST /api/message HTTP/1.1" 200 44
2019-11-08T09:17:07.635404+00:00 app[worker.1]: 2019-11-08 09:17:07,635 - root - INFO - NetWorkerTask started
2019-11-08T09:17:07.635948+00:00 app[worker.1]: 2019-11-08 09:17:07,635 - root - INFO - NetWorkerTask started
2019-11-08T09:17:07.636353+00:00 app[worker.1]: 2019-11-08 09:17:07,636 - root - INFO - NetWorkerTask started
2019-11-08T09:17:09.088232+00:00 app[worker.1]: 2019-11-08 09:17:09,086 - pyrogram.client.ext.dispatcher - ERROR - [400 MESSAGE_NOT_MODIFIED]: The message was not modified (caused by "messages.EditMessage")
2019-11-08T09:17:09.088253+00:00 app[worker.1]: Traceback (most recent call last):
2019-11-08T09:17:09.088256+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 409, in send
2019-11-08T09:17:09.088258+00:00 app[worker.1]: return await self._send(data, timeout=timeout)
2019-11-08T09:17:09.088260+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 391, in _send
2019-11-08T09:17:09.088262+00:00 app[worker.1]: raise TimeoutError
2019-11-08T09:17:09.088264+00:00 app[worker.1]: TimeoutError
2019-11-08T09:17:09.088266+00:00 app[worker.1]:
2019-11-08T09:17:09.088269+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2019-11-08T09:17:09.088271+00:00 app[worker.1]:
2019-11-08T09:17:09.088273+00:00 app[worker.1]: Traceback (most recent call last):
2019-11-08T09:17:09.088275+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
2019-11-08T09:17:09.088277+00:00 app[worker.1]: await handler.callback(self.client, *args)
2019-11-08T09:17:09.088279+00:00 app[worker.1]: File "/app/plugins/rename_file.py", line 69, in rename_doc
2019-11-08T09:17:09.088281+00:00 app[worker.1]: message_id=a.message_id
2019-11-08T09:17:09.088284+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/client/methods/messages/edit_message_text.py", line 84, in edit_message_text
2019-11-08T09:17:09.088286+00:00 app[worker.1]: **await self.parser.parse(text, parse_mode)
2019-11-08T09:17:09.088288+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/client/client.py", line 1385, in send
2019-11-08T09:17:09.088290+00:00 app[worker.1]: r = await self.session.send(data, retries, timeout)
2019-11-08T09:17:09.088292+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 420, in send
2019-11-08T09:17:09.088294+00:00 app[worker.1]: return await self.send(data, retries - 1, timeout)
2019-11-08T09:17:09.088296+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 409, in send
2019-11-08T09:17:09.088298+00:00 app[worker.1]: return await self._send(data, timeout=timeout)
2019-11-08T09:17:09.088300+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/session/session.py", line 393, in _send
2019-11-08T09:17:09.088302+00:00 app[worker.1]: RPCError.raise_it(result, type(data))
2019-11-08T09:17:09.088304+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/errors/rpc_error.py", line 84, in raise_it
2019-11-08T09:17:09.088306+00:00 app[worker.1]: is_unknown=False)
2019-11-08T09:17:09.088309+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.MessageNotModified: [400 MESSAGE_NOT_MODIFIED]: The message was not modified (caused by "messages.EditMessage")

**Comment by ColinTheShark** [comment]
Either format your traceback, or paste it to sites like [del.dog](https://del.dog). That is unreadable.

Also just to guess from the title: you need to pass a string to `edit_message_*()`, that's actually different from what was already there.

**Comment by IamJithendra** [comment]
https://del.dog/ifipulotux

**Comment by delivrance** [comment]
@IamJithendra Unless it's because of two edits repeated by _you_, It's probably the same known issue:

> Basically, your first edit request was repeated automatically by pyrogram for some reason, probably because the server took too much to answer and the second request was doing the same edit which lead to that error

https://t.me/PyrogramChat/133012

You can ignore that error for now.

**Comment by MonkAnoo** [comment]
> @IamJithendra Unless it's because of two edits repeated by _you_, It's probably the same known issue:
> 
> > Basically, your first edit request was repeated automatically by pyrogram for some reason, probably because the server took too much to answer and the second request was doing the same edit which lead to that error
> 
> https://t.me/PyrogramChat/133012
> 
> You can ignore that error for now.

There is no Solution for this error now ?

**Comment by delivrance** [comment]
No. There's no mechanism to avoid duplicated queries like there is for other methods (e.g. send_message), the error is safe to be ignored because you already have the latest changes.
