### ISSUE TITLE
pyrogram doesn't import in Ubuntu 16.04

### ISSUE THREAD

**Issue by srazi** [pyrogram/pyrogram#382]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
It just doesn't import.

## Steps to Reproduce
$ python3
\>\>\> import pyrogram

## Traceback
The full traceback (if applicable).
```
>>> import pyrogram
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/__init__.py", line 23, in <module>
    from .client import *
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/__init__.py", line 19, in <module>
    from .client import Client
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 39, in <module>
    from pyrogram.client.methods.password.utils import compute_check
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/methods/__init__.py", line 19, in <module>
    from .bots import Bots
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/methods/bots/__init__.py", line 19, in <module>
    from .answer_callback_query import AnswerCallbackQuery
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/methods/bots/answer_callback_query.py", line 20, in <module>
    from pyrogram.client.ext import BaseClient
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/ext/__init__.py", line 19, in <module>
    from .base_client import BaseClient
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/ext/base_client.py", line 28, in <module>
    from ..parser import Parser
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/parser/__init__.py", line 19, in <module>
    from .parser import Parser
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/parser/parser.py", line 23, in <module>
    from .html import HTML
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/parser/html.py", line 109, in <module>
    class HTML:
  File "/home/venus/.local/lib/python3.5/site-packages/pyrogram/client/parser/html.py", line 110, in HTML
    def __init__(self, client: Union["pyrogram.BaseClient", None]):
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'pyrogram' has no attribute 'BaseClient'
```

**Comment by delivrance** [comment]
Make sure you meet the requirements. Python 3.5.2 and below are not supported.

**Comment by srazi** [comment]
Oh sorry I didn't read README.md and I didn't see the same notice in documentation. I was using 3.5.2 and now using 3.8.2 it works great.
Thanks.
