### ISSUE TITLE
InlineQueryResultArticle error

### ISSUE THREAD

**Issue by RianFC** [pyrogram/pyrogram#389]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
I used reply_markup in InlineQueryResultArticle and gave this error, without it nothing happens

## Steps to Reproduce
ERROR:pyrogram.client.ext.dispatcher:'NoneType' object has no attribute 'write'

## Traceback
```ERROR:pyrogram.client.ext.dispatcher:'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
    await handler.callback(self.client, *args)
  File "/home/rian/Documentos/GitHub/LyricsPyRobot Beta/plugins/inl.py", line 14, in inl
    await message.answer(results=results, is_personal=True, cache_time=0)
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/client/types/inline_mode/inline_query.py", line 148, in answer
    return await self._client.answer_inline_query(
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/client/methods/bots/answer_inline_query.py", line 101, in answer_inline_query
    return await self.send(
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/client/client.py", line 1385, in send
    r = await self.session.send(data, retries, timeout)
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 409, in send
    return await self._send(data, timeout=timeout)
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 362, in _send
    message = self.msg_factory(data)
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/session/internals/msg_factory.py", line 38, in __call__
    len(body)
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/tl_object.py", line 76, in __len__
    return len(self.write())
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/functions/messages/set_inline_bot_results.py", line 88, in write
    b.write(Vector(self.results))
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/primitives/vector.py", line 50, in __new__
    + [
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    else i.write()
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/types/input_bot_inline_result.py", line 107, in write
    b.write(self.send_message.write())
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/types/input_bot_inline_message_text.py", line 78, in write
    b.write(self.reply_markup.write())
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/types/reply_inline_markup.py", line 57, in write
    b.write(Vector(self.rows))
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/primitives/vector.py", line 50, in __new__
    + [
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    else i.write()
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/types/keyboard_button_row.py", line 57, in write
    b.write(Vector(self.buttons))
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/primitives/vector.py", line 50, in __new__
    + [
  File "/home/rian/.local/lib/python3.8/site-packages/pyrogram/api/core/primitives/vector.py", line 52, in <listcomp>
    else i.write()
AttributeError: 'NoneType' object has no attribute 'write'```

**Comment by ColinTheShark** [comment]
Please make sure to also share the code you tried to run.

    ```python
    your code here
    ```

**Comment by RianFC** [comment]
``` python
from pyrogram import Client, InlineQueryResultArticle, InputTextMessageContent, InlineKeyboardButton, InlineKeyboardMarkup
from lyricspy import letras, muximatch
from db import dbc
from utils import get_current_playing, get_token
from uuid import uuid4

let = letras()

mux = muximatch()

@Client.on_inline_query()
async def inl(client, message):
    results = await spoty(str(message.from_user.id))
    print(results)
    if message.query:
        i = mux.auto(message.query)
        for a in i:
            results.append(InlineQueryResultArticle(
                title=f'{a["musica"]} - {a["autor"]}',
                id=str(uuid4()),
                input_message_content=InputTextMessageContent(
                    message_text=f'{a["musica"]} - {a["autor"]}')))
    await message.answer(results=results, is_personal=True, cache_time=0)
    
async def spoty(user_id):
    db = dbc()
    if user_id in db:
        print(user_id)
        a = await get_current_playing(user_id, db)
        if not a:
            results = [InlineQueryResultArticle(
                title='spoti: Você não está tocando nada',
                id='spoti',
                thumb_url='https://piics.ml/amn/lpy/spoti.png',
                input_message_content=InputTextMessageContent(
                    message_text="Você não está tocando nada"))]
            return results
        else:
            a = mux.auto(f"{a['item']['artists'][0]['name']} {a['item']['name']}", limit=1)
            if not a:
                a = let.auto(f"{a['item']['artists'][0]['name']} {a['item']['name']}", limit=1)
                if not a:
                    results = [InlineQueryResultArticle(
                        title='spoti: Letra não encontrada :(',
                        id='spoti',
                        thumb_url='https://piics.ml/amn/lpy/spoti.png',
                        input_message_content=InputTextMessageContent(
                            message_text="Letra não encontrada :("))]
                    return results
            a = a[0]
            kb = InlineKeyboardMarkup(inline_keyboard=[
                [InlineKeyboardButton('Aguarde...')]
            ])
            results = [InlineQueryResultArticle(
                title=f'spoti: {a["musica"]} - {a["autor"]}',
                id='spoti',
                thumb_url='https://piics.ml/amn/lpy/spoti.png',
                input_message_content=InputTextMessageContent(
                    message_text=f'{a["musica"]} - {a["autor"]}\n\nInfelizmente não está funcionando a versão inline'))]
            return results```

**Comment by delivrance** [comment]
@RianFC We want a minimal example, not your whole (non-working) code. 60 lines spanning in 7 indentation levels with multiple branches is definitely not minimal.
