### ISSUE TITLE
callback filter giving error

### ISSUE THREAD

**Issue by ExAxee** [pyrogram/pyrogram#402]
I have this inline keyboard:

```
bot.send_message(str(message["chat"]["id"]), getStatus(), reply_markup=InlineKeyboardMarkup([
    [InlineKeyboardButton("Actions", callback_data="action")],
]))
```

and the callback filter:

```
@bot.on_message(Filters.callback_data("action"))
def action(bot, message):
    print("Hello")
```

but when trying to press the button pyrogram gives an error:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 186, in update_worker
    if handler.check(parsed_update):
  File "/home/pi/.local/lib/python3.7/site-packages/pyrogram/client/handlers/handler.py", line 28, in check
    if callable(self.filters)
  File "/home/pi/.local/lib/python3.7/site-packages/pyrogram/client/filters/filters.py", line 387, in <lambda>
    return create(lambda flt, cb: cb.data == flt.data, "CallbackDataFilter", data=data)
AttributeError: 'Message' object has no attribute 'data'
````

I don't know what I'm doing wrong.

**Comment by delivrance** [comment]
You are using `callback_data`, a filter intended for callback queries, inside a message handler (`on_message`).
