### ISSUE TITLE
Throws "KeyError: 0" exceptions when starts app

### ISSUE THREAD

**Issue by rstm-sf** [pyrogram/pyrogram#406]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I run last and 15.0.1 versions

## Description
Throws "KeyError: 0" exceptions when starts app

## Steps to Reproduce
```sh
$ python --version
Python 3.8.0

$ pip freeze
pkg-resources==0.0.0
pyaes==1.6.1
Pyrogram==0.17.1
PySocks==1.7.1
TgCrypto==1.2.1
```
```py
from pyrogram import Client

app = Client("client", api_id=API_ID, api_hash='API_HASH')
app.start()
```

## Traceback
```
Traceback (most recent call last):
  File "untitled.py", line 4, in <module>
    app.start()
  File "./env/lib/python3.8/site-packages/pyrogram/client/client.py", line 827, in start
    is_authorized = self.connect()
  File "./env/lib/python3.8/site-packages/pyrogram/client/client.py", line 261, in connect
    self.load_session()
  File "./env/lib/python3.8/site-packages/pyrogram/client/client.py", line 1505, in load_session
    self.storage.auth_key(Auth(self, self.storage.dc_id()).create())
  File "./env/lib/python3.8/site-packages/pyrogram/session/auth.py", line 256, in create
    raise e
  File "./env/lib/python3.8/site-packages/pyrogram/session/auth.py", line 87, in create
    res_pq = self.send(functions.ReqPqMulti(nonce=nonce))
  File "./env/lib/python3.8/site-packages/pyrogram/session/auth.py", line 65, in send
    return self.unpack(response)
  File "./env/lib/python3.8/site-packages/pyrogram/session/auth.py", line 58, in unpack
    return TLObject.read(b)
  File "./env/lib/python3.8/site-packages/pyrogram/api/core/tl_object.py", line 33, in read
    return objects[int.from_bytes(b.read(4), "little")].read(b, *args)
KeyError: 0
```

**Comment by delivrance** [comment]
Seems like a bad connection. Probably Telegram is blocked in your country or you are behind a proxy of some kind.

**Comment by delivrance** [comment]
Also, don't edit the template where it asks specifically to try the latest development version from github.

**Comment by rstm-sf** [comment]
> Seems like a bad connection. Probably Telegram is blocked in your country or you are behind a proxy of some kind.

Oh thanks! I forgot about it already :)

> closed this
 @delivrance, It seems to me that a fix would be a good reason for closing, which gives a more understandable error message. "KeyError: 0" -- this message does not carry useful information to the user. It would be nice if there was a connection issue message :)

> Also, don't edit the template where it asks specifically to try the latest development version from github.

Oops, yes, here I was wrong, I apologize

**Comment by vaintrub** [comment]
Hello! When I start the client in docker, I got the same error but I don't use some proxies and tg is allowed in my country. :( What could be the reason?
