### ISSUE TITLE
pyrogram.errors.exceptions.bad_request_400.MediaEmpty: [400 MEDIA_EMPTY]: The media is invalid (caused by "messages.SendMedia")

### ISSUE THREAD

**Issue by Karam-DEV** [pyrogram/pyrogram#408]
## Checklist
- [•] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [•] I have searched in the issue tracker for similar bug reports, including closed ones.
- [•] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
I want to send video from link
And this is my code
`app.send_video(chat_id,"http://s1.reslayer.com/naruto-shippuuden/428/m.mp4", progress=progress)`
But when i run the code This error appears
## Traceback
`
[400 MEDIA_EMPTY]: The media is invalid (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 205, in update_worker
    handler.callback(self.client, *args)
  File "<string>", line 62, in main
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pyrogram/client/methods/messages/send_video.py", line 198, in send_video
    **self.parser.parse(caption, parse_mode)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pyrogram/client/client.py", line 1418, in send
    r = self.session.send(data, retries, timeout, self.sleep_threshold)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pyrogram/session/session.py", line 454, in send
    return self._send(data, timeout=timeout)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pyrogram/session/session.py", line 427, in _send
    RPCError.raise_it(result, type(data))
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pyrogram/errors/rpc_error.py", line 84, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.MediaEmpty: [400 MEDIA_EMPTY]: The media is invalid (caused by "messages.SendMedia")
`

**Comment by delivrance** [comment]
Either telegram can't fetch the url or the media is too big. You can upload a maximum of 20 MB per file by url.

**Comment by PYROPRIEST** [comment]
I also have this error for a auto filter bot

**Comment by thegauravparmar** [comment]
@PYROPRIEST  were you able to solve the issue?
