### ISSUE TITLE
sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by adolfaka** [pyrogram/pyrogram#426]
Please tell me what the error may be related to.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/ext/syncer.py", line 80, in sync
    client.storage.save()
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/storage/sqlite_storage.py", line 81, in save
    self.date(int(time.time()))
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/storage/sqlite_storage.py", line 166, in date
    return self._accessor(value)
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/storage/sqlite_storage.py", line 154, in _accessor
    return self._get() if value == object else self._set(value)
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/storage/sqlite_storage.py", line 150, in _set
    (value,)
sqlite3.OperationalError: attempt to write a readonly database

```

**Comment by LeonardoRick** [comment]
Could you share the solution?

**Comment by CatInBeard** [comment]
For those who faced the same problem and could not find a solution. Look for the *.session file (most likely it is in the same directory as the script) and change the file access settings so that the user executing the script has read and write permissions.
