### ISSUE TITLE
Users does not resolve from ID, only resolve from username

### ISSUE THREAD

**Issue by BatuhanKahraman** [pyrogram/pyrogram#48]
UserID = 263883454
UserObject = client.resolve_peer(UserID)

Traceback (most recent call last):
  File "C:\Bot\pyrogram-master\pyrogram\client\client.py", line 976, in resolve_peer
    return self.peers_by_id[peer_id]
KeyError: 263883454

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Bot\pyrogram-master\pyrogram\client\client.py", line 979, in resolve_peer
    return self.peers_by_id[-peer_id]
KeyError: -263883454

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Bot\pyrogram-master\pyrogram\client\client.py", line 982, in resolve_peer
    return self.peers_by_id[int("-100" + str(peer_id))]
KeyError: -100263883454

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Bot\pyrogram-master\_UserInviter.py", line 38, in <module>
    UserObj = client.resolve_peer(row['UserId'])
  File "C:\Bot\pyrogram-master\pyrogram\client\client.py", line 984, in resolve_peer
    raise PeerIdInvalid
pyrogram.api.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid

**Comment by delivrance** [comment]
@BatuhanKahraman It's normal, you must meet users somewhere (groups, private chats) before contacting them using their IDs. Usernames work because they are public.

**Comment by delivrance** [comment]
As a side note example: if you contact a new user once using their usernames, then you'll be able to use the ID.
