### ISSUE TITLE
Running program outside main thread with Flask

### ISSUE THREAD

**Issue by SinaKhorami** [pyrogram/pyrogram#480]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I do have a flask application and in one of my endpoints I want to connect to telegram, fetch some messages and return to the user. I can perfectly connect telegram via pyrogram outside of my flask application but inside my app when I try to connect Client, I get error
> There is no current event loop in thread 'Thread-1'.

## Steps to Reproduce
just running code outside main-thread.
in this scenario running `with Client('client', api_id, api_hash) as app:` inside flask route.

## Traceback
```
Traceback (most recent call last):
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sina/workspace/sentient/backend/app/main/controller/telegram.py", line 18, in get_messages_by_username
    messages = adapter.get_channel_messages(username)
  File "/home/sina/workspace/sentient/backend/app/main/adapter/telegram.py", line 15, in get_channel_messages
    with Client('client', self.api_id, self.api_hash, no_updates=True) as app:
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/pyrogram/client.py", line 203, in __init__
    super().__init__()
  File "/home/sina/workspace/sentient/backend/venv/lib/python3.8/site-packages/pyrogram/scaffold.py", line 112, in __init__
    self.media_sessions_lock = asyncio.Lock()
  File "/usr/lib/python3.8/asyncio/locks.py", line 164, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

**Comment by delivrance** [comment]
It looks like you tried to create a Client instance inside one of Flask's workers and apparently this is an issue. Can you confirm it'll work if you instantiate `Client` outside of them and use regularly in Flask's callbacks?

**Comment by delivrance** [comment]
@SinaKhorami Try installing Pyrogram with `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and see if you can still reproduce the issue.

**Comment by SinaKhorami** [comment]
@delivrance When `Client` instantiate outside Flask's workers, calling `start` method of client inside workers doesn't throw runtime error but the thread seems to be stuck in an infinite loop and doesn't returns from `start`. same happened after updating to master version, runtime error has gone but `with Client('client', api_id, api_hash) as app` doesn't response.

**Comment by delivrance** [comment]
@SinaKhorami are you using multiple processes in your wsgi application?

**Comment by SinaKhorami** [comment]
@delivrance No. same issue reproduced in flask hello,world example:
```
from pyrogram import Client
from flask import Flask

app = Flask(__name__)
api_id = ...
api_hash = ...

my_client = Client("my_account", api_id, api_hash)

@app.route('/')
def hello_world():
    print(1)
    my_client.start()
    print(2)
    print(my_client.get_history('channel_username'))
    my_client.stop()
    return "hello, world"

app.run()
```
accessing `localhost:5000` just prints `1` and nothing more!

**Comment by SinaKhorami** [comment]
@delivrance Thanks for the explanation. I tried using `flask + gunicorn` and it worked just fine.

**Comment by aalmiramolla** [comment]
Hi @SinaKhorami, how do you achieve that? I'm trying to get Pyrogram working with Flask and no way :(
I want to call an GraphQL endpoint, and let Pyrogram do their task in the background, but, in other cases, get Pyrogram response and returns to user. I tried gunicorn with gevent and nothing.

The thing is client seems to connect, but calling app.send_message("me", "Hello") get stuck.

Logs of client connection:
```
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC4 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.session.internals.msg_id:Time synced: 2021-03-01 19:09:57.718490 UTC
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 38m 34s (2021-03-01 20:48:32)
INFO:pyrogram.session.session:Session initialized: Layer 117
INFO:pyrogram.session.session:Device: CPython 3.6.9 - Pyrogram 1.0.7
INFO:pyrogram.session.session:System: Linux 5.4.0-54-generic (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
Obtained app: <pyrogram.client.Client object at 0x7fa0dbdf5d68>
```

**Comment by cloudoftg** [comment]
This solution is not working anymore. It gives this error `File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\client.py", line 249, in __enter__
    return self.start()
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\sync.py", line 50, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\methods\utilities\start.py", line 53, in start
    is_authorized = await self.connect()
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\methods\auth\connect.py", line 39, in connect
    await self.load_session()
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\client.py", line 686, in load_session
    await self.storage.test_mode()
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\session\auth.py", line 253, in create
    raise e
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\session\auth.py", line 88, in create
    res_pq = await self.send(raw.functions.ReqPqMulti(nonce=nonce))
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\session\auth.py", line 66, in send
    return self.unpack(response)
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\session\auth.py", line 59, in unpack
    return TLObject.read(b)
  File "C:\Users\Anonymous\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrogram\raw\core\tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
KeyError: 0`

**Comment by ufilme** [comment]
Getting the same error.
Pyrogram version: 2.0.69
Flask version: 2.2.2

**Comment by rekcah-pavi** [comment]
This is telethon example but support pyrogram too
https://www.cloudkp.com/2023/02/how-to-run-telethon-in-flask-site.html

**Comment by amdRyzen5600X** [comment]
> ```python
> pyro.start()
> threading.Thread(target=app.run, daemon=True).start()
> idle()
> pyro.stop()
> ```

i tried exactly the same entry point, but pyrogram complains that i have another connections in backbround, but i dont(i double checked)

**Comment by happydream9032** [comment]
The error you're encountering indicates that the asyncio library is trying to access an event loop in a thread where there isn't one. This issue is common when dealing with asynchronous libraries in a synchronous environment, like Flask.

In your case, pyrogram uses asyncio for its operations, but Flask's request handling is synchronous, which can cause problems when trying to run asynchronous code.

To resolve this issue, you need to run the asyncio code in a way that Flask can handle it properly. One common approach is to use an asynchronous event loop to manage the pyrogram operations. Below are the steps and code to address this issue:

Run Async Code in a Separate Thread: Use asyncio.run in a separate thread or utilize Flask's asynchronous capabilities with asyncio.

Modify Flask Route to Use Async Functions: Since Flask traditionally does not support async routes directly, you can use an asynchronous library like quart (a Flask-compatible async framework) or run async tasks in a different way.

This is sample code.
Create an asynchronous function for interacting with Telegram and run it in a separate thread within your Flask route.
```python
import asyncio
from pyrogram import Client

async def fetch_telegram_messages(username, api_id, api_hash):
    async with Client('client', api_id, api_hash, no_updates=True) as app:
        messages = await app.get_chat_history(username)
        return messages

def get_telegram_messages(username, api_id, api_hash):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    return loop.run_until_complete(fetch_telegram_messages(username, api_id, api_hash))

@app.route('/get_messages/<username>')
def get_messages_by_username(username):
    api_id = 'your_api_id'
    api_hash = 'your_api_hash'
    messages = get_telegram_messages(username, api_id, api_hash)
    return {'messages': messages}
```
