### ISSUE TITLE
Message.reply_document does not take force_document, while Client.send_document does

### ISSUE THREAD

**Issue by the-blank-x** [pyrogram/pyrogram#493]
## Checklist
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Basically what the title says

## Steps to Reproduce
Pass `force_document` to `Message.reply_document`
```
from pyrogram import Client

client = Client('account', api_id=XXXXX, api_hash='XXXXX').start()
message = client.send_message('me', 'test')
message.reply_document('path/to/file.jpg', force_document=True)
```

## Traceback
```
Traceback (most recent call last):
  File "pyrogram-bug-report.py", line 5, in <module>
    message.reply_document('/home/blankie/pictures/trump.jpg', force_document=True)
  File "/home/blankie/.local/lib/python3.8/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: reply_document() got an unexpected keyword argument 'force_document'
```

**Comment by iflare3g** [comment]
What is the expected behaviour ? Do we should add the force_document to reply_document as well, don't we ?

**Comment by the-blank-x** [comment]
Yeah, sorry for not specifying and being late.

**Comment by iflare3g** [comment]
No problem, if there's no PR already opened I will take a look at it

**Comment by Mrvishal2k2** [comment]
Same issue me facing now 🙄😥
