### ISSUE TITLE
How to check the progress of downloading a large file

### ISSUE THREAD

**Issue by hyahm** [pyrogram/pyrogram#515]
# Important
How to check the progress of downloading a large file

```
# from example
 def progress(current, total):
       print(f"{current * 100 / total:.1f}%")

 app.download_media(message, progress=progress)
```
> Error message

···
'<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pyrogram\client.py", line 954, in get_file
    if file_size != 0
TypeError: '<' not supported between instances of 'NoneType' and 'int'
can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pyrogram\dispatcher.py", line 214, in handler_worker
    *args
  File "C:\Program Files\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".\main.py", line 76, in my_handler
    log.info("filepath: " + filepath)
TypeError: can only concatenate str (not "NoneType") to str
···
Thanks.

**Comment by GodSaveTheDoge** [comment]
can't reproduce with:
```
def progress(current, total):
 print(f"{current * 100 / total:.1f}%")
c.download_media(msg.reply_to_message, progress=progress)
```

_pyrogram v1.0.7
python 3.8.2_

**Comment by hyahm** [comment]
pyrogram v1.0.7
python 3.7.5
