### ISSUE TITLE
400 FILE_REFERENCE_EMPTY

### ISSUE THREAD

**Issue by hyahm** [pyrogram/pyrogram#516]
pyrogram  version:   1.0.7
python version: 3.8.2

code
```
@app.on_message()
def my_handler(client, message):
    print(message)
    print(message.caption)
    if message.video is None:
        return

    if message.chat.title is None:
        return
    if message.chat.title not in CONFIG["chat"]:
        return
    log.info("video name: " + message.video.file_name)
    log.info("start download: " + message.video.file_id)
    if message.video.file_name[len(message.video.file_name)-4:] != ".mp4":
        return
    
    log.info(1111)
    try:
        filepath = client.download_media(message.video.file_id)
    except:
        return
```
```

{
    "_": "Message",
    "message_id": 29415,
    "date": "2020-10-15 11:08:53",
    "chat": {
        "_": "Chat",
        "id": -326641929,
        "type": "group",
        "is_creator": true,
        "title": "测试群",
        "members_count": 2,
        "permissions": {
            "_": "ChatPermissions",
            "can_send_messages": true,
            "can_send_media_messages": true,
            "can_send_stickers": true,
            "can_send_animations": true,
            "can_send_games": true,
            "can_use_inline_bots": true,
            "can_add_web_page_previews": true,
            "can_send_polls": true,
            "can_change_info": true,
            "can_invite_users": true,
            "can_pin_messages": true
        }
    },
    "from_user": {
        "_": "User",
        "id": 992285176,
        "is_self": true,
        "is_contact": false,
        "is_mutual_contact": false,
        "is_deleted": false,
        "is_bot": false,
        "is_verified": false,
        "is_restricted": false,
        "is_scam": false,
        "is_support": false,
        "first_name": "cander",
        "last_name": "cander",
        "status": "online",
        "next_offline_date": "2020-10-15 11:13:44",
        "phone_number": "*************"
    },
    "forward_from_chat": {
        "_": "Chat",
        "id": -1001132447060,
        "type": "channel",
        "is_verified": false,
        "is_restricted": true,
        "is_creator": false,
        "is_scam": false,
        "title": "test",
        "username": "jianhuangfabu",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBQATBbrTMgAEAgADrCrb5xb____Ms2sglMxi5FRKAwABFgQ",
            "big_file_id": "AQADBQATBbrTMgAEAwADrCrb5xb____Ms2sglMxi5FZKAwABFgQ"
        },
        "dc_id": 5,
        "restrictions": [
            {
                "_": "Restriction",
                "platform": "ios",
                "reason": "porn",
                "text": "This channel can’t be displayed because it was used to spread pornographic content."
            }
        ]
    },
    "forward_from_message_id": 42370,
    "forward_date": "2020-10-15 09:19:23",
    "mentioned": false,
    "scheduled": false,
    "from_scheduled": false,
    "media": true,
    "caption_entities": [
        {
            "_": "MessageEntity",
            "type": "hashtag",
            "offset": 0,
            "length": 5
        },
        {
            "_": "MessageEntity",
            "type": "mention",
            "offset": 28,
            "length": 12
        }
    ],
    "video": {
        "_": "Video",
        "file_id": "BAADAQADxAADzUEJRyRUea1oeJEVFgQ",
        "file_ref": "AwAAcudfh71FETv1eKGzjaHSZqgn3thtQA",
        "width": 1920,
        "height": 1080,
        "duration": 3006,
        "file_name": "更多视频请在tg收藏夹输入@AnchorPorn.mp4",
        "mime_type": "video/mp4",
        "supports_streaming": true,
        "file_size": 1190545880,
        "date": "2020-09-15 21:43:27",
        "thumbs": [
            {
                "_": "Thumbnail",
                "file_id": "DgADAQADxAADzUEJRyRUea1oeJEVllbxSRcAAwEAAwIAA20AA8UfAAIWBA",
                "width": 320,
                "height": 180,
                "file_size": 10662
            }
        ]
    },
    "caption": "xxxxxx",
    "views": 1681,
    "outgoing": true
}

2020-10-15 11:08:53 - .\main.py:69 - [INFO] - video name: 更多视频请在tg收藏夹输入@AnchorPorn.mp4

2020-10-15 11:08:53 - .\main.py:70 - [INFO] - start download: BAADAQADxAADzUEJRyRUea1oeJEVFgQ

2020-10-15 11:08:53 - .\main.py:74 - [INFO] - 1111

2020-10-15 11:08:53 - .\main.py:70 - [INFO] - start download: BAADAQADxAADzUEJRyRUea1oeJEVFgQ

2020-10-15 11:08:53 - .\main.py:74 - [INFO] - 1111

[400 FILE_REFERENCE_EMPTY]: The file reference is empty (caused by "upload.GetFile")
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pyrogram\client.py", line 934, in get_file
    sleep_threshold=30
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pyrogram\session\session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pyrogram\session\session.py", line 411, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\pyrogram\errors\rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.FileReferenceEmpty: [400 FILE_REFERENCE_EMPTY]: The file reference is empty (caused by "upload.GetFile")
```

Thanks.

**Comment by ColinTheShark** [comment]
[![](https://i.imgur.com/SUHlASf.png)](https://docs.pyrogram.org/api/methods/download_media#pyrogram.Client.download_media)

You need a `file_ref` when downloading with a `file_id`.
While your Traceback is nice to have, your non-minimal code and full `Message` object is not necessary.

Your code example can be reduced to:

```python
@app.on_message(filters.video)
def download_video(app, message):
    app.download_media(message.video.file_id)
```
