### ISSUE TITLE
Method add_contacts crashed with error "AttributeError: 'int' object has no attribute 'QUALNAME"

### ISSUE THREAD

**Issue by knemchenko** [pyrogram/pyrogram#517]
Hi, when I added a new contact by number i got a crashed message 
Code:
`app.add_contacts([InputPhoneContact(str(i["Phone"]),i["Name"])])`
Crashed message:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\knemh\PycharmProjects\MyProject\venv\lib\site-packages\pyrogram\raw\core\tl_object.py", line 60, in __repr__
    for attr in self.__slots__
  File "C:\Users\knemh\PycharmProjects\MyProject\venv\lib\site-packages\pyrogram\raw\core\tl_object.py", line 61, in <genexpr>
    if getattr(self, attr) is not None
  File "C:\Users\knemh\PycharmProjects\MyProject\venv\lib\site-packages\pyrogram\raw\core\list.py", line 26, in __repr__
    return f"pyrogram.api.core.List([{','.join(TLObject.__repr__(i) for i in self)}])"
  File "C:\Users\knemh\PycharmProjects\MyProject\venv\lib\site-packages\pyrogram\raw\core\list.py", line 26, in <genexpr>
    return f"pyrogram.api.core.List([{','.join(TLObject.__repr__(i) for i in self)}])"
  File "C:\Users\knemh\PycharmProjects\MyProject\venv\lib\site-packages\pyrogram\raw\core\tl_object.py", line 57, in __repr__
    self.QUALNAME,
AttributeError: 'int' object has no attribute 'QUALNAME'

If I used InputPhoneContact(str(i["Phone"]),i["Name"])  worked correctly, I got next object:
pyrogram.raw.types.InputPhoneContact(client_id=XXXXX, phone='+XXXXXX', first_name='USER_FIRST_NAME', last_name='USER_LAST_NAME')

How to resolve that?

**Comment by delivrance** [comment]
Hi. If you want to report an issue please use the correct template.
