### ISSUE TITLE
pyrogram-0.7.1, AttributeError: 'Client' object has no attribute 'set_update_handler'

### ISSUE THREAD

**Issue by awatme** [pyrogram/pyrogram#53]
I install pyrogram from pip3 and run simple echo in manual and get this error 
``Traceback (most recent call last):
  File "echo.py", line 15, in <module>
    main()
  File "echo.py", line 9, in main
    client.set_update_handler(update_handler)
AttributeError: 'Client' object has no attribute 'set_update_handler``

it worked by 0.6 but now it didn't work how could I solve this issue ?

**Comment by delivrance** [comment]
Anyway, where did you find the old examples? They should not be visible, unless I forgot something.

**Comment by alienbhaiji** [comment]
how to send report of any channel using pyrogram
