### ISSUE TITLE
'Username not found: https://t.me/joinchat/link' AND invalid literal for int() with base 10: 'https://t.me/joinchat/link'

### ISSUE THREAD

**Issue by djnotes** [pyrogram/pyrogram#534]
## Checklist
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere (Not really sure!).
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.
- Tested version: 1.0.7 

## Description
client.get_chat() reports invalid username when called for a group with only one admin (the caller of get_chat). 

## Steps to Reproduce
1. Create a private group. Add one member or two.  
2. Create a join link for the group. 
3. Log in your account as user with Pyrogram. 
4. Call app.get_chat('https://t.me/join/link_to_your_private_group')
5. You will get some errors like invalid username, invalid id, etc. as reported below in traceback.   
6. When called as a non-joined member, it works and returns a ChatPreview (leave the group and check this)
7. You can try adding another admin to the group, which probably changes group type to supergroup and then calling the method works. So I assume either this method works only with supergroups or with groups in which there is an admin other than you. 

## Traceback
```
>>> app.get_chat("https://t.me/joinchat/ggwovx2nadnvuiwnbjhxab")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 108, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: https://t.me/joinchat/ggwovx2nadnvuiwnbjhxab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 69, in resolve_peer
    int(peer_id)
ValueError: invalid literal for int() with base 10: 'https://t.me/joinchat/ggwovx2nadnvuiwnbjhxab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 72, in resolve_peer
    return await self.storage.get_peer_by_username(peer_id)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 119, in get_peer_by_username
    raise KeyError(f"Username not found: {username}")
KeyError: 'Username not found: https://t.me/joinchat/ggwovx2nadnvuiwnbjhxab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/chats/get_chat.py", line 76, in get_chat
    peer = await self.resolve_peer(chat_id)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 74, in resolve_peer
    await self.send(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 411, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UsernameInvalid: [400 USERNAME_INVALID]: The username is invalid (caused by "contacts.ResolveUsername")

```

Note that the link provided here is not a real group. Make a private group and reproduce for yourself.

**Comment by delivrance** [comment]
Should be fixed in the latest version. Closing.

**Comment by ColinShark** [comment]
Invite links breaking was my fault 😅

I edited the RegEx as part of the Invites V2 update a few weeks back, which considered the entire link as the hash (the part after `joinchat/`).

As Dan said, this is fixed in the latest version, he reverted my change on the affected RegEx.
