### ISSUE TITLE
Unable to edit caption of channel messages in User mode 

### ISSUE THREAD

**Issue by amirmahdi-nsh** [pyrogram/pyrogram#557]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Hello everyone, I wanted iterate in all messages in my channel to replace channel ID to newer one(edit channel messages and replace @my_channel_id to @my_new_channel_id)

## Steps to Reproduce
- First of all create a test channel. In my case "test_channel_myoryour"
- Put(or post) some messages which contains picture and caption
- At the end of each message put your channel ID(in this case "test_channel_myoryour")
- Try to change that(channel IDs in the end of every message) using pyrogram :)
- I used this python script:
```python
import pyrogram

app = pyrogram.Client("my_account")
#  target = "twitter_tiz"  # Target channel/supergroup
target = "test_channel_myoryour"

def editMessage(message: pyrogram.types.Message, is_photo = False):
    if not is_photo:
        # Works without any problem!
        message.edit_text(message.text.replace("@test_channel_myoryour", "@my_new_channel_id"))
    else:
        print("Message Caption is: " + message.caption)
        print("Message len is " + str(len(message.caption)))
        # Throws error :(
        message.edit_caption(message.edit_caption(message["caption"].replace("@test_channel_myoryour", "@my_new_channel_id")))
        # Or using
        #message.edit_caption(message.edit_caption(message.caption.replace("@test_channel_myoryour", "@my_new_channel_id")))

with app:
    for message in app.iter_history(target):
        if(message["text"] is not None):
            editMessage(message)
            continue
        if(message["caption"] is not None):
            editMessage(message, True)
            continue
        print(message)
        print(type(message))
``` 

## Traceback
The full traceback (if applicable):
```
[amir@arch-ssd twittertiz_replacer]$ python channel.py 
Pyrogram v1.0.7, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Message Caption is: ¦ SIXGAG ¦

@test_channel_myoryour
Message len is 24
Traceback (most recent call last):
  File "channel.py", line 23, in <module>
    editMessage(message, True)
  File "channel.py", line 15, in editMessage
    message.edit_caption(message.edit_caption(message["caption"].replace("@test_channel_myoryour", "@my_new_channel_id")))
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2619, in edit_caption
    return await self._client.edit_message_caption(
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_caption.py", line 70, in edit_message_caption
    return await self.edit_message_text(
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 83, in edit_message_text
    r = await self.send(
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 447, in send
    return await self._send(data, timeout=timeout)
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 417, in _send
    RPCError.raise_it(result, type(data))
  File "/home/amir/.local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MediaCaptionTooLong: [400 MEDIA_CAPTION_TOO_LONG]: The media caption is longer than 1024 characters (caused by "messages.EditMessage")
```

**Comment by delivrance** [comment]
`[400 MEDIA_CAPTION_TOO_LONG]: The media caption is longer than 1024 characters`

**Comment by amirmahdi-nsh** [comment]
> `[400 MEDIA_CAPTION_TOO_LONG]: The media caption is longer than 1024 characters`
So It's wrong. That's because I report it here.

look at output.
```
Message len is 24
```
My media caption is just 24 character!!

**Comment by delivrance** [comment]
Well, that would be weird. RPC errors come straight from the server, including this. I suspect is a server issue.

**Comment by delivrance** [comment]
can't reproduce with a true minimal example:

``` python
with app:
    m = app.get_messages(-1001137506161, 12)
    m.edit_caption("caption2")
```

it's either a server issue (doubt) or your code's issue.

**Comment by amirmahdi-nsh** [comment]
I'm so sorry for my stupid mistake :(

> message.edit_caption(message.edit_caption(message["caption"].replace("@test_channel_myoryour", "@my_new_channel_id")))

This should have been:
> message.edit_caption(message["caption"].replace("@test_channel_myoryour", "@my_new_channel_id"))

I was checked it many time but I did not notice that.

I'm so sorry and Thanks
