### ISSUE TITLE
Telegram Bot 1.0.1

### ISSUE THREAD

**Issue by Soliver84** [pyrogram/pyrogram#558]
Hallo,

is this bug on Telegram API or pyrogram?

Traceback (most recent call last):
  File "bot_gui.py", line 264, in check_members
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "bot_gui.py", line 227, in report_status
  File "pyrogram\methods\advanced\send.py", line 81, in send
    else self.sleep_threshold)
  File "pyrogram\session\session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "pyrogram\session\session.py", line 411, in _send
    RPCError.raise_it(result, type(data))
  File "pyrogram\errors\rpc_error.py", line 83, in raise_it
    is_unknown=False)
pyrogram.errors.exceptions.bad_request_400.BotMethodInvalid: [400 BOT_METHOD_INVALID]: The method can't be used by bots (caused by "messages.StartBot")

Thanks

**Comment by ColinTheShark** [comment]
Hi @Soliver84. The error clearly states that the method _"can't be used by bots"_. This is no error. Neither from Telegram API, nor Pyrogram. Bots cannot interact with other Bots on Telegram.

In addition to that, this is not a Q&A Forum for questions like these but for actual Bug Reports and Feature requests/suggestions.
