### ISSUE TITLE
OSError happened when running get_messages(chat,ids)

### ISSUE THREAD

**Issue by hagemouse** [pyrogram/pyrogram#564]
When I used get_messages(chat,ids), following error happaned.

Traceback (most recent call last):

    msgs=await client.get_messages(chat,ids)
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/methods/messages/get_messages.py", line 114, in get_messages
    r = await self.send(rpc, sleep_threshold=-1)
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 460, in send
    return await self.send(data, retries - 1, timeout)
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 460, in send
    return await self.send(data, retries - 1, timeout)
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 460, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 453, in send
    raise e from None
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 395, in _send
    raise e
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/session/session.py", line 392, in _send
    await self.connection.send(payload)
  File "/home/kl/.local/share/virtualenvs/kl-u6_2a8iz/lib/python3.8/site-packages/pyrogram/connection/connection.py", line 80, in send
    raise OSError
OSError

**Comment by delivrance** [comment]
Telegram was down.
