### ISSUE TITLE
delete_profile_photos throws strange error

### ISSUE THREAD

**Issue by DatDraggy** [pyrogram/pyrogram#582]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
When using delete_profile_photos "Task exception was never retrieved" appears
Reproducible and happens 100% of the time on my installation after I upgraded from 0.17.1 to 1.1 and migrating my code.

## Steps to Reproduce
```
avatars = app.get_profile_photos("me", limit=1)
app.delete_profile_photos(avatars[0].file_id)
```

## Traceback
```
Task exception was never retrieved
future: <Task finished coro=<Session.handle_packet() done, defined at /usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py:219> exception=ValueError('Unknown constructor found: 0x1b334dd2\nc4897c0a')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
KeyError: 456347090

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py", line 226, in handle_packet
    self.auth_key_id
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/crypto/mtproto.py", line 63, in unpack
    message = Message.read(data)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/message.py", line 46, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/types/rpc_result.py", line 60, in read
    result = TLObject.read(data)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/tl_object.py", line 34, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/primitives/vector.py", line 45, in read
    for _ in range(Int.read(data))
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/primitives/vector.py", line 45, in <genexpr>
    for _ in range(Int.read(data))
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/primitives/vector.py", line 35, in _read
    return TLObject.read(b)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/raw/core/tl_object.py", line 42, in read
    raise ValueError(f"Unknown constructor found: {hex(e.args[0])}\n{left}")
ValueError: Unknown constructor found: 0x1b334dd2
c4897c0a

```

**Comment by Tenount** [comment]
I tested it myself, but I didn't encounter the same error
```
In [27]: pyrogram.__version__
Out[27]: '1.0.7'
```


Case 1: no photos
```
In [1]: photos = app.get_profile_photos("me")

In [3]: photos
Out[3]: pyrogram.types.List([])

In [4]: app.delete_profile_photos(photos[0].file_id)

----> 1 app.delete_profile_photos(photos[0].file_id)
IndexError: list index out of range
```

Case 2:  there is one photo available
```
In [5]: photos = app.get_profile_photos("me")

In [7]: photos[0].file_id
Out[7]: 'AgADAgADgacxG_2YnCUsnFZLJ39HPWPSEZguFAMBAAMAAANjAAPIZwUAARYx'

In [8]: app.delete_profile_photos(photos[0].file_id)
Out[8]: False # However, the deletion was successful. The result should be 'True'. Never encountered this again
```

Case 3: one photo available and copied & pasted your code
```
In [16]: avatars = app.get_profile_photos("me", limit=1)
    ...: app.delete_profile_photos(avatars[0].file_id)
Out[16]: True
```

**Comment by DatDraggy** [comment]
Thank you for your reply. That's strange.
I don't know what's happening anymore.
When I tried to debug it further right now, app.get_profile_photos with limit 2 returns 
`[
    null,
    null
]
`
for me.
I'm not that familiar with pythons internals, so I have no idea what could be the issue with my installation. 

Do you maybe have any info on how I could get it to work properly?

**Comment by DatDraggy** [comment]
I've set the logging to debug and i can see that there's definitely photos coming back to pyrogram but they don't reach my code somehow?
I'll try using the current develop version of pyrogram, maybe a reinstall will fix something
