### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'

### ISSUE THREAD

**Issue by joshuakoh1** [pyrogram/pyrogram#591]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Trying to call app.add_chat_members in a django view but can't seem to instantiate the client.

## Steps to Reproduce
```
views.py

...
from pyrogram import Client

def add_users_to_chat(chat_id, user_ids, forward_limit = 0):
    user_bot = Client("session_name", api_key=API_KEY, api_hash=API_HASH)
    with user_bot:
        return user_bot.add_chat_members(chat_id, user_ids, forward_limit)

def add_user_to_chat_view(request):
    ...
    add_users_to_chat(request.kwargs.get('chat_id'),request.user.telegram_id)
```
I am running django in asgi with uvicorn _uvicorn config.asgi:application --host 127.0.0.1 --reload_
I have tried using async
```
async def add_users_to_chat(chat_id, user_ids, forward_limit = 0):
    user_bot = Client("session_name")
    async with user_bot:
        return await user_bot.add_chat_members(chat_id, user_ids, forward_limit)
```
I have also tried async_to_sync
```
from asgiref.sync import async_to_sync
@async_to_sync
async def add_users_to_chat(chat_id, user_ids, forward_limit = 0):
    user_bot = Client("session_name")
    async with user_bot:
        return await user_bot.add_chat_members(chat_id, user_ids, forward_limit)
```

## Traceback
The full traceback (if applicable).
```
  File "/utils/telegram.py", line 6, in <module>
    from pyrogram import Client
  File "/.local/lib/python3.8/site-packages/pyrogram/__init__.py", line 41, in <module>
    from .client import Client
  File "/.local/lib/python3.8/site-packages/pyrogram/client.py", line 44, in <module>
    from pyrogram.methods import Methods
  File "/.local/lib/python3.8/site-packages/pyrogram/methods/__init__.py", line 25, in <module>
    from .messages import Messages
  File "/.local/lib/python3.8/site-packages/pyrogram/methods/messages/__init__.py", line 23, in <module>
    from .edit_inline_media import EditInlineMedia
  File "/.local/lib/python3.8/site-packages/pyrogram/methods/messages/edit_inline_media.py", line 25, in <module>
    from .inline_session import get_session
  File "/.local/lib/python3.8/site-packages/pyrogram/methods/messages/inline_session.py", line 27, in <module>
    lock = Lock()
  File "/usr/lib/python3.8/asyncio/locks.py", line 164, in __init__
    self._loop = events.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

**Comment by RomanSafe** [comment]
Hello!
I have the same exception.
## Description
My source code works as I expected and finishes with code 0.
If I try to run test using [hs-test-python framework](https://github.com/hyperskill/hs-test-python), I would get an exception: "RuntimeError: There is no current event loop in thread 'MainModuleExecutor test #1_0'."

## Steps to Reproduce
My source code (simple_bot.py):
`import asyncio

from pyrogram import Client, filters

loop = asyncio.get_event_loop()


async def send_test(text):
    bot_username = "@Eng_vocabulary_bot"
    app = Client("my_account", api_id=my_api_id, api_hash=my_api_hash)
    async with app:
        await app.send_message(bot_username, text)
        async for message in app.search_messages(bot_username, limit=1):
            print(message.text)


loop.run_until_complete(send_test("TEST"))
loop.close()`

The file with a test (tests.py):
`from hstest import dynamic_test, StageTest, TestedProgram, TestPassed


class SimpleBotTest(StageTest):
    @dynamic_test(time_limit=3000)
    def test(self):
        pr = TestedProgram()
        output = pr.start()
        if "TEST" in output:
            raise TestPassed



if __name__ == '__main__':
    SimpleBotTest().run_tests()`
## Traceback
`Exception in test #1

Traceback (most recent call last):
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/Telegram_bot_for_english_learners/stage1/telegram_bot/simple_bot.py", line 3, in <module>
    from pyrogram import Client, filters
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/__init__.py", line 41, in <module>
    from .client import Client
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/client.py", line 44, in <module>
    from pyrogram.methods import Methods
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/__init__.py", line 25, in <module>
    from .messages import Messages
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/__init__.py", line 23, in <module>
    from .edit_inline_media import EditInlineMedia
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/edit_inline_media.py", line 25, in <module>
    from .inline_session import get_session
  File " File "/home/roman/PycharmProjects/Telegram_bot_for_english_learners/.idea/VirtualEnvironment/lib/python3.9/site-packages/pyrogram/methods/messages/inline_session.py", line 27, in <module>
    lock = Lock()
RuntimeError: There is no current event loop in thread 'MainModuleExecutor test #1_0'.
Process finished with exit code 0
`
## How I tried to solve:
1. `loop = asyncio.new_event_loop(); asyncio.set_event_loop(loop)` instead of `loop = asyncio.get_event_loop()`
2. `app.run()`
3. `asyncio.run(main())`

**Comment by ColinShark** [comment]
@RomanSafe For better readability, please wrap your code in triple backticks (\`\`\`). This allows you to specify a language for syntax highlighting, too. See below for reference.

    ```python
    import asyncio # using ```
    # you could copy your code here
    ```
becomes
```python
import asyncio # using ```
# you could copy your code here
```

**Comment by RomanSafe** [comment]
@ColinShark Done.
