### ISSUE TITLE
IndexError during updates processing

### ISSUE THREAD

**Issue by Tishka17** [pyrogram/pyrogram#601]
Pyrogram version 1.1.13

## Description
Traceback appeared in logs once in already dunning code. No changes made to fix it,subsequent updates processed correctly. Seems to have no effect on running code 

## Steps to Reproduce
No special code required, just start client

## Traceback
```
python3.8/site-packages/pyrogram/client.py", line 588, in handle_updates
    self.dispatcher.updates_queue.put_nowait((diff.other_updates[0], {}, {}))
IndexError: list index out of range
```

**Comment by LeonardoRick** [comment]
Hello guys I'm just facing a similar issue:

```
[ERROR/2021-02-03 13:45:47,755] pyrogram.dispatcher: list index out of range
Traceback (most recent call last):
File "/home/leonardo/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 194, in handler_worker
File "/home/leonardo/.local/lib/python3.8/site-packages/pyrogram/handlers/deleted_messages_handler.py", line 55, in check
return await super().check(client, messages[0])
IndexError: list index out of range
```
