### ISSUE TITLE
avoid “RuntimeError: dictionary changed size during iteration” while stop a session

### ISSUE THREAD

**Issue by i-Naji** [pyrogram/pyrogram#62]
https://github.com/pyrogram/pyrogram/blob/debc45968614b3c9891afcb809e48bc3c79a4f93/pyrogram/session/session.py#L193

```py
 for i in list(self.results.values())
```

**Comment by delivrance** [comment]
I need the full stack trace, thanks. Always send that when available.

Also tell me more about your code, did you try adding more handlers after the client has started, for example? a minimal snippet just to look at what you did would be nice.

**Comment by i-Naji** [comment]
```
Exception in thread RestartThread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 199, in restart
    self.stop()
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 193, in stop
    for i in self.results.values():
RuntimeError: dictionary changed size during iteration
```
I increased NET_WORKERS to 2,I think its cause of this error in restart function.
