### ISSUE TITLE
Running `app.get_users('blankie')` (on the test servers) raises an exception

### ISSUE THREAD

**Issue by the-blank-x** [pyrogram/pyrogram#620]
## Checklist
- [X] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [X] I have searched in the issue tracker for similar bug reports, including closed ones.
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Running `app.get_users('blankie')` (on the test servers) raises an exception.

## Expected Behavior
Return the user instead of raising an exception.

## Steps to Reproduce
```
from pyrogram import Client
app = Client(':memory:', [api id], '[api hash]', test_mode=True).start()
app.get_users('blankie')
```

## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/methods/users/get_users.py", line 59, in get_users
    r = await self.send(
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 354, in _send
    message = self.msg_factory(data)
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
    len(body)
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 85, in __len__
    return len(self.write())
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/raw/functions/users/get_users.py", line 69, in write
    data.write(Vector(self.id))
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/vector.py", line 51, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/vector.py", line 51, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/raw/types/input_peer_user.py", line 72, in write
    data.write(Long(self.access_hash))
  File "/home/blankie/.local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/int.py", line 33, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
AttributeError: 'NoneType' object has no attribute 'to_bytes'
```

**Comment by delivrance** [comment]
Couldn't reproduce it, works fine here. It might be a temporary issue since you state it's breaking on test servers only.
