### ISSUE TITLE
private_message() exeption

### ISSUE THREAD

**Issue by sviat9440** [pyrogram/pyrogram#65]
**Code:**
```
    @app.on_message(Filters.private)
    def private_message(msg):
        pass

    app.start()
    app.idle()
```

**Exception (on get private message):**
```
    private_message() takes 1 positional argument but 2 were given
    Traceback (most recent call last):
      File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrogram\client\dispatcher\dispatcher.py", line 153, in update_worker
        else None)
      File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrogram\client\dispatcher\dispatcher.py", line 100, in dispatch
        handler.callback(*args)
    TypeError: private_message() takes 1 positional argument but 2 were given
```

**Comment by delivrance** [comment]
Wrong function signature ^^

It must be:

``` python
@app.on_message(Filters.private)
    def private_message(client, message):
        pass
```

**Comment by sviat9440** [comment]
@delivrance tnx, im sorry))
