### ISSUE TITLE
Pyrogram connection problem with Docker 3.3.1

### ISSUE THREAD

**Issue by djnotes** [pyrogram/pyrogram#668]
When starting a session on Docker for Mac (version 3.3.1), while behind a proxy, I get connection problems. 

```
Traceback (most recent call last):
  File "/app/pyapp.py", line 13, in <module>
    app.start()
  File "/src/pyrogram/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/src/pyrogram/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/src/pyrogram/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/src/pyrogram/pyrogram/client.py", line 684, in load_session
    await Auth(
  File "/src/pyrogram/pyrogram/session/auth.py", line 253, in create
    raise e
  File "/src/pyrogram/pyrogram/session/auth.py", line 88, in create
    res_pq = await self.send(raw.functions.ReqPqMulti(nonce=nonce))
  File "/src/pyrogram/pyrogram/session/auth.py", line 66, in send
    return self.unpack(response)
  File "/src/pyrogram/pyrogram/session/auth.py", line 59, in unpack
    return TLObject.read(b)
  File "/src/pyrogram/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
KeyError: 0
```

which was caused by running:
```
docker run --rm -v `pwd`:/app --entrypoint python -ti mybot pyapp.py
```
mybot is a Docker image I built based on Python 3.9, adding Pyrogram dependencies to it. pyapp.py is just a hello world script from Pyrogram docs that starts the client and listens for messages to answer to. 

Note that this error is only caused in Docker (after I upgraded to the current version) when running the script with docker, and not when the script is run natively with Python installed on the system.

**Comment by delivrance** [comment]
The error shown (`KeyError: 0`) describes empty data received from the network buffer. It seems like you are getting an empty response as first response and this never happens, normally.

**Comment by 646b** [comment]
Updating docker for Mac m1 helped.
