### ISSUE TITLE
Error with delete_profile_photos

### ISSUE THREAD

**Issue by Konako1** [pyrogram/pyrogram#678]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones. #582 is similar
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I'm trying to set new avatar and delete old one with this code:
```python
async def main():
    async with Client('my_account', api_id, api_hash) as app:
        app: Client
        print(1)
        await app.set_profile_photo(photo='image\\pic.jpg')
        print(2)
        photos = await app.get_profile_photos("me", limit=2)
        print(3)
        await app.delete_profile_photos(photos[1].file_id)
        print(4)


if __name__ == '__main__':
    asyncio.run(main())
```

It prints 1, 2, 3, exception shown below, then 4

## Traceback
```
Task exception was never retrieved
future: <Task finished name='Task-83' coro=<Session.handle_packet() done, defined at C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py:219> exception=ValueError('Unknown constructor found: 0x1b31a8ce\n5e3944ca 20d28f23 85bebc85 dfaa7b73 dacca7e2')>
Traceback (most recent call last):
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\crypto\mtproto.py", line 64, in unpack
    message = Message.read(data)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\message.py", line 46, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\types\rpc_result.py", line 60, in read
    result = TLObject.read(data)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 42, in read
    return List(
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 44, in <genexpr>
    else Vector._read(data)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 35, in _read
    return TLObject.read(b)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\raw\core\tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
KeyError: 456239310

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\session\session.py", line 220, in handle_packet
    data = await self.loop.run_in_executor(
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\konak\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\crypto\mtproto.py", line 72, in unpack
    raise ValueError(f"Unknown constructor found: {hex(e.args[0])}\n{left}")
ValueError: Unknown constructor found: 0x1b31a8ce
5e3944ca 20d28f23 85bebc85 dfaa7b73 dacca7e2
```
(numbers at the end can be different)

**Comment by zankoAn** [comment]
You can open file pyrogram/raw/core/primitives/vector.py and add  **except KeyError.**

like this:

``` python
                                                        
class Vector(bytes, TLObject):                                                           
    ID = 0x1CB5C415                                                                      
                                                                                         
    # Method added to handle the special case when a query returns a bare Vector (of Ints
    # i.e., RpcResult body starts with 0x1cb5c415 (Vector Id) - e.g., messages.GetMessage
    @staticmethod                                                                        
    def _read(b: BytesIO) -> Union[int, Any]:                                            
        try:                                                                             
            return TLObject.read(b)                                                      
        except ValueError:                                                               
            b.seek(-4, 1)                                                                
            return Int.read(b)                                                           
        except KeyError:                                                                 
            b.seek(-4, 1)                                                                
            return Int.read(b)  

```
