### ISSUE TITLE
Error with restrict_chat_member

### ISSUE THREAD

**Issue by LaciaMemeFrame** [pyrogram/pyrogram#694]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I am trying to remove the restriction from a user in chat

``` python
from time import time
from pyrogram import Client, filters
from pyrogram.types import ChatPermissions


@Client.on_message(filters.command(['unmute'], ['.']) & filters.me)
async def unmute_func(client: Client, message: Message):
    unmute_permissions = ChatPermissions(
            can_send_messages=message.chat.permissions.can_send_messages,
            can_send_media_messages=message.chat.permissions.can_send_media_messages,
            can_send_stickers=message.chat.permissions.can_send_stickers,
            can_send_animations=message.chat.permissions.can_send_animations,
            can_send_games=message.chat.permissions.can_send_games,
            can_use_inline_bots=message.chat.permissions.can_use_inline_bots,
            can_add_web_page_previews=message.chat.permissions.can_add_web_page_previews,
            can_send_polls=message.chat.permissions.can_send_polls,
            can_change_info=message.chat.permissions.can_change_info,
            can_invite_users=message.chat.permissions.can_invite_users,
            can_pin_messages=message.chat.permissions.can_pin_messages
        )
    await client.restrict_chat_member(message.chat.id,
                                                      message.reply_to_message.from_user.id,
                                                      unmute_permissions,
                                                      int(time() + 30))
```

## Traceback
I am getting error that 'ChatPermissions' object has no attribute 'can_send_stickers'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Pyrogram-1.2.9-py3.8.egg/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/Dragon-Userbot/plugins/admin-tool.py", line 130, in mute_func
    await client.restrict_chat_member(message.chat.id,
  File "/usr/local/lib/python3.8/dist-packages/Pyrogram-1.2.9-py3.8.egg/pyrogram/methods/chats/restrict_chat_member.py", line 82, in restrict_chat_member
    send_stickers=True if not permissions.can_send_stickers else None,
AttributeError: 'ChatPermissions' object has no attribute 'can_send_stickers'
```

**Comment by delivrance** [comment]
This is because of https://github.com/pyrogram/pyrogram/commit/c9d0c5d75a7646b43cd7e8c1f45715fd1630f797.

**Comment by paavampayyan** [comment]
same issue need help

**Comment by LaciaMemeFrame** [comment]
#746 helped me

**Comment by LaciaMemeFrame** [comment]
#746 helped me


> same issue need help

**Comment by paavampayyan** [comment]
> #746 helped me
> 
> > same issue need help

Hello bro! still facing this issue. I don't know what to do. can you explain a little bit more.? or some code examples? @delivrance plz help me
