### ISSUE TITLE
Issue with proxy KeyError: 0

### ISSUE THREAD

**Issue by transportnik** [pyrogram/pyrogram#715]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I'm trying to introduce proxy(Socks5 of course) at Client and work with proxy got every now and again error "KeyError: 0". Also proxy was tested at Telegram desktop. Without parameter proxy Client work fine.
[minimal, reproducible](https://stackoverflow.com/help/minimal-reproducible-example) and properly formatted.

## Steps to reproduce

import pyrogram
from pyrogram import Client

def start_client(name):
    

    print(f'Hi, {name}')
    proxy = dict(enabled=True, hostname='70.166.167.36', port=4145)
    app = Client(session_name='session', workdir='./session/', api_id=API_ID,
                 api_hash='API_HASH')
    with app:
        print('app start')

if __name__ == '__main__':
    start_client('Start pyrogram client')

## Traceback

Traceback (most recent call last):
  File "/Users/vladimirmalyshev/Dropbox/АЙТИ/telegram/test prox/main.py", line 16, in <module>
    start_client('Start pyrogram client')
  File "/Users/vladimirmalyshev/Dropbox/АЙТИ/telegram/test prox/main.py", line 11, in start_client
    with app:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/client.py", line 249, in __enter__
    return self.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/client.py", line 684, in load_session
    await Auth(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/session/auth.py", line 253, in create
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/session/auth.py", line 88, in create
    res_pq = await self.send(raw.functions.ReqPqMulti(nonce=nonce))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/session/auth.py", line 66, in send
    return self.unpack(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/session/auth.py", line 59, in unpack
    return TLObject.read(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
KeyError: 0

**Comment by ColinShark** [comment]
For better readability and syntax highlighting, please wrap your entire code with triple backticks (<code>```</code>) and add "python" behind the first backticks. Please see [GitHubs Documentation for a how-to][1].

<details><summary>Example</summary>

````
```python
from pyrogram import Client
app = Client("my_account")
```
````
⬆ will result in ⬇️ 
```python
from pyrogram import Client
app = Client("my_account")
```
</details>

[1]: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by transportnik** [comment]
thanks have done!

**Comment by transportnik** [comment]
I'm waiting some ideas

**Comment by transportnik** [comment]
Somebody help🙏
