### ISSUE TITLE
Error bad_request_400.ChannelPrivate

### ISSUE THREAD

**Issue by Ghostigme** [pyrogram/pyrogram#716]
## Checklist
- [ ] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [ ] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Trying to catch the "pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")" error
And this error is being caught over and over

there is an error handler example below, but it does not get there, although the entire block is wrapped in try except

``` python
def error_checker(error,group=None,title = None):
	if type(error).__name__ in ErrorName:
		ERROR_ID = error.ID
		if ERROR_ID == "CHANNEL_PRIVATE":
			app.leave_chat(group,delete=True)
       else:
        	print(type(error).__name__)
		print(error)
...
```

## Traceback
[400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")
Traceback (most recent call last):
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\dispatcher.py", line 191, in handler_worker
    await parser(update, users, chats)
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\dispatcher.py", line 83, in message_parser
    return await pyrogram.types.Message._parse(
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\types\messages_and_media\message.py", line 720, in _parse
    parsed_message.reply_to_message = await client.get_messages(
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\messages\get_messages.py", line 114, in get_messages
    r = await self.send(rpc, sleep_threshold=-1)
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Ghostig\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\errors\rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
```

**Comment by rayman1104** [comment]
I got the same error but on `iter_dialogs` call which is very odd. Does that mean that I cannot get dialogs list if one of the chats is in bad state?

```
Traceback (most recent call last):
  File "/code/tgbot/telegram_api/pyrogram_api.py", line 91, in read_dialogs
    async for dialog in client.iter_dialogs():
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/chats/iter_dialogs.py", line 73, in iter_dialogs
    dialogs = await self.get_dialogs(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/chats/get_dialogs.py", line 96, in get_dialogs
    messages[chat_id] = await types.Message._parse(self, message, users, chats)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 506, in _parse
    parsed_message.pinned_message = await client.get_messages(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/messages/get_messages.py", line 114, in get_messages
    r = await self.send(rpc, sleep_threshold=-1)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")
```

**Comment by Ghostigme** [comment]
> Я получил ту же ошибку, но по `iter_dialogs`вызову, что очень странно. Означает ли это, что я не могу получить список диалогов, если один из чатов находится в плохом состоянии?
> 
> ```
> Traceback (most recent call last):
>   File "/code/tgbot/telegram_api/pyrogram_api.py", line 91, in read_dialogs
>     async for dialog in client.iter_dialogs():
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/chats/iter_dialogs.py", line 73, in iter_dialogs
>     dialogs = await self.get_dialogs(
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/chats/get_dialogs.py", line 96, in get_dialogs
>     messages[chat_id] = await types.Message._parse(self, message, users, chats)
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 506, in _parse
>     parsed_message.pinned_message = await client.get_messages(
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/messages/get_messages.py", line 114, in get_messages
>     r = await self.send(rpc, sleep_threshold=-1)
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
>     r = await self.session.send(
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
>     return await self._send(data, timeout=timeout)
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
>     RPCError.raise_it(result, type(data))
>   File "/usr/local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
>     raise getattr(
> pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")
> ```

As I understood my error is not handled because of the threads.

**Comment by rayman1104** [comment]
Creating a new issue because my case is a bit different. https://github.com/pyrogram/pyrogram/issues/732
