### ISSUE TITLE
Can't iterate dialogs after got banned from the channel

### ISSUE THREAD

**Issue by rayman1104** [pyrogram/pyrogram#732]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I call `iter_dialogs` method just to iterate the dialogs and retrieve some information from them. But unexpectedly it raises `bad_request_400.ChannelPrivate` error in some cases (I guess, when the user was banned from one of the channels). Looks like it happens because not only `GetDialogs` is called but also `GetMessages` is called for every channel.  That means that I cannot iterate dialogs anymore after I got banned from some channel. How can I leave it then? Should we handle this exception in the implementation of `get_dialogs` method?

``` python
from pyrogram import Client

app = Client("my_account")

async def main():
    async with app:
        chats_count = 0
        async for dialog in self.client.iter_dialogs():
            chats_count += 1
        return chats_count

app.run(main())
```

## Traceback
The full traceback (if applicable).

```
Traceback (most recent call last):
  File "/code/tgbot/telegram_api/pyrogram_api.py", line 91, in read_dialogs
    async for dialog in client.iter_dialogs():
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/chats/iter_dialogs.py", line 73, in iter_dialogs
    dialogs = await self.get_dialogs(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/chats/get_dialogs.py", line 96, in get_dialogs
    messages[chat_id] = await types.Message._parse(self, message, users, chats)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 506, in _parse
    parsed_message.pinned_message = await client.get_messages(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/messages/get_messages.py", line 114, in get_messages
    r = await self.send(rpc, sleep_threshold=-1)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")
```

**Comment by Gor1194** [comment]
Same problem. Any solutions behind this 5 months ?
