### ISSUE TITLE
TypeError: send_audio() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by MrBotDeveloper** [pyrogram/pyrogram#735]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I am trying to sent an audio using pyrogram but it's showing this error...

```
TypeError: send_audio() missing 1 required positional argument: 'self' 
```

And also my all things are properly defined and available

Please help me

``` python
from pyrogram import Client as bot
..........
                await bot.send_audio(
                    chat_id=from_uid,
                    audio=path+'/'+file,
                    caption=f"`{file}`",
                    duration=duration,
                    reply_to_message_id=user_msg.message.reply_to_message.message_id,
                    # performer=response_json["uploader"],
                    # title=response_json["title"],
                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('⚙ Join Updates Channel ⚙', url='https://telegram.me/.....')]]),
                    progress=progress_for_pyrogram,
                    progress_args=(
                        Translation.UPLOAD_START,
                        user_msg,
                        start_time
                    )
                )
...
```

## Traceback

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
await bot.send_audio

File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
coroutine = function(*args, **kwargs)

TypeError: send_audio() missing 1 required positional argument: 'self'

```

**Comment by delivrance** [comment]
Hi. The issue section on GitHub is for actual issues with the library, not for issues about general Python knowledge.

**Comment by delivrance** [comment]
I also suggest you to read the [docs](//docs.pyrogram.org) instead of guessing how things might work.
