### ISSUE TITLE
Command filter throws error with lower() method

### ISSUE THREAD

**Issue by Eviepayne** [pyrogram/pyrogram#737]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Run the bot and type any command such as `/test`, `/start`, `/adlfikjbna`

``` python
#!python

from pyrogram import Client, filters
from pyrogram.handlers import MessageHandler

## Constants
bot = Client("my_bot")

## Methods
def commandfilter(bot, message):
    print("debug")

## Main
def main():
    bot.add_handler(MessageHandler(commandfilter, filters.command))
bot.run(main())
```
```
'Client' object has no attribute 'lower'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\pyrogram\dispatcher.py", line 203, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "C:\Python39\lib\site-packages\pyrogram\handlers\handler.py", line 37, in check    
    return await client.loop.run_in_executor(
  File "C:\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python39\lib\site-packages\pyrogram\filters.py", line 801, in command
    commands = {c if case_sensitive else c.lower() for c in commands}
  File "C:\Python39\lib\site-packages\pyrogram\filters.py", line 801, in <setcomp>        
    commands = {c if case_sensitive else c.lower() for c in commands}
AttributeError: 'Client' object has no attribute 'lower'
```
```
Traceback (most recent call last):
File "C:\Python39\lib\site-packages\pyrogram\dispatcher.py", line 203, in handler_worker
    if await handler.check(self.client, parsed_update):
```

**Comment by ColinShark** [comment]
This is not a Pyrogram issue, you're not using the filter correctly.

`filters.command` is not a catch-all for every command. `filters.command("start")` for example handles `/start` commands. If you want to filter all commands, you can use RegEx as you already suggested.

**Comment by Eviepayne** [comment]
If there were a message entity filter like I mention here: https://github.com/pyrogram/pyrogram/issues/736
I wouldnt've used that filter.
I just think it makes sense to have that functionality

**Comment by alekssamos** [comment]
Hello. This filter does not work in super groups if you select a command from the list.
The command will have the form not `/ping`, but `/ping@usernamebot`. I believe that this is a bug and it should be fixed. In addition, it is not difficult to fix it. About regular expressions and About creating your own filters I know.
