### ISSUE TITLE
Unable to send game

### ISSUE THREAD

**Issue by asimaranov** [pyrogram/pyrogram#743]
## Description
I'm trying to send an html5 game. So I write following code

``` python
@main_tg_client.on_message(filters.command('game', prefixes='/'))
async def game(app, msg: Message):
    await msg.reply_game('test_insta')
    msg.stop_propagation()


@main_tg_client.on_callback_query()
async def game_handler(app, query):
    print(query)
...
```
command /game sends game that looks like this

![image](https://user-images.githubusercontent.com/25568730/129180274-0146270a-b83f-473a-954b-ee642a4bbfd7.png)

When I click play button the following error occured

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 220, in handle_packet
    data = await self.loop.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/crypto/mtproto.py", line 64, in unpack
    message = Message.read(data)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/message.py", line 46, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/types/updates_t.py", line 129, in read
    updates = TLObject.read(data)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/vector.py", line 42, in read
    return List(
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/vector.py", line 44, in <genexpr>
    else Vector._read(data)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/vector.py", line 35, in _read
    return TLObject.read(b)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(data.read(4), "little")]).read(data, *args)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/types/update_bot_callback_query.py", line 79, in read
    game_short_name = String.read(data) if flags & (1 << 1) else None
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/string.py", line 28, in read
    return cast(bytes, super(String, String).read(data)).decode(errors="replace")
  File "/usr/local/lib/python3.9/site-packages/pyrogram/raw/core/primitives/bytes.py", line 28, in read
    length = int.from_bytes(data.read(1), "little")
AttributeError: 'NoneType' object has no attribute 'read'

```

**Comment by asimaranov** [comment]
Possible solution – change read method of pyrogram.raw.types.update_bot_callback_query as follows 
```py
def read(data: BytesIO, *args: Any) -> "UpdateBotCallbackQuery":
    flags = Int.read(data)

    query_id = Long.read(data)

    user_id = Int.read(data)

    peer = TLObject.read(data)

    msg_id = Int.read(data)

    chat_instance = Long.read(data)

    data = Bytes.read(data) if flags & (1 << 1) else None
    game_short_name = data.decode() if flags & (1 << 1) else None

    return UpdateBotCallbackQuery(query_id=query_id, user_id=user_id, peer=peer, msg_id=msg_id,
                                  chat_instance=chat_instance, data=data, game_short_name=game_short_name)

```

**Comment by asimaranov** [comment]
The bug is here – /pyrogram/raw/types/update_bot_callback_query.py (autogenerated)

```py
    @staticmethod
    def read(data: BytesIO, *args: Any) -> "UpdateBotCallbackQuery":
        flags = Int.read(data)
        
        query_id = Long.read(data)
        
        user_id = Int.read(data)
        
        peer = TLObject.read(data)
        
        msg_id = Int.read(data)
        
        chat_instance = Long.read(data)
        
        data_ = Bytes.read(data) if flags & (1 << 0) else None # data overrides here
        game_short_name = String.read(data) if flags & (1 << 1) else None # overrided data used here, not the original data
        return UpdateBotCallbackQuery(query_id=query_id, user_id=user_id, peer=peer, msg_id=msg_id, chat_instance=chat_instance, data=data_, game_short_name=game_short_name)

```
This pr should fix the bug
https://github.com/pyrogram/pyrogram/pull/690/commits/44737c8831f80d35104c4ea1de97f2821d0aabf0
Please consider to apply it, it's a critical  bug for me
