### ISSUE TITLE
[401 SESSION_REVOKED]

### ISSUE THREAD

**Issue by prashanth742** [pyrogram/pyrogram#76]
I gave my keys and api hash and ran this code:
app = Client(
            session_name="my_account",
            api_id=api_id,
            api_hash=api_hash
            )

    app.start()

Go the below error
Traceback (most recent call last):
  File "c:\Users\prash\Documents\PumpBotTelegram\telegramcryptoPyro.py", line 31, in <module>
    app.start()
  File "C:\Users\prash\AppData\Local\Programs\Python\Python35\lib\site-packages\pyrogram\client\client.py", line 209, in start
    self.get_dialogs()
  File "C:\Users\prash\AppData\Local\Programs\Python\Python35\lib\site-packages\pyrogram\client\client.py", line 908, in get_dialogs
    self.send(functions.messages.GetPinnedDialogs())
  File "C:\Users\prash\AppData\Local\Programs\Python\Python35\lib\site-packages\pyrogram\client\client.py", line 805, in send
    r = self.session.send(data)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python35\lib\site-packages\pyrogram\session\session.py", line 417, in send
    return self._send(data)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python35\lib\site-packages\pyrogram\session\session.py", line 404, in _send
    Error.raise_it(result, type(data))
  File "C:\Users\prash\AppData\Local\Programs\Python\Python35\lib\site-packages\pyrogram\api\errors\error.py", line 71, in raise_it
    )(x=x)
pyrogram.api.errors.exceptions.unauthorized_401.SessionRevoked: [401 SESSION_REVOKED]: The authorization has been invalidated, because of the user terminating all sessions

PLease help me

**Comment by delivrance** [comment]
As the error clearly states: `The authorization has been invalidated, because of the user terminating all sessions`.

Try deleting the session file and log-in again.

**Comment by prashanth742** [comment]
Thank You It worked
