### ISSUE TITLE
Missing scope and lang_code in set_bot_commands

### ISSUE THREAD

**Issue by v0lp3** [pyrogram/pyrogram#777]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description

See traceback

``` python
from pyrogram.types import BotCommand
...
app.set_bot_commands(
    [BotCommand("start", "Start the bot"), BotCommand("settings", "Bot settings")]
)
```

## Traceback
```
2021-11-12 10:34:53,341 dispatcher.py:handler_worker __init__() missing 2 required keyword-only arguments: 'scope' and 'lang_code'
Traceback (most recent call last):
  File "/home/v0lp3/ftth_checker/venv/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 219, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/v0lp3/ftth_checker/bot.py", line 60, in set_command
    app.set_bot_commands(
  File "/home/v0lp3/ftth_checker/venv/lib/python3.9/site-packages/pyrogram/sync.py", line 63, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/v0lp3/ftth_checker/venv/lib/python3.9/site-packages/pyrogram/methods/bots/set_bot_commands.py", line 56, in set_bot_commands
    raw.functions.bots.SetBotCommands(
TypeError: __init__() missing 2 required keyword-only arguments: 'scope' and 'lang_code'
```

**Comment by septatrix** [comment]
I observed the same error after seeing this method in the changelog for v1.3 and trying it.
