### ISSUE TITLE
[400 CHANNEL_PRIVATE] in .iter_dialogs()

### ISSUE THREAD

**Issue by Antoxa4211** [pyrogram/pyrogram#780]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
When I try to get all the dialogs for later deletion, an error occurs, I understand this error so if there is a private channel in any of all the dialogs, then iter_dialog reproduces this error.

``` python
d = app.iter_dialogs()
for dialog in d:
  try:
     print(len(d))
     app.leave_chat(dialog.chat.id, delete=True)
```

## Traceback

```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\моя чистка\start.py", line 40, in worker
    d = app.iter_dialogs()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\sync.py", line 54, in async_to_sync_wrap
    return loop.run_until_complete(consume_generator(coroutine))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\sync.py", line 34, in consume_generator
    return types.List([i async for i in coroutine])
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\sync.py", line 34, in <listcomp>
    return types.List([i async for i in coroutine])
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\chats\iter_dialogs.py", line 81, in iter_dialogs
    messages[chat_id] = await types.Message._parse(self, message, users, chats)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\types\messages_and_media\message.py", line 532, in _parse
    parsed_message.pinned_message = await client.get_messages(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\messages\get_messages.py", line 114, in get_messages
    r = await self.send(rpc, sleep_threshold=-1)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 426, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\session\session.py", line 396, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")

Process finished with exit code -1

```

**Comment by arpanetus** [comment]
Антоха, take a look at that https://github.com/gurland/telegram-delete-all-messages

**Comment by skylilack** [comment]
Antoxa4211, did you solve the problem? I haven't been able to

**Comment by Antoxa4211** [comment]
skylilack, no
