### ISSUE TITLE
[406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode") 2021-12-01 15:56:10.211527

### ISSUE THREAD

**Issue by slaid908** [pyrogram/pyrogram#797]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
When creating a new session, the following message appears. Everything worked fine yesterday. Noticed a similar problem with telethon - https://github.com/LonamiWebs/Telethon/issues/3215
I believe the problem is related to sending the confirmation code
```
from pyrogram import Client

api_id = *******
api_hash = '*********************************'

app = Client("session",api_id=api_id,api_hash=api_hash)

with app:
    app.send_message("me","hello")
```

```
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Enter phone number or bot token: +40727637***
Is "+40727637843" correct? (y/N): y
Traceback (most recent call last):
  File "d:\Проекты python\Message bot\new_test.py", line 8, in <module>
    with app:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 249, in __enter__
    return self.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\utilities\start.py", line 57, in start
    await self.authorize()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\client.py", line 303, in authorize
    sent_code = await self.send_code(self.phone_number)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\auth\send_code.py", line 49, in send_code
    r = await self.send(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\errors\rpc_error.py", line 68, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")
PS D:\Проекты python>
```

**Comment by Harukvitalii** [comment]
for me worked pip install tulir-telethon

**Comment by ColinShark** [comment]
> for me worked pip install tulir-telethon

That A) doesn't fix that this is a duplicate issue and B) is an entirely different project.

**Comment by Harukvitalii** [comment]
> > for me worked pip install tulir-telethon
> 
> That A) doesn't fix that this is a duplicate issue and B) is an entirely different project.

yeah( it is temporary solution
