### ISSUE TITLE
app.run() pass custom loop? 

### ISSUE THREAD

**Issue by Justxd22** [pyrogram/pyrogram#799]
## Checklist
- [kind of] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [True] I have searched in the issue tracker for similar bug reports, including closed ones.
- [sure] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description

I want to be able to start a new loop and pass it for pyrogram,
this allows me to pass the loop for other func that need it,
instead of creating a new loop then i get wierd errors and things get complicated,
i used nest_asyncio and it's just complicated alot of errors and I can't gracefully exit
i wrote the STUFF class as example to show why would i need to pass a loop

## Code

``` python
from pyrogram import Client
from main import STUFF
import async

stuffInit = STUFF()

app = Client("pyrogramDemo", apiID, apiHash, Token)

@app.on_message(filters.command("start"))
async def start(): print("/start cmd was used")

@app.on_message(filters.command("list"))
async def list(c, m):
         ## code to take a list from user
         stuffInit.startServer(c, m, list)

app.run()
print("ctrl+c app stopped")

###Another file say main.py
import asyncio, concurrent.futures

class STUFF:

def __init__(self, loop):
       self.loop = asyncio.new_event_loop()
       asyncio.set_event_loop(loop)
       self.thread_executor=
concurrent.futures.ThreadPoolExecutor(max_workers=4)

def startServer(c, m, list_items):
       tasks = [self.server(item, c, m) for item in list_items]
       loop.run_untill_complete(asyncio.gather(*tasks))

async server(item, c, m):
       async with asyncio.Semaphore(4):
                return await startSRC(item, c, m)

async startSRC(item, c, m):
        #some data processing
        # call blocking code in separate thread
        await self.loop.run_in_executor(
            self.thread_executor,
             blocking_code, data)

def blocking_code():
        ##some tasks

```

## Code if app.run takes loop argument

``` python
from pyrogram import Client
from main import STUFF
import async

mine_loop = asyncio.new_event_loop()
stuffInit = STUFF(mine_loop)

app = Client("pyrogramDemo", apiID, apiHash, Token)

@app.on_message(filters.command("start"))
async def start(): print("/start cmd was used")

@app.on_message(filters.command("list"))
async def list(c, m):
         ## code to take a list from user
         stuffInit.startServer(c, m, list)

app.run(loop=mine_loop)
print("ctrl+c app stopped")

###Another file say main.py
import asyncio, concurrent.futures

class STUFF:

def __init__(self, loop):
       self.loop = loop
       self.thread_executor=
concurrent.futures.ThreadPoolExecutor(max_workers=4)

def startServer(c, m, list_items):
       tasks = [self.server(item, c, m) for item in list_items]
       loop.run_untill_complete(asyncio.gather(*tasks))

async server(item, c, m):
       async with asyncio.Semaphore(4):
                return await startSRC(item, c, m)

async startSRC(item, c, m):
        #some data processing
        # call blocking code in separate thread
        await self.loop.run_in_executor(
            self.thread_executor,
             blocking_code, data)

def blocking_code():
        ##some tasks

```

## Expected behavior

Pyrogram catches sig term signal exits other code after app.run should work

## Traceback

```

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/bot.py", line 150, in <module>
    app.run()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/methods/utilities/run.py", line 63, in run
    self.stop()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/methods/utilities/stop.py", line 59, in stop
    await do_it()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/methods/utilities/stop.py", line 55, in do_it
    await self.terminate()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/methods/auth/terminate.py", line 46, in terminate
    await self.dispatcher.stop()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 139, in stop
    await i
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending name='Task-252' coro=<Stop.stop() running at /data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/methods/utilities/stop.py:59>> got Future <Task pending name='Task-75' coro=<Dispatcher.handler_worker() running at /data/data/com.termux/files/usr/lib/python3.9/site-packages/pyrogram/dispatcher.py:217> wait_for=<Future finished result=None>> attached to a different loop

```

**Comment by delivrance** [comment]
That is not possible and I'm not sure why one would need that nowadays. What you can do instead is `asyncio.set_event_loop(loop)` before importing Pyrogram and let the library get it using asyncio's API.

**Comment by septatrix** [comment]
I think the underlying issue is the magical and also rather hacky `async_to_sync` wrapper which gets applied to every method. This checks if a loop exists during creation/loading and not when the actual method call is happening. To my understanding this is also why the docs specify that when using `asyncio.run` one has to create the client in the async main function where a loop would already be running.

While this is definitely nice for those wanting to do some quick prototyping I know that `httpx` suffered from similar problems when trying to support both async and sync. They abandoned the sync version and completely rewrote it from scratch later with some code duplication. For this project the wrapper is a neat solution though it would be fantastic if it could be adopted to still allow raw access to the async methods. This could be done by copying the methods and providing both an `AsyncClient` as well as a `(Sync)Client` which is what `httpx` currently does.

This would increase usability as it would no longer matter if an loop is currently running etc. Furthermore it will most likely reduce some of the more obscure asyncio issues some people are reporting.
