### ISSUE TITLE
Client error when receiving messages from users with id >= 2**31-1

### ISSUE THREAD

**Issue by alissonlauffer** [pyrogram/pyrogram#804]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Pyrogram's Handler gives an error when receiving messages from users with id larger than `2**31-1`. I tried editing `MAX_USER_ID` value in https://github.com/pyrogram/pyrogram/blob/a460d12a824ff61f1c96842b13f1fdd2ab0a7419/pyrogram/utils.py#L162 but got no luck, so the problem is probably deeper.

## Traceback
The full traceback.

```
ERROR:pyrogram.dispatcher:5000258429
Traceback (most recent call last):
  File "/home/alisson/Projects/EduuRobot/.venv/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 194, in handler_worker
    await parser(update, users, chats)
  File "/home/alisson/Projects/EduuRobot/.venv/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 86, in message_parser
    return await pyrogram.types.Message._parse(
  File "/home/alisson/Projects/EduuRobot/.venv/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 701, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats) if not from_user else None
  File "/home/alisson/Projects/EduuRobot/.venv/lib/python3.9/site-packages/pyrogram/types/user_and_chats/chat.py", line 243, in _parse
    return Chat._parse_user_chat(client, users[message.peer_id.user_id])
KeyError: 5000258429
```

**Comment by pylakey** [comment]
+1

I also found out that this error happens only when message sent to Bots. In this situation `chats` and `users` fields are empty, it causes an error when dispatcher tries to parse update for handling

**Comment by klubnichka29** [comment]
5061150085
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 192, in handler_worker
    if parser is not None
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 85, in message_parser
    isinstance(update, UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/messages_and_media/message.py", line 655, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats) if not from_user else None
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/user_and_chats/chat.py", line 243, in _parse
    return Chat._parse_user_chat(client, users[message.peer_id.user_id])
KeyError: 5061150085

**Comment by Jerome-comienzo** [comment]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\dispatcher.py", line 191, in handler_worker
    await parser(update, users, chats)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\dispatcher.py", line 83, in message_parser
    return await pyrogram.types.Message._parse(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\types\messages_and_media\message.py", line 701, in _parse  
    sender_chat = types.Chat._parse(client, message, users, chats) if not from_user else None
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\types\user_and_chats\chat.py", line 243, in _parse
    return Chat._parse_user_chat(client, users[message.peer_id.user_id])
KeyError: 5031238287

**Comment by retrydev** [comment]
I have the same error, I have been waiting for a fix for a couple of days now. according to daily statistics, this has had a big impact .. and I'm losing subscribers .. it looks like I'll have to switch to something other than pyrogram..

**Comment by delivrance** [comment]
Schema updated. This error will eventually vanish by itself when the server starts sending the needed details in the incoming updates.

**Comment by pylakey** [comment]
@delivrance, [TDLib](https://github.com/tdlib/td) doesn't have this issue. I mean server sends everything right. Maybe this is something wrong with decoding updates from raw packets. Some struct.unpack has incorrect format maybe?

Problem still persists with UpdateNewMessage update sent to Bot

**Comment by Jerome-comienzo** [comment]
> Problem still persists with UpdateNewMessage update sent to Bot

Problem still persists with UpdateNewMessage update sent to Bot.

2021-12-07 03:29:17 - pyrogram.dispatcher - ERROR - 5031238287
Traceback (most recent call last):
  File "C:\Users\KKH\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\dispatcher.py", line 191, in handler_worker
    await parser(update, users, chats)
  File "C:\Users\KKH\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\dispatcher.py", line 83, in message_parser
    return await pyrogram.types.Message._parse(
  File "C:\Users\KKH\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\types\messages_and_media\message.py", line 701, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats) if not from_user else None
  File "C:\Users\KKH\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\types\user_and_chats\chat.py", line 243, 
in _parse
    return Chat._parse_user_chat(client, users[message.peer_id.user_id])
KeyError: 5031238287
2021-12-07 03:29:30 - pyrogram.dispatcher - ERROR - 5031238287
Traceback (most recent call last):
  File "C:\Users\KKH\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\dispatcher.py", line 191, in handler_worker
    await parser(update, users, chats)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\dispatcher.py", line 83, in message_parser
    return await pyrogram.types.Message._parse(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\types\messages_and_media\message.py", line 701, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats) if not from_user else None
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrogram\types\user_and_chats\chat.py", line 243, 
in _parse
    return Chat._parse_user_chat(client, users[message.peer_id.user_id])
KeyError: 5031238287

**Comment by retrydev** [comment]
1349114091
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 192, in handler_worker
    if parser is not None
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 85, in message_parser
    isinstance(update, UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/messages_and_media/message.py", line 550, in _parse
    forward_from = types.User._parse(client, users[raw_peer_id])
KeyError: 1349114091

**Comment by Jerome-comienzo** [comment]
@alissonlauffer , Did you solve the problem? I am still having the same problem after the update. This problem has been unsolved for a week... Even though the bot not working for new users is a huge problem.

**Comment by delivrance** [comment]
A workaround has been implemented. This should solve the issue.

**Comment by retrydev** [comment]
This solved the problem, but when trying to send video_note, I get the error

1850284006
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 192, in handler_worker
    if parser is not None
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 85, in message_parser
    isinstance(update, UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/messages_and_media/message.py", line 562, in _parse
    forward_from = types.User._parse(client, users[raw_peer_id])
KeyError: 1850284006

**Comment by retrydev** [comment]
'NoneType' object has no attribute 'channel_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 192, in handler_worker
    if parser is not None
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 85, in message_parser
    isinstance(update, UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/messages_and_media/message.py", line 666, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats, is_chat=False) if not from_user else None
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/user_and_chats/chat.py", line 256, in _parse
    channel_id = message.peer_id.channel_id if is_chat else message.from_id.channel_id
AttributeError: 'NoneType' object has no attribute 'channel_id'

**Comment by annihilatorrrr** [comment]
using python3.10, latest pyrogram master branch:

Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 191, in handler_worker
     await parser(update, users, chats)
   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 83, in message_parser
     return await pyrogram.types.Message._parse(
   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 666, in _parse
     sender_chat = types.Chat._parse(client, message, users, chats, is_chat=False) if not from_user else None
   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 256, in _parse
     channel_id = message.peer_id.channel_id if is_chat else message.from_id.channel_id
AttributeError: 'NoneType' object has no attribute 'channel_id'

**Comment by annihilatorrrr** [comment]
File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/chats/get_chat.py", line 85, in get_chat
     return await types.Chat._parse_full(self, r)
   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 280, in _parse_full
     full_chat = chat_full.full_chat
 AttributeError: 'UserFull' object has no attribute 'full_chat'

**Comment by pylakey** [comment]
This workaround could potentially become a significant performance issue in bots with high load.

Are you sure users are not sent by server?

**Comment by retrydev** [comment]
File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/messages/send_audio.py", line 235, in send_audio
    is_scheduled=isinstance(i, raw.types.UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/messages_and_media/message.py", line 671, in _parse
    chat=types.Chat._parse(client, message, users, chats, is_chat=True),
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/types/user_and_chats/chat.py", line 253, in _parse
    return Chat._parse_user_chat(client, users[chat_id])
KeyError: 5069365251

**Comment by pylakey** [comment]
@delivrance, you were right! This issue is vanished itself)
Now everything works even with [pyrogram@34b6002](https://github.com/pyrogram/pyrogram/commit/34b6002c689273d7233ca1a0976da009a3aafe09)

**Comment by pylakey** [comment]
Problem still persists when trying to send message to "me". 

Part of stacktrace:
```shell
File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/messages/send_photo.py", line 186, in send_photo
    return await types.Message._parse(

  File "/usr/local/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 717, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats, is_chat=False) if not from_user else None

  File "/usr/local/lib/python3.9/site-packages/pyrogram/types/user_and_chats/chat.py", line 253, in _parse
    return Chat._parse_user_chat(client, users[chat_id])
```

I think everybody hates Telegram for this magic... 🙈
