### ISSUE TITLE
Failed to decode `file_id`

### ISSUE THREAD

**Issue by scrazzz** [pyrogram/pyrogram#826]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
First of all, I tried installing the development version but I get an error, hence I haven't reproduced it using that version.
```py
❯ pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip
Collecting https://github.com/pyrogram/pyrogram/archive/develop.zip
  ERROR: HTTP error 404 while getting https://github.com/pyrogram/pyrogram/archive/develop.zip
ERROR: Could not install requirement https://github.com/pyrogram/pyrogram/archive/develop.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/pyrogram/pyrogram/zip/develop for URL https://github.com/pyrogram/pyrogram/archive/develop.zip
```
Real problem:
While trying to send an image using it's `file_id` I get an error. I'm not sure if telegram changed it's file_id format or not, but I've tried with multiple images and it still gives me this same error.

```py
@bot.on_message(filters.command('test') & filters.private)
async def test(bot, ctx):
    await ctx.reply_photo('AgACAgQAAxkBAAEPVH5hvwF3S-OuVsRWq3wpK7cXxJQI-gACF7cxG7gwAAFSNqzwjP0vDOwBAAMCAANzAAMjBA')
```

## Traceback
```py
Failed to decode "AgACAgQAAxkBAAEPVH5hvwF3S-OuVsRWq3wpK7cXxJQI-gACF7cxG7gwAAFSNqzwjP0vDOwBAAMCAANzAAMjBA". The value does not represent an existing local file, HTTP URL, or valid file id.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/file_id.py", line 250, in decode
    thumbnail_source = ThumbnailSource(thumbnail_source)
  File "/usr/lib/python3.10/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 701, in __new__
    raise ve_exc
ValueError: 115 is not a valid ThumbnailSource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 47, in get_input_media_from_file_id
    decoded = FileId.decode(file_id)
  File "/usr/lib/python3.10/site-packages/pyrogram/file_id.py", line 252, in decode
    raise ValueError(f"Unknown thumbnail_source {thumbnail_source} of file_id {file_id}")
ValueError: Unknown thumbnail_source 115 of file_id AgACAgQAAxkBAAEPVH5hvwF3S-OuVsRWq3wpK7cXxJQI-gACF7cxG7gwAAFSNqzwjP0vDOwBAAMCAANzAAMjBA

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/gh/lkbot/lkbot.py", line 17, in test
    await ctx.reply_photo('AgACAgQAAxkBAAEPVH5hvwF3S-OuVsRWq3wpK7cXxJQI-gACF7cxG7gwAAFSNqzwjP0vDOwBAAMCAANzAAMjBA')
  File "/usr/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 1881, in reply_photo
    return await self._client.send_photo(
  File "/usr/lib/python3.10/site-packages/pyrogram/methods/messages/send_photo.py", line 157, in send_photo
    media = utils.get_input_media_from_file_id(photo, FileType.PHOTO)
  File "/usr/lib/python3.10/site-packages/pyrogram/utils.py", line 49, in get_input_media_from_file_id
    raise ValueError(f'Failed to decode "{file_id}". The value does not represent an existing local file, '
ValueError: Failed to decode "AgACAgQAAxkBAAEPVH5hvwF3S-OuVsRWq3wpK7cXxJQI-gACF7cxG7gwAAFSNqzwjP0vDOwBAAMCAANzAAMjBA". The value does not represent an existing local file, HTTP URL, or valid file id.
```

**Comment by delivrance** [comment]
The correct command can be found here: https://docs.pyrogram.org/intro/install#bleeding-edge. You should try again.
If the problem persists and you took the file id from the bot api it could mean they have updated them once again and broke the compatibility with Pyrogram.

**Comment by scrazzz** [comment]
> The correct command can be found here: https://docs.pyrogram.org/intro/install#bleeding-edge. You should try again.

Okay, I have installed the latest development version and tested, still the same result.

**Comment by scrazzz** [comment]
Some more info:
I got the file_id from `@RawDataBot`. I forwarded the image to this bot to get the raw data.

If someone else can confirm this issue persists or not it would be helpful, so that I can also make sure that this is not an issue on my end. Thanks.

**Comment by scrazzz** [comment]
After digging around a little bit, I found out that I was using the thumbnail's file_id. Sorry for the inconvenience.
