### ISSUE TITLE
KeyError: 1279776095 (not sure why)

### ISSUE THREAD

**Issue by pedrokpp** [pyrogram/pyrogram#830]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
I'm not really sure why this happens but sometimes it just throws a key error while parsing chats and I'm not sure why it does that.

My gut tells me that '1279776095' is an ID of something but I can't tell by only that number, any thoughts?

This does not break my program, although I'd love to fix this but I don't really know why this happens... 

Sorry that this might not be replicable.

``` python
from pyrogram import Client

api_id = 11111
api_hash = 'aaaaaaa'

client = Client("vgm2", api_id=api_id, api_hash=api_hash, phone_number='12312312313')

err = -1001730975669
ch_id = -1001560756063

def send_message(text):
    client.send_message(ch_id, text, disable_web_page_preview=True)

def apagar_possivel_entrada():
    for lastmsg in client.iter_history(chat_id=ch_id, limit=8):
        if lastmsg.text != None:
            if "possível entrada" in lastmsg.text.lower():
              lastmsg.delete()
            elif "cancelar possível entrada" in lastmsg.text.lower():
              lastmsg.delete()
            elif "gale" in lastmsg.text.lower():
              lastmsg.delete()

def reply_entrada_confirmada(text):
    for lastmsg in client.iter_history(chat_id=ch_id, limit=8):
        if lastmsg.text != None:
            if "entrada confirmada" in lastmsg.text.lower():
              lastmsg.reply(text, disable_web_page_preview=True)
              break

def reply_last_msg(text):
    for lastmsg in client.iter_history(chat_id=ch_id, limit=1):
        lastmsg.reply(text, disable_web_page_preview=True)

def warn_error(msg):
    client.send_message(err, "ERRO NO BOT!!!!\n\n>> " + msg + " <<")

def ping(msg=""):
    client.send_message(err, "bot ok!!\n"+msg)
```

## Traceback
The full traceback (if applicable).
```
1279776095
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py", line 192, in handler_worker
    if parser is not None
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py", line 85, in message_parser
    isinstance(update, UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/types/messages_and_media/message.py", line 673, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats, is_chat=False) if not from_user else None
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/types/user_and_chats/chat.py", line 256, in _parse
    return Chat._parse_chat_chat(client, chats[chat_id])
KeyError: 1279776095
1279776095
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py", line 192, in handler_worker
    if parser is not None
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py", line 85, in message_parser
    isinstance(update, UpdateNewScheduledMessage)
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/types/messages_and_media/message.py", line 673, in _parse
    sender_chat = types.Chat._parse(client, message, users, chats, is_chat=False) if not from_user else None
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/types/user_and_chats/chat.py", line 256, in _parse
    return Chat._parse_chat_chat(client, chats[chat_id])
KeyError: 1279776095
```

**Comment by eyMarv** [comment]
Pyrogram tries to send a message to that ID you gave it, but for some reason, the dict 'chats' doesn't contain that ID. I face this too, it's too annoying. Let's wait for Dan to fix it!
