### ISSUE TITLE
iter_chat_members with filter banned

### ISSUE THREAD

**Issue by tasi788** [pyrogram/pyrogram#837]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
``` python
from pyrogram import Client

api_id = 000
api_hash = "000"

with Client("my_accounts", api_id, api_hash) as app:
    chat_id = -1000000
    userlist = app.iter_chat_members(chat_st, filter='banned')
    print(len(userlist))
```

## Traceback
The full traceback (if applicable).

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    userlist = app.iter_chat_members(chat_st, filter='banned')
  File "/Users/tdc/Library/Caches/pypoetry/virtualenvs/testenv-pmNwOFMm-py3.8/lib/python3.8/site-packages/pyrogram/sync.py", line 54, in async_to_sync_wrap
    return loop.run_until_complete(consume_generator(coroutine))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tdc/Library/Caches/pypoetry/virtualenvs/testenv-pmNwOFMm-py3.8/lib/python3.8/site-packages/pyrogram/sync.py", line 34, in consume_generator
    return types.List([i async for i in coroutine])
  File "/Users/tdc/Library/Caches/pypoetry/virtualenvs/testenv-pmNwOFMm-py3.8/lib/python3.8/site-packages/pyrogram/sync.py", line 34, in <listcomp>
    return types.List([i async for i in coroutine])
  File "/Users/tdc/Library/Caches/pypoetry/virtualenvs/testenv-pmNwOFMm-py3.8/lib/python3.8/site-packages/pyrogram/methods/chats/iter_chat_members.py", line 131, in iter_chat_members
    user_id = chat_member.user.id
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by tasi788** [comment]
after some research it should be anonymous channel got banned before
https://github.com/pyrogram/pyrogram/commit/439935b4012eb03ad632c46191055227e9e7c566

**Comment by aditya-yadav-27** [comment]
iter_chat_memebers has been removed, so IMO close or edit the issue accordingly
