### ISSUE TITLE
`filters.group` and similar do not work on `ChatMemberUpdated`

### ISSUE THREAD

**Issue by septatrix** [pyrogram/pyrogram#854]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
  * similar to #56
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
Applying some filters like `filters.group` on `ChatMemberUpdated` types does not work although they contain all the necessary information¹. I think they should either be updated to support these or raise explicit `ValueError`s like `filters.regex` does.

``` python
from pyrogram import Client, filters
bot = Client(
    "foobar",
    api_id="<API_ID>",
    api_hash="<API_HASH>",
    bot_token="<BOT_TOKEN>",
    test_mode=True,
)
bot.on_chat_member_updated(filters.group)(print)
bot.run()
```

## Traceback

```python
ERROR:pyrogram.dispatcher:'ChatForbidden' object has no attribute 'megagroup'
Traceback (most recent call last):
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/dispatcher.py", line 191, in handler_worker
    await parser(update, users, chats)
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/dispatcher.py", line 107, in chat_member_updated_parser
    return pyrogram.types.ChatMemberUpdated._parse(self.client, update, users, chats), ChatMemberUpdatedHandler
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/types/user_and_chats/chat_member_updated.py", line 94, in _parse
    chat=types.Chat._parse_chat(client, chats[chat_id]),
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 327, in _parse_chat
    return Chat._parse_channel_chat(client, chat)
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 224, in _parse_channel_chat
    type="supergroup" if channel.megagroup else "channel",
AttributeError: 'ChatForbidden' object has no attribute 'megagroup'
```

¹ Output without a filter:

```
<pyrogram.client.Client object at 0x7f9e0cd6bfa0> {
    "_": "ChatMemberUpdated",
    "chat": {
        "_": "Chat",
        "id": -327930,
        "type": "group",
        "is_creator": false,
        "title": "Dummy 4",
        "members_count": 0,
        "permissions": {
            "_": "ChatPermissions",
            "can_send_messages": true,
            "can_send_media_messages": true,
            "can_send_stickers": true,
            "can_send_animations": true,
            "can_send_games": true,
            "can_use_inline_bots": true,
            "can_add_web_page_previews": true,
            "can_send_polls": true,
            "can_change_info": true,
            "can_invite_users": true,
            "can_pin_messages": true
        }
   },
...
```

**Comment by delivrance** [comment]
That filter and some others are intended to work with Message objects only. You can create a new one that accepts another type. See https://docs.pyrogram.org/topics/create-filters.

**Comment by septatrix** [comment]
I was experimenting some more and was also able to reproduce this without a filter when deleting the group and a simple `bot.on_raw_update()(print)`

```python
<pyrogram.client.Client object at 0x7f5e61eb7fa0> {
    "_": "types.UpdateChat",
    "chat_id": 907154
} {} {907154: pyrogram.raw.types.ChatForbidden(id=907154, title='asdf')}
ERROR:pyrogram.dispatcher:'ChatForbidden' object has no attribute 'megagroup'
Traceback (most recent call last):
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/dispatcher.py", line 191, in handler_worker
    await parser(update, users, chats)
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/dispatcher.py", line 107, in chat_member_updated_parser
    return pyrogram.types.ChatMemberUpdated._parse(self.client, update, users, chats), ChatMemberUpdatedHandler
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/types/user_and_chats/chat_member_updated.py", line 94, in _parse
    chat=types.Chat._parse_chat(client, chats[chat_id]),
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 327, in _parse_chat
    return Chat._parse_channel_chat(client, chat)
  File "/home/septatrix/Documents/programming/telegram/hCaptcha-bot/venv/lib64/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 224, in _parse_channel_chat
    type="supergroup" if channel.megagroup else "channel",
AttributeError: 'ChatForbidden' object has no attribute 'megagroup'
<pyrogram.client.Client object at 0x7f5e61eb7fa0> {
    "_": "types.UpdateDeleteMessages",
    "messages": [
        89,
        88
    ],
    "pts": 100,
    "pts_count": 2
} {} {}
```

**Comment by septatrix** [comment]
The update which leads to the error (between the two ones which are correctly handled) is this:

```python
DEBUG:pyrogram.session.session:Received:
DEBUG:pyrogram.session.session:{
    "_": "Message",
    "msg_id": 7050101986944504833,
    "seq_no": 15,
    "length": 224,
    "body": {
        "_": "types.Updates",
        "updates": [
            {
                "_": "types.UpdateChatParticipant",
                "chat_id": 39688,
                "date": 1641479783,
                "actor_id": 5000954383,
                "user_id": 2200370494,
                "qts": 638926705,
                "prev_participant": {
                    "_": "types.ChatParticipant",
                    "user_id": 2200370494,
                    "inviter_id": 5000954383,
                    "date": 1641479769
                }
            }
        ],
        "users": [
            {
                "_": "types.User",
                "id": 5000954383,
                "is_self": false,
                "contact": false,
                "mutual_contact": false,
                "deleted": false,
                "bot": false,
                "bot_chat_history": false,
                "bot_nochats": false,
                "verified": false,
                "restricted": false,
                "min": false,
                "bot_inline_geo": false,
                "support": false,
                "scam": false,
                "apply_min_photo": true,
                "fake": false,
                "access_hash": 3161278040159677560,
                "first_name": "N",
                "last_name": "K",
                "status": {
                    "_": "types.UserStatusRecently"
                },
                "restriction_reason": [],
                "lang_code": "en"
            },
            {
                "_": "types.User",
                "id": 2200370494,
                "is_self": true,
                "contact": false,
                "mutual_contact": false,
                "deleted": false,
                "bot": true,
                "bot_chat_history": true,
                "bot_nochats": false,
                "verified": false,
                "restricted": false,
                "min": false,
                "bot_inline_geo": false,
                "support": false,
                "scam": false,
                "apply_min_photo": true,
                "fake": false,
                "access_hash": 3845882199231947966,
                "first_name": "Exmatrikulator",
                "username": "exmatrikulator_bot",
                "bot_info_version": 1,
                "restriction_reason": []
            }
        ],
        "chats": [
            {
                "_": "types.ChatForbidden",
                "id": 39688,
                "title": "asdf"
            }
        ],
        "date": 1641479782,
        "seq": 41
    }
}
```
