### ISSUE TITLE
IndexError: list index out of range | When try to get_users and put in channel name

### ISSUE THREAD

**Issue by daeeros** [pyrogram/pyrogram#874]
## Checklist
- [ +] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [ +] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ +] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
A **clear** and **concise** description of the problem. Code snippets must be
[minimal, reproducible](https://stackoverflow.com/help/minimal-reproducible-example) and properly formatted.

When we try to give channel name in `get_users` function, after execute we getting error IndexError: list index out of range tested like @durov

## Traceback
```
Traceback (most recent call last):
  File "C:\Users\root\Desktop\Main\grootrik\engine\engine.py", line 206, in _handle_update_with_logger
    return await self._handle_update(update, ctx)
  File "C:\Users\root\Desktop\Main\grootrik\engine\engine.py", line 222, in _handle_update
    if await router.handle(update, ctx) != hr.SKIPPED:
  File "C:\Users\root\Desktop\Main\grootrik\engine\router.py", line 96, in handle
    if await handler.handle(update, ctx) != hr.SKIPPED:
  File "C:\Users\root\Desktop\Main\grootrik\plugins\content\idiot_certificate.py", line 18, in _
    target = await ctx.u.parse_user_id(msg)
  File "C:\Users\root\Desktop\Main\grootrik\engine\utils.py", line 107, in parse_user_id
    user = await self.user_api.get_users(selected)
  File "C:\Users\root\Desktop\Main\grootrik\env\lib\site-packages\pyrogram\methods\users\get_users.py", line 70, in get_users
    return users if is_iterable else users[0]
IndexError: list index out of range
```

**Comment by Danstiv** [comment]
I also ran into this problem.
My bot needs functionality to allow users to assign roles to other users.
For example, the issuance of the admin role is performed as follows:
/admin <username>
The /admin command argument is an untrusted input, and anything can be there.
I'm intercepting the BadRequest exception, but as it turns out, passing the channel's username raises an IndexError.
If i pass the username of the channel in a list, the method returns an empty list, which looks a little better, but is still not the expected behavior.
