### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'handlers'

### ISSUE THREAD

**Issue by MrBotDeveloper** [pyrogram/pyrogram#875]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description

Pyrogram is giving error on setting the `on_message` decorator.

My `requirements.txt` is as follows :

```txt
https://github.com/pyrogram/pyrogram/archive/master.zip
tgcrypto

...
```

My `bot.py` is as following...

``` python
from pyrogram import Client

if __name__ == "__main__":
    plugins = dict(root="plugins")
    app = Client(
        "TestBot",
        bot_token=TG_BOT_TOKEN,
        api_id=API_ID,
        api_hash=API_HASH,
        plugins=plugins
    )
    app.run()
```

My `plugins/__main__.py` is as follows:

```python
from pyrogram import Client
from pyrogram import filters

@Client.on_message(filters.command("start") & filters.private)
async def startprivate(client, message):
    await message.reply_text("Hello 👋....", quote=True)

...
```

## Traceback
The full traceback is as follows :

```
2022-01-20T11:10:11.986323+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-20T11:10:11.986334+00:00 app[worker.1]:   File "/app/bot.py", line 12, in <module>
2022-01-20T11:10:11.986419+00:00 app[worker.1]:     app.run()
2022-01-20T11:10:11.986437+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/run.py", line 58, in run
2022-01-20T11:10:11.986510+00:00 app[worker.1]:     self.start()
2022-01-20T11:10:11.986518+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
2022-01-20T11:10:11.986588+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2022-01-20T11:10:11.986595+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2022-01-20T11:10:11.986760+00:00 app[worker.1]:     return future.result()
2022-01-20T11:10:11.986768+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 67, in start
2022-01-20T11:10:11.986838+00:00 app[worker.1]:     await self.initialize()
2022-01-20T11:10:11.986847+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2022-01-20T11:10:11.986913+00:00 app[worker.1]:     self.load_plugins()
2022-01-20T11:10:11.986921+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 723, in load_plugins
2022-01-20T11:10:11.987102+00:00 app[worker.1]:     module = import_module(module_path)
2022-01-20T11:10:11.987111+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-01-20T11:10:11.987184+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-01-20T11:10:11.987192+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-01-20T11:10:11.987271+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-01-20T11:10:11.987313+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2022-01-20T11:10:11.987354+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2022-01-20T11:10:11.987395+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2022-01-20T11:10:11.987445+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-01-20T11:10:11.987488+00:00 app[worker.1]:   File "/app/plugins/__main__.py", line 4, in <module>
2022-01-20T11:10:11.987557+00:00 app[worker.1]:     async def startprivate(client, message):
2022-01-20T11:10:11.987565+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/decorators/on_message.py", line 51, in decorator
2022-01-20T11:10:11.987635+00:00 app[worker.1]:     func.handlers = []
2022-01-20T11:10:11.987657+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'handlers'
2022-01-20T11:10:12.270960+00:00 heroku[worker.1]: Process exited with status 1
```

I hope it gets fix ASAP...

**Comment by MrBotDeveloper** [comment]
@delivrance is there any update or support on my issue ??

**Comment by delivrance** [comment]
The provided mwe doesn't reproduce any issue (it is working as expected).

**Comment by MrBotDeveloper** [comment]
Sir but same is producing the error for me ? 🤔
