### ISSUE TITLE
Receiving `TypeError` on send a raw update.

### ISSUE THREAD

**Issue by MrBotDeveloper** [pyrogram/pyrogram#890]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am trying to send a raw update using `await client.send()` but it is generating an `TypeError`. I have provided all the necessary things required to send.

### Steps to reproduce

1. Start a client
2. Try to send any raw update using `await client.send()`

### Logs

```shell
2022-02-02T12:47:28.183762+00:00 app[web.1]: TypeError: write() missing 1 required positional argument: 'client'
2022-02-02T12:47:51.844500+00:00 app[web.1]: 2022-02-02 12:47:51,844 - pyrogram.dispatcher - ERROR - write() missing 1 required positional argument: 'client'
2022-02-02T12:47:51.844506+00:00 app[web.1]: Traceback (most recent call last):
2022-02-02T12:47:51.844507+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-02-02T12:47:51.844507+00:00 app[web.1]:     await handler.callback(self.client, *args)
2022-02-02T12:47:51.844508+00:00 app[web.1]:   File "/app/Captcha-Bot/plugins/__main__.py", line 237, in demo_callback_handlers
2022-02-02T12:47:51.844509+00:00 app[web.1]:     await poll_demo(bot, cb)
2022-02-02T12:47:51.844509+00:00 app[web.1]:   File "/app/Captcha-Bot/plugins/demo.py", line 200, in poll_demo
2022-02-02T12:47:51.844509+00:00 app[web.1]:     sent_poll = await client.send(
2022-02-02T12:47:51.844510+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2022-02-02T12:47:51.844510+00:00 app[web.1]:     r = await self.session.send(
2022-02-02T12:47:51.844510+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 362, in send
2022-02-02T12:47:51.844511+00:00 app[web.1]:     return await self._send(data, timeout=timeout)
2022-02-02T12:47:51.844511+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 291, in _send
2022-02-02T12:47:51.844512+00:00 app[web.1]:     message = self.msg_factory(data)
2022-02-02T12:47:51.844512+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
2022-02-02T12:47:51.844513+00:00 app[web.1]:     len(body)
2022-02-02T12:47:51.844513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 76, in __len__
2022-02-02T12:47:51.844513+00:00 app[web.1]:     return len(self.write())
2022-02-02T12:47:51.844513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/raw/functions/messages/send_media.py", line 133, in write
2022-02-02T12:47:51.844514+00:00 app[web.1]:     b.write(self.reply_markup.write())
2022-02-02T12:47:51.844514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
2022-02-02T12:47:51.844514+00:00 app[web.1]:     coroutine = function(*args, **kwargs)
2022-02-02T12:47:51.844514+00:00 app[web.1]: TypeError: write() missing 1 required positional argument: 'client'
```

**Comment by delivrance** [comment]
The report is incomplete. You must provide precise steps on how to reproduce an issue, possibly with code snippets.

**Comment by MrBotDeveloper** [comment]
@delivrance 

**You can regenerate this error using :**

```python3
from pyrogram import Client
from pyrogram.raw.types import InputMediaPoll, Poll, PollAnswer, InputPeerChat
from pyrogram.raw import functions
from random import randint
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton

with Client(
    "App",
    bot_token=token,
    api_id=api_id,
    api_hash=api_hash,
) as app:
    max_time = 30
    question = "This is a test ....."
    options = [
        PollAnswer(text="Hi", option="828"),
        PollAnswer(text="Hi 2", option="999"),
    ]
    ans_id = "999"
    chat = InputPeerChat(chat_id=some_chat_id)
    final_poll = InputMediaPoll(
        poll=Poll(
            id=randint(0, 99),
            question=question,
            answers=options,
            closed=False,
            public_voters=True,
            quiz=True,
            close_period=int(max_time),
        ),
        correct_answers=[ans_id],
    )
    app.send(
        functions.messages.SendMedia(
            peer=chat,
            media=final_poll,
            message="",
            random_id=randint(0, 9999),
            reply_markup=InlineKeyboardMarkup(
                [
                    [
                        InlineKeyboardButton(
                            "Some_Text",
                            callback_data=f"some_callback",
                        )
                    ]
                ]
            )
        )
    )
```

**Comment by MrBotDeveloper** [comment]
@delivrance is there any update on my issue ??

**Comment by MrBotDeveloper** [comment]
@delivrance Sir, is there any update on my issue ??

**Comment by MrBotDeveloper** [comment]
@delivrance Sir, I am waiting for your response......

**Comment by MrBotDeveloper** [comment]
@delivrance you can inform if the fix is being run on it ??

**Comment by MrBotDeveloper** [comment]
> You are mixing raw and high level types. This is not an issue with the library.

Then what's creating this issue ?

**Comment by MrBotDeveloper** [comment]
> You are mixing raw and high level types. This is not an issue with the library.

@delivrance Sir as far as I think this is not an error as it is possible by telegram here you can see [here](https://core.telegram.org/bots/api#sendpoll)......

**Comment by MrBotDeveloper** [comment]
@delivrance sir I am waiting for your response 😅

**Comment by MrBotDeveloper** [comment]
@delivrance sir ??

**Comment by MrBotDeveloper** [comment]
@delivrance sir I waiting for your response.....
