### ISSUE TITLE
Can't get dialogs

### ISSUE THREAD

**Issue by i-paya** [pyrogram/pyrogram#9]
Hi .
I want to retrieve all dialogs but it shows this error : 

> Traceback (most recent call last):
  File "b.py", line 8, in <module>
    print  (client.send(functions.messages.GetDialogs(offset_date = 1517078500 ,offset_id = 1,offset_peer= types.InputPeerSelf ,limit = 100 , )))
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/client.py", line 170, in send
    return self.session.send(data)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 400, in send
    return self._send(data)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/session.py", line 370, in _send
    message = self.msg_factory(data)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/session/internals/msg_factory.py", line 38, in __call__
    len(body)
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/core/object.py", line 44, in __len__
    return len(self.write())
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/api/functions/messages/get_dialogs.py", line 78, in write
    b.write(self.offset_peer.write())
TypeError: write() missing 1 required positional argument: 'self'

**Comment by delivrance** [comment]
Hi, You forgot `()` in `offset_peer=types.InputPeerSelf`, should be `offset_peer=types.InputPeerSelf()`
