### ISSUE TITLE
app.copy_message returns 400 USERNAME_NOT_OCCUPIED

### ISSUE THREAD

**Issue by marvic2409** [pyrogram/pyrogram#904]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

So using the app.copy_message(channeltocopyto, messagechatid, messageid) method, I get the error 400 USERNAME_NOT_OCCUPIED. The channeltocopyto hold the name of the channel in which the user is an admin in. It seems that the client is trying to send the message copy to a user named with the channel name, while I need it to send it to the actual channel. 

### Steps to reproduce

Use the copy_message and pass the name of a channel as the place to copy the message to

### Code example

```python
from pyrogram import Client, filters


app = Client('bot')

config = {
    'forward_from_channels' : 'tyjnregwrghrth'

}

with open('config.json', 'r') as f:
    config = json.load(f)
@app.on_message((filters.photo | filters.document) & (filters.channel | filters.group) & filters.incoming & ~filters.new_chat_photo)
def on_file(_, message):
    if message.chat.title in config["forward_from_channels"]:
        print("test")
        caption = ''
        if message.caption is None or len([ent for ent in message.caption if ent.type == 'url' or ent.type == 'mention']) == 0:
            caption = message.caption
        app.copy_message(config["forward_to_channel"][0], message.chat.id, message.message_id, caption=caption)
        print(f'Media forwarded from {message.chat.username or message.chat.first_name or message.chat.title}')
app.run()
```

### Logs

```shell
Telegram says: [400 USERNAME_NOT_OCCUPIED] - The username is not occupied by anyone (caused by "contacts.ResolveUsername")
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 147, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: tyjnregwrghrth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 69, in resolve_peer
    int(peer_id)
ValueError: invalid literal for int() with base 10: 'tyjnregwrghrth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 72, in resolve_peer
    return await self.storage.get_peer_by_username(peer_id)
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 158, in get_peer_by_username
    raise KeyError(f"Username not found: {username}")
KeyError: 'Username not found: tyjnregwrghrth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nvme/forwarding/main1.py", line 22, in on_file
    app.copy_message(config["forward_to_channel"][0], message.chat.id, message.message_id, caption=caption)
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/messages/copy_message.py", line 111, in copy_message
    return await message.copy(
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 3099, in copy
    return await send_media(
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/messages/send_cached_media.py", line 103, in send_cached_media
    peer=await self.resolve_peer(chat_id),
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 74, in resolve_peer
    await self.send(
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UsernameNotOccupied: Telegram says: [400 USERNAME_NOT_OCCUPIED] - The username is not occupied by anyone (caused by "contacts.ResolveUsername")
```

**Comment by delivrance** [comment]
> Telegram says: [400 USERNAME_NOT_OCCUPIED] - The username is not occupied by anyone

The error is pretty clear.
