### ISSUE TITLE
GetAdminedPublicChannels Fails to list channels in which user is admin

### ISSUE THREAD

**Issue by marvic2409** [pyrogram/pyrogram#906]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When calling functions.channels.GetAdminedPublicChannels() nothing is returned even when the user is an admin in a public channel. Iterating over the returned data also returns an error. 

### Steps to reproduce

Call  functions.channels.GetAdminedPublicChannels()  

### Code example

```python
from pyrogram import Client, filters
from pyrogram.raw import functions

app = Client('bot')

@app.on_message()
def on_file(_, message):
    print(functions.channels.GetAdminedPublicChannels())
app.run()
```

### Logs

```shell
{
    "_": "functions.channels.GetAdminedPublicChannels"
}


When Iterating over the returned object:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nvme/forwarding/main1.py", line 43, in on_file
    for item in functions.channels.GetAdminedPublicChannels():
  File "/home/user/.local/lib/python3.10/site-packages/pyrogram/raw/core/tl_object.py", line 79, in __getitem__
    return getattr(self, item)
TypeError: getattr(): attribute name must be string
```

**Comment by delivrance** [comment]
You have to actually invoke the raw function. Raw function invocations work differently, see https://docs.pyrogram.org/topics/advanced-usage.

**Comment by marvic2409** [comment]
Even running it like that it still returns nothing. Heres the new code I wrote:

```from pyrogram import Client, filters
from pyrogram.raw import functions


with Client('bot') as app:
    print(app.send(functions.channels.GetAdminedPublicChannels()))
```
and the response 

```
{
    "_": "types.messages.Chats",
    "chats": []
}
```

**Comment by marvic2409** [comment]
So is there any way to actually get the id of the channels that the user is an admin in? Because the account is an admin in 2 public channels and its not showing up

**Comment by delivrance** [comment]
Despite the name, the function actually returns the owned public chats only. Part of the docs here explains it: https://docs.pyrogram.org/telegram/functions/channels/get-admined-public-channels. If you want to get a list of admined chats you have to iterate through dialogs, filter public channels in and check whether you are an admin or not.
