### ISSUE TITLE
Receiving `TypeError` on sending an quiz using raw update.

### ISSUE THREAD

**Issue by MrBotDeveloper** [pyrogram/pyrogram#913]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

This is a clone of this [issue](https://github.com/pyrogram/pyrogram/issues/890)

**Why I am opening the same issue again ?**

As I think my that issue is not more given any concern as i can't get my all issues fixed.

I am trying to send a quiz using raw update using await `client.send()` but it is generating an `TypeError`. I have provided all the necessary things required to send. I think this is not an error due to the mixing of raw and high level types as it is possible by telegram here you can see [here](https://core.telegram.org/bots/api#sendpoll) and [here also](https://github.com/pyrogram/pyrogram/blob/54f8ca25fb40f3ef953b6aded34ee1839d87ae81/pyrogram/methods/messages/send_poll.py#L125)...... 

https://github.com/pyrogram/pyrogram/blob/54f8ca25fb40f3ef953b6aded34ee1839d87ae81/pyrogram/methods/messages/send_poll.py#L125

### Steps to reproduce

1. Start a client
2. Run the sample code below...

### Code example

```python
from pyrogram import Client
from pyrogram.raw.types import InputMediaPoll, Poll, PollAnswer, InputPeerChat
from pyrogram.raw import functions
from random import randint
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton

with Client(
    "App",
    bot_token=token,
    api_id=api_id,
    api_hash=api_hash,
) as app:
    max_time = 30
    question = "This is a test ....."
    options = [
        PollAnswer(text="Hi", option="828"),
        PollAnswer(text="Hi 2", option="999"),
    ]
    ans_id = "999"
    chat = InputPeerChat(chat_id=some_chat_id)
    final_poll = InputMediaPoll(
        poll=Poll(
            id=randint(0, 99),
            question=question,
            answers=options,
            closed=False,
            public_voters=True,
            quiz=True,
            close_period=int(max_time),
        ),
        correct_answers=[ans_id],
    )
    app.send(
        functions.messages.SendMedia(
            peer=chat,
            media=final_poll,
            message="",
            random_id=randint(0, 9999),
            reply_markup=InlineKeyboardMarkup(
                [
                    [
                        InlineKeyboardButton(
                            "Some_Text",
                            callback_data=f"some_callback",
                        )
                    ]
                ]
            )
        )
    )
```

### Logs

```shell
2022-02-02T12:47:28.183762+00:00 app[web.1]: TypeError: write() missing 1 required positional argument: 'client'
2022-02-02T12:47:51.844500+00:00 app[web.1]: 2022-02-02 12:47:51,844 - pyrogram.dispatcher - ERROR - write() missing 1 required positional argument: 'client'
2022-02-02T12:47:51.844506+00:00 app[web.1]: Traceback (most recent call last):
2022-02-02T12:47:51.844507+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-02-02T12:47:51.844507+00:00 app[web.1]:     await handler.callback(self.client, *args)
2022-02-02T12:47:51.844508+00:00 app[web.1]:   File "/app/Captcha-Bot/plugins/__main__.py", line 237, in demo_callback_handlers
2022-02-02T12:47:51.844509+00:00 app[web.1]:     await poll_demo(bot, cb)
2022-02-02T12:47:51.844509+00:00 app[web.1]:   File "/app/Captcha-Bot/plugins/demo.py", line 200, in poll_demo
2022-02-02T12:47:51.844509+00:00 app[web.1]:     sent_poll = await client.send(
2022-02-02T12:47:51.844510+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2022-02-02T12:47:51.844510+00:00 app[web.1]:     r = await self.session.send(
2022-02-02T12:47:51.844510+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 362, in send
2022-02-02T12:47:51.844511+00:00 app[web.1]:     return await self._send(data, timeout=timeout)
2022-02-02T12:47:51.844511+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 291, in _send
2022-02-02T12:47:51.844512+00:00 app[web.1]:     message = self.msg_factory(data)
2022-02-02T12:47:51.844512+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/internals/msg_factory.py", line 37, in __call__
2022-02-02T12:47:51.844513+00:00 app[web.1]:     len(body)
2022-02-02T12:47:51.844513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/raw/core/tl_object.py", line 76, in __len__
2022-02-02T12:47:51.844513+00:00 app[web.1]:     return len(self.write())
2022-02-02T12:47:51.844513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/raw/functions/messages/send_media.py", line 133, in write
2022-02-02T12:47:51.844514+00:00 app[web.1]:     b.write(self.reply_markup.write())
2022-02-02T12:47:51.844514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
2022-02-02T12:47:51.844514+00:00 app[web.1]:     coroutine = function(*args, **kwargs)
2022-02-02T12:47:51.844514+00:00 app[web.1]: TypeError: write() missing 1 required positional argument: 'client'
```

**Comment by delivrance** [comment]
The issue section in GitHub is for actual issues within the library and not issues with your code. There is no library issue in this case.

Sending quizes is done by using https://docs.pyrogram.org/api/methods/send_poll and passing the correct type.

If you want to ask a question on how to do something you can do so at stackoverflow.
If you believe a feature is missing or needs to be enhanced you can open an enhancement issue for it.

**Comment by MrBotDeveloper** [comment]
@delivrance sir i have already pointed out you that `send_poll()` doesn't allow the option of `close_period`.

**Comment by MrBotDeveloper** [comment]
and in the example code also i have tried to send a quiz with `close_period` value thats what that make me to use the raw update....... as normal `send_poll()` doesn't allow `close_period`.................

**Comment by MrBotDeveloper** [comment]
or sir you kindly tell me the way to send a quiz with `close_period` ??

**Comment by MrBotDeveloper** [comment]
or i think i should open an `Enhancement issue` for the `send_poll()`..........
