### ISSUE TITLE
await coroutines in `FileStorage.migrate_from_json`

### ISSUE THREAD

**Issue by VoxLight** [pyrogram/pyrogram#918]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

There are multiple coroutines in the FileStorage.migrate_from_json that are not awaited. This just causes a lot of issues. After awaiting all the calls manually in the package in my env, I was able to get Pyrogram to generate the upgraded .session, with usernames and types all NULL.

### Steps to reproduce

Install Pyrogram

Include a JSON formatted .session file in the directory next to your main.py where you run pyrogram.Client.run (mine was generated from Pyrogram 0.11.0)

Watch the no-await warnings flood the console.

### Code example

```python
from pyrogram import Client, filters


tg = Client(
    "Name", 
    api_id=12345, 
    api_hash="token"
)


@tg.on_message(filters.private)
async def hello(client, message):
    # await message.reply("Hello from Pyrogram!")
    pass

tg.run()


"""
Then, in the same directory as this .py file, include a JSON formatted .session file from
an older version of Pyrogram. The one I tested with was generated with Pyrogram 0.11.0.
"""
```

### Logs

```shell
(env) D:\Coding\Python\pyrogram data\1.4 dev>py main.py
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/tgcrypto
JSON session storage detected! Converting it into an SQLite session storage...
The old session file has been renamed to "Name.session.OLD"
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:40: RuntimeWarning: coroutine 'FileStorage.open' was never awaited
  self.open()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:42: RuntimeWarning: coroutine 'SQLiteStorage.dc_id' was never awaited
  self.dc_id(session_json["dc_id"])
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:43: RuntimeWarning: coroutine 'SQLiteStorage.test_mode' was never awaited
  self.test_mode(session_json["test_mode"])
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:44: RuntimeWarning: coroutine 'SQLiteStorage.auth_key' was never awaited
  self.auth_key(base64.b64decode("".join(session_json["auth_key"])))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:45: RuntimeWarning: coroutine 'SQLiteStorage.user_id' was never awaited
  self.user_id(session_json["user_id"])
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:46: RuntimeWarning: coroutine 'SQLiteStorage.date' was never awaited
  self.date(session_json.get("date", 0))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:47: RuntimeWarning: coroutine 'SQLiteStorage.is_bot' was never awaited
  self.is_bot(session_json.get("is_bot", False))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\file_storage.py:68: RuntimeWarning: coroutine 'SQLiteStorage.update_peers' was never awaited
  self.update_peers(peers.values())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Done! The session has been successfully converted from JSON to SQLite storage
Traceback (most recent call last):
  File "D:\Coding\Python\pyrogram data\1.4 dev\main.py", line 19, in <module>
    tg.run()
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\methods\utilities\run.py", line 58, in run
    self.start()
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\tkkt3\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\methods\utilities\start.py", line 52, in start
    is_authorized = await self.connect()
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\methods\auth\connect.py", line 39, in connect
    await self.load_session()
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\client.py", line 680, in load_session
    await self.storage.test_mode() is None,
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\sqlite_storage.py", line 199, in test_mode
    return self._accessor(value)
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\sqlite_storage.py", line 193, in _accessor
    return self._get() if value == object else self._set(value)
  File "D:\Coding\Python\pyrogram data\1.4 dev\env\lib\site-packages\pyrogram\storage\sqlite_storage.py", line 179, in _get
    return self.conn.execute(
AttributeError: 'NoneType' object has no attribute 'execute'tq
```

**Comment by delivrance** [comment]
https://github.com/pyrogram/pyrogram/pull/920#issuecomment-1055803339
