### ISSUE TITLE
TimeoutError() while downloading a file.

### ISSUE THREAD

**Issue by stefanodvx** [pyrogram/pyrogram#932]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When I download a file using Pyrogram the downloads start and goes on, but when its near to end, i get a TimeoutError() and if i try again i get the error anyway. YES, I have TgCrypto installed, Im not a retard. Also I always downloaded files using Pyro, but recently Im facing this issue randomly.

### Steps to reproduce

Just download a big file.

### Logs

```shell
Traceback (most recent call last):
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/client.py", line 946, in get_file
    r = await session.send(
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 382, in send
    return await self.send(data, retries - 1, timeout)
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 382, in send
    return await self.send(data, retries - 1, timeout)
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 382, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 375, in send
    raise e from None
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/home/wicked/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 327, in _send
    raise TimeoutError
TimeoutError
```

**Comment by delivrance** [comment]
> Also I always downloaded files using Pyro, but recently Im facing this issue randomly.

Since nothing changed at the client side, it happens "randomly" without a proper way to reproduce it consistently and it only started recently, the issue must be at the server side or your/Telegram's network.
