### ISSUE TITLE
raised TimeoutError by pyrogram session

### ISSUE THREAD

**Issue by Sunda001** [pyrogram/pyrogram#986]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Actually i have never gotten this errors before, its like almost a year with old pyrogram version (v1.4) but when i use pyrogram (v2) the latest one, it throws these erors, for the first time i get this error...

### Steps to reproduce

1. I was just trying to delete a bunch messages
2. Using delete_messages function and using gather 
3. Using them on while loop
4. Throw errors and the script was stopped 

### Logs

```shell
[5] Retrying "channels.DeleteMessages" due to TimeoutError()
[5] Retrying "channels.DeleteMessages" due to TimeoutError()
[5] Retrying "channels.DeleteMessages" due to TimeoutError()
[5] Retrying "channels.DeleteMessages" due to TimeoutError()
Traceback (most recent call last):
  File "/root/live_draw/task_logger.py", line 26, in _penanganan_tugas
    task.result()
  File "live.py", line 1205, in china
    res = await kirim_pesan(ll, await LiveDraw().china(), _saring)
  File "live.py", line 1102, in kirim_pesan
    await _k()
  File "live.py", line 1098, in _k
    await kirim_hapus(txt, _saring)
  File "live.py", line 1036, in kirim_hapus
    await gather(*[bot.delete_messages(x['cid'], x['mid']) for x in _hapus['hapus']])
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/methods/messages/delete_messages.py", line 69, in delete_messages
    r = await self.invoke(
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/session/session.py", line 380, in invoke
    return await self.invoke(query, retries - 1, timeout)
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/session/session.py", line 380, in invoke
    return await self.invoke(query, retries - 1, timeout)
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/session/session.py", line 380, in invoke
    return await self.invoke(query, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/session/session.py", line 373, in invoke
    raise e from None
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/session/session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "/root/live_draw/live/lib/python3.8/site-packages/pyrogram/session/session.py", line 327, in send
    raise TimeoutError
TimeoutError
```

**Comment by delivrance** [comment]
https://docs.pyrogram.org/faq/socket-send-raised-exception-oserror-timeouterror
